// Code generated by velox. DO NOT EDIT.

package user

import (
	predicate "github.com/syssam/graphql-go/examples/veloxfx/velox/predicate"
	sql "github.com/syssam/velox/dialect/sql"
	sqlgraph "github.com/syssam/velox/dialect/sql/sqlgraph"
	runtime "github.com/syssam/velox/runtime"
)

const (
	// Label holds the string label denoting the User type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// EdgeTodos holds the string denoting the todos edge name in mutations.
	EdgeTodos = "todos"
	// Table holds the table name of the User in the database.
	Table = "users"
	// TodosTable is the table that holds the todos relation/edge.
	TodosTable = "todos"
	// TodosInverseTable is the table name for the Todo entity.
	// It exists in this package in order to avoid circular dependency with the "todo" package.
	TodosInverseTable = "todos"
	// TodosColumn is the table column denoting the todos relation/edge.
	TodosColumn = "user_todos"
)

// Columns holds all SQL columns for User fields.
var Columns = []string{FieldID, FieldName, FieldEmail}

// ForeignKeys holds the SQL foreign-keys that are owned by the "users"
// table and are not defined as standalone fields in the schema.
var ForeignKeys []string

// columnSet holds the set of valid column names for O(1) lookups.
var columnSet = func() map[string]struct{} {
	s := make(map[string]struct{}, 3)
	for _, c := range Columns {
		s[c] = struct{}{}
	}
	return s
}()

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	_, ok := columnSet[column]
	return ok
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByTodosCount orders the results by todos count.
func ByTodosCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTodosStep(), opts...)
	}
}

// ByTodos orders the results by todos terms.
func ByTodos(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTodosStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTodosStep() *sqlgraph.Step {
	return sqlgraph.NewStep(sqlgraph.From(Table, FieldID), sqlgraph.To(TodosInverseTable, FieldID), sqlgraph.Edge(sqlgraph.O2M, false, TodosTable, TodosColumn))
}

// =============================================================================
// LoadOption helpers (functional options for edge loading)
// =============================================================================

// Where returns a LoadOption that adds predicates to the edge query.
func Where(ps ...predicate.User) runtime.LoadOption {
	return func(c *runtime.LoadConfig) {
		for _, p := range ps {
			c.Predicates = append(c.Predicates, (func(*sql.Selector))(p))
		}
	}
}

// Select returns a LoadOption that selects specific fields.
func Select(fields ...string) runtime.LoadOption {
	return runtime.Select(fields...)
}

// Limit returns a LoadOption that limits the number of results.
func Limit(n int) runtime.LoadOption {
	return runtime.Limit(n)
}

// OrderBy returns a LoadOption that orders the results.
func OrderBy(o ...func(*sql.Selector)) runtime.LoadOption {
	return runtime.OrderBy(o...)
}

// WithTodos returns a LoadOption that eager-loads the "todos" edge.
func WithTodos(opts ...runtime.LoadOption) runtime.LoadOption {
	return runtime.WithEdge("todos", opts...)
}
