// Code generated by velox. DO NOT EDIT.

package user

import (
	predicate "github.com/syssam/graphql-go/examples/veloxfx/velox/predicate"
	sql "github.com/syssam/velox/dialect/sql"
	sqlgraph "github.com/syssam/velox/dialect/sql/sqlgraph"
)

// IDField is the predicate for the id field.
var IDField = sql.IntField[predicate.User](FieldID)

// NameField is the predicate for the "name" field.
var NameField = sql.StringField[predicate.User](FieldName)

// EmailField is the predicate for the "email" field.
var EmailField = sql.StringField[predicate.User](FieldEmail)

// HasTodos applies the HasEdge predicate on the "todos" edge.
func HasTodos() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(sqlgraph.From(Table, FieldID), sqlgraph.Edge(sqlgraph.O2M, false, TodosTable, TodosColumn))
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTodosWith applies the HasEdge predicate on the "todos" edge with a given conditions (other predicates).
func HasTodosWith(preds ...predicate.Todo) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newTodosStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
var And = sql.PredicateAnd[predicate.User]

// Or groups predicates with the OR operator between them.
var Or = sql.PredicateOr[predicate.User]

// Not applies the not operator on the given predicate.
var Not = sql.PredicateNot[predicate.User]
