// Code generated by velox. DO NOT EDIT.

package warehouseclient

import (
	"context"
	"errors"
	"fmt"

	entity "github.com/syssam/graphql-go/examples/veloxfx/velox/entity"
	warehouse "github.com/syssam/graphql-go/examples/veloxfx/velox/warehouse"
	velox "github.com/syssam/velox"
	sqlgraph "github.com/syssam/velox/dialect/sql/sqlgraph"
	runtime "github.com/syssam/velox/runtime"
	field "github.com/syssam/velox/schema/field"
)

// warehouseIDFieldType is the field.Type for Warehouse's primary key column.
var warehouseIDFieldType = field.TypeInt

// warehouseFieldTypes maps column names to field.Type for Warehouse.
var warehouseFieldTypes = map[string]field.Type{"id": field.TypeInt, "name": field.TypeString}

// WarehouseCreate is the builder for creating a Warehouse entity.
type WarehouseCreate struct {
	config   runtime.Config
	mutation *WarehouseMutation
	hooks    []runtime.Hook
}

// NewWarehouseCreate creates a new WarehouseCreate builder.
func NewWarehouseCreate(c runtime.Config, mutation *WarehouseMutation, hooks []runtime.Hook) *WarehouseCreate {
	return &WarehouseCreate{
		config:   c,
		hooks:    hooks,
		mutation: mutation,
	}
}

// SetName sets the "name" field.
func (c *WarehouseCreate) SetName(v string) *WarehouseCreate {
	c.mutation.SetName(v)
	return c
}

// AddStockIDs adds the "stocks" edge by ids.
func (c *WarehouseCreate) AddStockIDs(ids ...int) *WarehouseCreate {
	c.mutation.AddStockIDs(ids...)
	return c
}

// AddOrderIDs adds the "orders" edge by ids.
func (c *WarehouseCreate) AddOrderIDs(ids ...int) *WarehouseCreate {
	c.mutation.AddOrderIDs(ids...)
	return c
}

// AddStocks adds the "stocks" edge to the given entities.
func (c *WarehouseCreate) AddStocks(v ...*entity.Stock) *WarehouseCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	c.AddStockIDs(ids...)
	return c
}

// AddOrders adds the "orders" edge to the given entities.
func (c *WarehouseCreate) AddOrders(v ...*entity.Order) *WarehouseCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	c.AddOrderIDs(ids...)
	return c
}

// Mutation returns the WarehouseMutation.
func (c *WarehouseCreate) Mutation() *WarehouseMutation {
	return c.mutation
}

// check runs all checks and user-defined validators on the builder.
func (c *WarehouseCreate) check() error {
	if _, ok := c.mutation.Name(); !ok {
		return &runtime.ValidationError{
			Entity: "Warehouse",
			Err:    errors.New("missing required field \"Warehouse.name\""),
			Field:  "name",
			Name:   "name",
		}
	}
	if v, ok := c.mutation.Name(); ok {
		if err := warehouse.NameValidator(v); err != nil {
			return &runtime.ValidationError{
				Entity: "Warehouse",
				Err:    fmt.Errorf("validator failed for field \"Warehouse.name\": %w", err),
				Field:  "name",
				Name:   "name",
			}
		}
	}
	return nil
}

// sqlSave executes the SQL create for Warehouse after hooks have run.
func (c *WarehouseCreate) sqlSave(ctx context.Context) (*entity.Warehouse, error) {
	if err := c.check(); err != nil {
		return nil, err
	}
	_node, _spec := c.createSpec()
	if err := sqlgraph.CreateNode(ctx, c.config.Driver, _spec); err != nil {
		return nil, runtime.MayWrapConstraintError(err)
	}
	_node.SetConfig(c.config)
	if _spec.ID.Value != nil {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	c.mutation.SetID(_node.ID)
	return _node, nil
}

// createSpec builds the Warehouse node and sqlgraph.CreateSpec from mutation fields.
func (c *WarehouseCreate) createSpec() (*entity.Warehouse, *sqlgraph.CreateSpec) {
	var (
		_node = &entity.Warehouse{}
		_spec = sqlgraph.NewCreateSpec(warehouse.Table, &sqlgraph.FieldSpec{
			Column: warehouse.FieldID,
			Type:   warehouseIDFieldType,
		})
	)
	if c.mutation._name != nil {
		v := *c.mutation._name
		_spec.SetField("name", field.TypeString, v)
		_node.Name = v
	}
	if nodes := c.mutation.StocksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"warehouse_stocks"},
			Inverse: false,
			Rel:     sqlgraph.O2M,
			Table:   "stocks",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := c.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"warehouse_orders"},
			Inverse: false,
			Rel:     sqlgraph.O2M,
			Table:   "orders",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// Save creates the Warehouse in the database.
func (c *WarehouseCreate) Save(ctx context.Context) (*entity.Warehouse, error) {
	hooks := c.hooks
	return velox.WithHooks[*entity.Warehouse, WarehouseMutation, *WarehouseMutation](ctx, c.sqlSave, c.mutation, hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (c *WarehouseCreate) SaveX(ctx context.Context) *entity.Warehouse {
	v, err := c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (c *WarehouseCreate) Exec(ctx context.Context) error {
	_, err := c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (c *WarehouseCreate) ExecX(ctx context.Context) {
	if err := c.Exec(ctx); err != nil {
		panic(err)
	}
}

// WarehouseCreateBulk is the builder for creating many Warehouse entities in bulk.
type WarehouseCreateBulk struct {
	config    runtime.Config
	err       error
	builders  []*WarehouseCreate
	batchSize int
}

// NewWarehouseCreateBulk creates a new WarehouseCreateBulk builder.
func NewWarehouseCreateBulk(c runtime.Config, builders []*WarehouseCreate) *WarehouseCreateBulk {
	return &WarehouseCreateBulk{
		builders: builders,
		config:   c,
	}
}

// BatchSize sets the chunk size for the bulk insert.
// A value of 0 (default) means no chunking — all builders
// go through a single BatchCreate. When set, Save splits the
// builders into chunks of at most n and runs one INSERT per
// chunk. Use this to stay under SQLite's SQL-variable cap.
//
// Atomicity across chunks is NOT automatic. Wrap the call
// in client.Tx(ctx) if you need all-or-nothing semantics.
func (_cb *WarehouseCreateBulk) BatchSize(n int) *WarehouseCreateBulk {
	_cb.batchSize = n
	return _cb
}

// Save creates the Warehouse entities in the database.
//
// When BatchSize is 0 (default), all builders go through a
// single mutator chain ending in one BatchCreate. When
// BatchSize > 0, the builders are sliced into chunks of at
// most N and each chunk runs its own mutator chain + one
// INSERT. A mid-loop error returns the rows persisted so far
// together with the error — wrap in client.Tx(ctx) for
// all-or-nothing semantics.
func (_cb *WarehouseCreateBulk) Save(ctx context.Context) ([]*entity.Warehouse, error) {
	if _cb.err != nil {
		return nil, _cb.err
	}
	if _cb.batchSize <= 0 || _cb.batchSize >= len(_cb.builders) {
		return _cb.saveChunk(ctx, _cb.builders)
	}
	nodes := make([]*entity.Warehouse, 0, len(_cb.builders))
	for start := 0; start < len(_cb.builders); start += _cb.batchSize {
		end := start + _cb.batchSize
		if end > len(_cb.builders) {
			end = len(_cb.builders)
		}
		chunk, err := _cb.saveChunk(ctx, _cb.builders[start:end])
		nodes = append(nodes, chunk...)
		if err != nil {
			return nodes, err
		}
	}
	return nodes, nil
}

// saveChunk runs one mutator chain over a sub-slice of the builders.
func (_cb *WarehouseCreateBulk) saveChunk(ctx context.Context, builders []*WarehouseCreate) ([]*entity.Warehouse, error) {
	if len(builders) == 0 {
		return []*entity.Warehouse{}, nil
	}
	specs := make([]*sqlgraph.CreateSpec, len(builders))
	nodes := make([]*entity.Warehouse, len(builders))
	mutators := make([]runtime.Mutator, len(builders))
	for i := range builders {
		func(i int, root context.Context) {
			builder := builders[i]
			allHooks := builder.hooks
			var mut runtime.Mutator = runtime.MutateFunc(func(ctx context.Context, m runtime.Mutation) (runtime.Value, error) {
				mutation, ok := m.(*WarehouseMutation)
				if !ok {
					return nil, fmt.Errorf("velox: unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				nodes[i].SetConfig(_cb.config)
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					if err = sqlgraph.BatchCreate(ctx, _cb.config.Driver, spec); err != nil {
						err = runtime.MayWrapConstraintError(err)
					}
				}
				if err != nil {
					return nil, err
				}
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
					mutation.SetID(int(id))
				}
				return nodes[i], nil
			})
			for j := len(allHooks) - 1; j >= 0; j-- {
				mut = allHooks[j](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_cb *WarehouseCreateBulk) SaveX(ctx context.Context) []*entity.Warehouse {
	v, err := _cb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_cb *WarehouseCreateBulk) Exec(ctx context.Context) error {
	_, err := _cb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_cb *WarehouseCreateBulk) ExecX(ctx context.Context) {
	if err := _cb.Exec(ctx); err != nil {
		panic(err)
	}
}
