// Code generated by velox. DO NOT EDIT.

package warehouseclient

import (
	"context"
	"errors"
	"fmt"

	entity "github.com/syssam/graphql-go/examples/veloxfx/velox/entity"
	predicate "github.com/syssam/graphql-go/examples/veloxfx/velox/predicate"
	warehouse "github.com/syssam/graphql-go/examples/veloxfx/velox/warehouse"
	velox "github.com/syssam/velox"
	sql "github.com/syssam/velox/dialect/sql"
	sqlgraph "github.com/syssam/velox/dialect/sql/sqlgraph"
	runtime "github.com/syssam/velox/runtime"
	field "github.com/syssam/velox/schema/field"
)

// WarehouseUpdate is the update builder for Warehouse entities.
//
// Query interceptors do NOT run on mutations. A row filter registered
// with Intercept() leaves this builder unscoped, so express row-level
// authorization as a schema Policy() — it covers reads and writes.
type WarehouseUpdate struct {
	config    runtime.Config
	mutation  *WarehouseMutation
	hooks     []runtime.Hook
	modifiers []func(*sql.UpdateBuilder)
}

// NewWarehouseUpdate creates a new WarehouseUpdate builder.
func NewWarehouseUpdate(c runtime.Config, mutation *WarehouseMutation, hooks []runtime.Hook) *WarehouseUpdate {
	return &WarehouseUpdate{
		config:   c,
		hooks:    hooks,
		mutation: mutation,
	}
}

// Where appends a list predicates to the WarehouseUpdate builder.
func (_u *WarehouseUpdate) Where(ps ...predicate.Warehouse) *WarehouseUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *WarehouseUpdate) SetName(v string) *WarehouseUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *WarehouseUpdate) SetNillableName(v *string) *WarehouseUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// AddStockIDs adds the "stocks" edge by ids.
func (_u *WarehouseUpdate) AddStockIDs(ids ...int) *WarehouseUpdate {
	_u.mutation.AddStockIDs(ids...)
	return _u
}

// RemoveStockIDs removes the "stocks" edge by ids.
func (_u *WarehouseUpdate) RemoveStockIDs(ids ...int) *WarehouseUpdate {
	_u.mutation.RemoveStockIDs(ids...)
	return _u
}

// ClearStocks clears the "stocks" edge.
func (_u *WarehouseUpdate) ClearStocks() *WarehouseUpdate {
	_u.mutation.ClearStocks()
	return _u
}

// AddStocks adds the "stocks" edge to the given entities.
func (_u *WarehouseUpdate) AddStocks(v ...*entity.Stock) *WarehouseUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	_u.AddStockIDs(ids...)
	return _u
}

// RemoveStocks removes the "stocks" edge to the given entities.
func (_u *WarehouseUpdate) RemoveStocks(v ...*entity.Stock) *WarehouseUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	_u.RemoveStockIDs(ids...)
	return _u
}

// Mutation returns the WarehouseMutation.
func (_u *WarehouseUpdate) Mutation() *WarehouseMutation {
	return _u.mutation
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *WarehouseUpdate) Modify(modifiers ...func(*sql.UpdateBuilder)) *WarehouseUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

// check runs the user-defined validators on the fields this mutation sets
// and guards required unique edges against being cleared.
func (_u *WarehouseUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := warehouse.NameValidator(v); err != nil {
			return &runtime.ValidationError{
				Entity: "Warehouse",
				Err:    fmt.Errorf("validator failed for field \"Warehouse.name\": %w", err),
				Field:  "name",
				Name:   "name",
			}
		}
	}
	return nil
}

// sqlSave executes the SQL update for Warehouse after hooks have run.
func (_u *WarehouseUpdate) sqlSave(ctx context.Context) (int, error) {
	if err := _u.check(); err != nil {
		return 0, err
	}
	spec := sqlgraph.NewUpdateSpec(warehouse.Table, warehouse.Columns, &sqlgraph.FieldSpec{
		Column: warehouse.FieldID,
		Type:   warehouseIDFieldType,
	})
	if _u.mutation._name != nil {
		spec.SetField("name", field.TypeString, *_u.mutation._name)
	}
	ps := _u.mutation.PredicatesFuncs()
	if len(ps) > 0 {
		spec.Predicate = func(s *sql.Selector) {
			for i := range ps {
				ps[i](s)
			}
		}
	}
	if _u.mutation.StocksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"warehouse_stocks"},
			Inverse: false,
			Rel:     sqlgraph.O2M,
			Table:   "stocks",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		spec.Edges.Clear = append(spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStocksIDs(); len(nodes) > 0 && !_u.mutation.StocksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"warehouse_stocks"},
			Inverse: false,
			Rel:     sqlgraph.O2M,
			Table:   "stocks",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		spec.Edges.Clear = append(spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StocksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"warehouse_stocks"},
			Inverse: false,
			Rel:     sqlgraph.O2M,
			Table:   "stocks",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		spec.Edges.Add = append(spec.Edges.Add, edge)
	}
	if len(_u.modifiers) > 0 {
		spec.AddModifiers(_u.modifiers...)
	}
	affected, err := sqlgraph.UpdateNodes(ctx, _u.config.Driver, spec)
	if err != nil {
		return 0, runtime.MayWrapConstraintError(err)
	}
	return affected, nil
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WarehouseUpdate) Save(ctx context.Context) (int, error) {
	hooks := _u.hooks
	return velox.WithHooks[int, WarehouseMutation, *WarehouseMutation](ctx, _u.sqlSave, _u.mutation, hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WarehouseUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WarehouseUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WarehouseUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// WarehouseUpdateOne is the update builder for a single Warehouse entity.
type WarehouseUpdateOne struct {
	config       runtime.Config
	mutation     *WarehouseMutation
	hooks        []runtime.Hook
	modifiers    []func(*sql.UpdateBuilder)
	selectFields []string
}

// NewWarehouseUpdateOne creates a new WarehouseUpdateOne builder.
func NewWarehouseUpdateOne(c runtime.Config, mutation *WarehouseMutation, hooks []runtime.Hook) *WarehouseUpdateOne {
	return &WarehouseUpdateOne{
		config:   c,
		hooks:    hooks,
		mutation: mutation,
	}
}

// Where appends a list predicates to the WarehouseUpdateOne builder.
func (_u *WarehouseUpdateOne) Where(ps ...predicate.Warehouse) *WarehouseUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema. It narrows
// only what is read back — every field set on this builder is still written.
func (_u *WarehouseUpdateOne) Select(field string, fields ...string) *WarehouseUpdateOne {
	_u.selectFields = append([]string{field}, fields...)
	return _u
}

// SetName sets the "name" field.
func (_u *WarehouseUpdateOne) SetName(v string) *WarehouseUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *WarehouseUpdateOne) SetNillableName(v *string) *WarehouseUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// AddStockIDs adds the "stocks" edge by ids.
func (_u *WarehouseUpdateOne) AddStockIDs(ids ...int) *WarehouseUpdateOne {
	_u.mutation.AddStockIDs(ids...)
	return _u
}

// RemoveStockIDs removes the "stocks" edge by ids.
func (_u *WarehouseUpdateOne) RemoveStockIDs(ids ...int) *WarehouseUpdateOne {
	_u.mutation.RemoveStockIDs(ids...)
	return _u
}

// ClearStocks clears the "stocks" edge.
func (_u *WarehouseUpdateOne) ClearStocks() *WarehouseUpdateOne {
	_u.mutation.ClearStocks()
	return _u
}

// AddStocks adds the "stocks" edge to the given entities.
func (_u *WarehouseUpdateOne) AddStocks(v ...*entity.Stock) *WarehouseUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	_u.AddStockIDs(ids...)
	return _u
}

// RemoveStocks removes the "stocks" edge to the given entities.
func (_u *WarehouseUpdateOne) RemoveStocks(v ...*entity.Stock) *WarehouseUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	_u.RemoveStockIDs(ids...)
	return _u
}

// Mutation returns the WarehouseMutation.
func (_u *WarehouseUpdateOne) Mutation() *WarehouseMutation {
	return _u.mutation
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *WarehouseUpdateOne) Modify(modifiers ...func(*sql.UpdateBuilder)) *WarehouseUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

// check runs the user-defined validators on the fields this mutation sets
// and guards required unique edges against being cleared.
func (_u *WarehouseUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := warehouse.NameValidator(v); err != nil {
			return &runtime.ValidationError{
				Entity: "Warehouse",
				Err:    fmt.Errorf("validator failed for field \"Warehouse.name\": %w", err),
				Field:  "name",
				Name:   "name",
			}
		}
	}
	return nil
}

// sqlSave executes the SQL update for a single Warehouse after hooks have run.
func (_u *WarehouseUpdateOne) sqlSave(ctx context.Context) (*entity.Warehouse, error) {
	if err := _u.check(); err != nil {
		return nil, err
	}
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, errors.New("velox: missing ID for UpdateOne")
	}
	spec := sqlgraph.NewUpdateSpec(warehouse.Table, warehouse.Columns, &sqlgraph.FieldSpec{
		Column: warehouse.FieldID,
		Type:   warehouseIDFieldType,
	})
	if _u.mutation._name != nil {
		spec.SetField("name", field.TypeString, *_u.mutation._name)
	}
	spec.Node.ID.Value = id
	ps := _u.mutation.PredicatesFuncs()
	spec.Predicate = func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(warehouse.FieldID), id))
		for i := range ps {
			ps[i](s)
		}
	}
	if _u.mutation.StocksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"warehouse_stocks"},
			Inverse: false,
			Rel:     sqlgraph.O2M,
			Table:   "stocks",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		spec.Edges.Clear = append(spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStocksIDs(); len(nodes) > 0 && !_u.mutation.StocksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"warehouse_stocks"},
			Inverse: false,
			Rel:     sqlgraph.O2M,
			Table:   "stocks",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		spec.Edges.Clear = append(spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StocksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"warehouse_stocks"},
			Inverse: false,
			Rel:     sqlgraph.O2M,
			Table:   "stocks",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		spec.Edges.Add = append(spec.Edges.Add, edge)
	}
	if len(_u.modifiers) > 0 {
		spec.AddModifiers(_u.modifiers...)
	}
	if err := sqlgraph.UpdateNode(ctx, _u.config.Driver, spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			return nil, velox.NewNotFoundError("Warehouse")
		}
		return nil, runtime.MayWrapConstraintError(err)
	}
	columns := warehouse.Columns
	if len(_u.selectFields) > 0 {
		columns = make([]string, 0, len(_u.selectFields)+1)
		columns = append(columns, warehouse.FieldID)
		for _, f := range _u.selectFields {
			if !warehouse.ValidColumn(f) {
				return nil, &runtime.ValidationError{
					Entity: "Warehouse",
					Err:    errors.New("invalid field for query"),
					Field:  f,
					Name:   f,
				}
			}
			if f != warehouse.FieldID {
				columns = append(columns, f)
			}
		}
	}
	build := func(_ context.Context) (*sql.Selector, error) {
		s := sql.Select(columns...).From(sql.Table(warehouse.Table))
		s.SetDialect(_u.config.Driver.Dialect())
		s.Where(sql.EQ(s.C(warehouse.FieldID), id))
		s.Limit(1)
		return s, nil
	}
	_node, err2 := runtime.ScanFirst[entity.Warehouse, *entity.Warehouse](ctx, _u.config.Driver, build, "Warehouse")
	if err2 != nil {
		return nil, err2
	}
	_node.SetConfig(_u.config)
	return _node, nil
}

// Save executes the query and returns the updated Warehouse entity.
func (_u *WarehouseUpdateOne) Save(ctx context.Context) (*entity.Warehouse, error) {
	_u.mutation.oldValue = func(ctx context.Context) (*entity.Warehouse, error) {
		id, ok := _u.mutation.ID()
		if !ok {
			return nil, errors.New("velox: missing ID for OldField")
		}
		build := func(_ context.Context) (*sql.Selector, error) {
			s := sql.Select(warehouse.Columns...).From(sql.Table(warehouse.Table))
			s.SetDialect(_u.config.Driver.Dialect())
			s.Where(sql.EQ(s.C(warehouse.FieldID), id))
			s.Limit(1)
			return s, nil
		}
		_old, err := runtime.ScanFirst[entity.Warehouse, *entity.Warehouse](ctx, _u.config.Driver, build, "Warehouse")
		if err != nil {
			return nil, err
		}
		_old.SetConfig(_u.config)
		return _old, nil
	}
	hooks := _u.hooks
	return velox.WithHooks[*entity.Warehouse, WarehouseMutation, *WarehouseMutation](ctx, _u.sqlSave, _u.mutation, hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WarehouseUpdateOne) SaveX(ctx context.Context) *entity.Warehouse {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WarehouseUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WarehouseUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}
