// Code generated by gqlc. DO NOT EDIT.

// Package order holds the generated GraphQL bindings for the order group.
package order

import (
	"context"
	"time"

	"github.com/syssam/graphql-go"
	ordermodel "github.com/syssam/graphql-go/examples/veloxfx/graph/model/order"
	entity "github.com/syssam/graphql-go/examples/veloxfx/velox/entity"
	filter "github.com/syssam/graphql-go/examples/veloxfx/velox/filter"
	order "github.com/syssam/graphql-go/examples/veloxfx/velox/order"
	gqlrelay "github.com/syssam/velox/contrib/graphql/gqlrelay"
)

type PlaceOrderArgs struct {
	Input ordermodel.PlaceOrderInput `graphql:"input"`
}

type PayOrderArgs struct {
	ID int `graphql:"id"`
}

type ShipOrderArgs struct {
	ID int `graphql:"id"`
}

type CancelOrderArgs struct {
	ID int `graphql:"id"`
}

type DeleteOrderArgs struct {
	ID int `graphql:"id"`
}

type OrdersArgs struct {
	After   *gqlrelay.Cursor        `graphql:"after"`
	First   *int                    `graphql:"first"`
	Before  *gqlrelay.Cursor        `graphql:"before"`
	Last    *int                    `graphql:"last"`
	OrderBy *entity.OrderOrder      `graphql:"orderBy"`
	Where   *filter.OrderWhereInput `graphql:"where"`
}

type OrderArgs struct {
	ID int `graphql:"id"`
}

// Resolver holds methods for fields that are not struct data.
type Resolver interface {
	PlaceOrder(ctx context.Context, args PlaceOrderArgs) (*entity.Order, error)
	PayOrder(ctx context.Context, args PayOrderArgs) (*entity.Order, error)
	ShipOrder(ctx context.Context, args ShipOrderArgs) (*entity.Order, error)
	CancelOrder(ctx context.Context, args CancelOrderArgs) (*entity.Order, error)
	DeleteOrder(ctx context.Context, args DeleteOrderArgs) (int, error)
	OrderTotalCents(ctx context.Context, obj *entity.Order) (int, error)
	Orders(ctx context.Context, args OrdersArgs) (*entity.OrderConnection, error)
	Order(ctx context.Context, args OrderArgs) (*entity.Order, error)
}

func Bindings(r Resolver) graphql.SchemaOption {
	return graphql.Options(
		graphql.EnumMarshaler[entity.OrderOrderField]("OrderOrderField"),
		graphql.EnumMarshaler[order.Status]("OrderStatus"),
		graphql.Input[entity.OrderOrder]("OrderOrder", graphql.ZeroForNull()),
		graphql.Input[filter.OrderWhereInput]("OrderWhereInput", graphql.ZeroForNull()),
		graphql.Input[ordermodel.PlaceOrderInput]("PlaceOrderInput", graphql.ZeroForNull()),
		graphql.Input[ordermodel.PlaceOrderItemInput]("PlaceOrderItemInput", graphql.ZeroForNull()),
		graphql.Object[entity.Order]("Order",
			graphql.Field("id", func(v *entity.Order) int { return v.ID }),
			graphql.Field("createdAt", func(v *entity.Order) time.Time { return v.CreatedAt }),
			graphql.Field("updatedAt", func(v *entity.Order) time.Time { return v.UpdatedAt }),
			graphql.Field("status", func(v *entity.Order) order.Status { return v.Status }),
			graphql.Resolve("customer", func(ctx context.Context, v *entity.Order) (*entity.Customer, error) { return v.Customer(ctx) }),
			graphql.Resolve("warehouse", func(ctx context.Context, v *entity.Order) (*entity.Warehouse, error) { return v.Warehouse(ctx) }),
			graphql.Resolve("items", func(ctx context.Context, v *entity.Order) ([]*entity.OrderItem, error) { return v.Items(ctx) }),
			graphql.Resolve("totalCents", func(ctx context.Context, v *entity.Order) (int, error) { return r.OrderTotalCents(ctx, v) }),
		),
		graphql.Object[entity.OrderConnection]("OrderConnection",
			graphql.Field("edges", func(v *entity.OrderConnection) []*entity.OrderEdge { return v.Edges }),
			graphql.Field("pageInfo", func(v *entity.OrderConnection) gqlrelay.PageInfo { return v.PageInfo }),
			graphql.Field("totalCount", func(v *entity.OrderConnection) int { return v.TotalCount }),
		),
		graphql.Object[entity.OrderEdge]("OrderEdge",
			graphql.Field("node", func(v *entity.OrderEdge) *entity.Order { return v.Node }),
			graphql.Field("cursor", func(v *entity.OrderEdge) gqlrelay.Cursor { return v.Cursor }),
		),
		graphql.Query(
			graphql.ResolveArgs("orders", func(ctx context.Context, _ graphql.Root, a OrdersArgs) (*entity.OrderConnection, error) {
				return r.Orders(ctx, a)
			}),
			graphql.ResolveArgs("order", func(ctx context.Context, _ graphql.Root, a OrderArgs) (*entity.Order, error) { return r.Order(ctx, a) }),
		),
		graphql.Mutation(
			graphql.ResolveArgs("placeOrder", func(ctx context.Context, _ graphql.Root, a PlaceOrderArgs) (*entity.Order, error) {
				return r.PlaceOrder(ctx, a)
			}),
			graphql.ResolveArgs("payOrder", func(ctx context.Context, _ graphql.Root, a PayOrderArgs) (*entity.Order, error) {
				return r.PayOrder(ctx, a)
			}),
			graphql.ResolveArgs("shipOrder", func(ctx context.Context, _ graphql.Root, a ShipOrderArgs) (*entity.Order, error) {
				return r.ShipOrder(ctx, a)
			}),
			graphql.ResolveArgs("cancelOrder", func(ctx context.Context, _ graphql.Root, a CancelOrderArgs) (*entity.Order, error) {
				return r.CancelOrder(ctx, a)
			}),
			graphql.ResolveArgs("deleteOrder", func(ctx context.Context, _ graphql.Root, a DeleteOrderArgs) (int, error) {
				return r.DeleteOrder(ctx, a)
			}),
		),
		graphql.Args[PlaceOrderArgs](),
		graphql.Args[PayOrderArgs](),
		graphql.Args[ShipOrderArgs](),
		graphql.Args[CancelOrderArgs](),
		graphql.Args[DeleteOrderArgs](),
		graphql.Args[OrdersArgs](),
		graphql.Args[OrderArgs](),
	)
}
