// Code generated by velox. DO NOT EDIT.

package query

import (
	"context"
	"fmt"

	category "github.com/syssam/graphql-go/examples/veloxfx/velox/category"
	entity "github.com/syssam/graphql-go/examples/veloxfx/velox/entity"
	predicate "github.com/syssam/graphql-go/examples/veloxfx/velox/predicate"
	product "github.com/syssam/graphql-go/examples/veloxfx/velox/product"
	velox "github.com/syssam/velox"
	dialect "github.com/syssam/velox/dialect"
	sql "github.com/syssam/velox/dialect/sql"
	sqlgraph "github.com/syssam/velox/dialect/sql/sqlgraph"
	runtime "github.com/syssam/velox/runtime"
	field "github.com/syssam/velox/schema/field"
)

// CategoryQuery is the query builder for Category entities.
// It implements entity.CategoryQuerier.
type CategoryQuery struct {
	config            runtime.Config
	ctx               *runtime.QueryContext
	predicates        []func(*sql.Selector)
	order             []func(*sql.Selector)
	modifiers         []func(*sql.Selector)
	inters            *entity.InterceptorStore
	withProducts      *ProductQuery
	withNamedProducts map[string]*ProductQuery
	path              func(context.Context) (*sql.Selector, error)
}

// NewCategoryQuery creates a new CategoryQuery.
func NewCategoryQuery(cfg runtime.Config) *CategoryQuery {
	return &CategoryQuery{
		config: cfg,
		ctx:    &runtime.QueryContext{Type: "Category"},
	}
}

// SetPath sets the graph traversal path for this query.
func (q *CategoryQuery) SetPath(p func(context.Context) (*sql.Selector, error)) {
	q.path = p
}

// SetInterStore wires the shared client-level interceptor store onto this query.
// Called by the entity client constructor and by query derivation code paths.
// Not for direct use — call via the SetInterStore inline interface assertion.
func (q *CategoryQuery) SetInterStore(s *entity.InterceptorStore) {
	q.inters = s
}

// GetIDColumn returns the primary key column name for Category.
func (q *CategoryQuery) GetIDColumn() string {
	return category.FieldID
}

// GetCtx returns the query context for field projection.
func (q *CategoryQuery) GetCtx() *runtime.QueryContext {
	return q.ctx
}

// WithEdgeLoad enables eager loading of the named edge, applies opts to
// the edge query and returns it (nil for an unknown edge). runtime.Limit
// caps the rows of each parent, not the total. Used by the GraphQL field
// collector for generic edge loading.
func (q *CategoryQuery) WithEdgeLoad(name string, opts ...runtime.LoadOption) runtime.FieldCollectable {
	switch name {
	case "products":
		if q.withProducts == nil {
			q.withProducts = NewProductQuery(q.config)
			q.withProducts.inters = q.inters
		}
		q.withProducts.applyLoad(runtime.NewLoadConfig(opts...), true)
		return q.withProducts
	}
	return nil
}

// applyLoad applies an edge's load configuration to this query when a
// parent eager-loads it through WithEdgeLoad. A limit is kept only on a
// to-many edge, where the parent's loader applies it per parent.
func (q *CategoryQuery) applyLoad(cfg *runtime.LoadConfig, toMany bool) {
	for _, f := range cfg.Fields {
		q.ctx.AppendFieldOnce(f)
	}
	q.predicates = append(q.predicates, cfg.Predicates...)
	q.order = append(q.order, cfg.Orders...)
	if toMany && cfg.Limit != nil {
		n := *cfg.Limit
		q.ctx.PartitionLimit = &n
	}
	for name, opts := range cfg.Edges {
		q.WithEdgeLoad(name, opts...)
	}
}

// querySpec builds a *sqlgraph.QuerySpec from the query's direct fields.
func (q *CategoryQuery) querySpec() *sqlgraph.QuerySpec {
	return runtime.MakeQuerySpec(q, field.TypeInt)
}

// buildQuery constructs a *sql.Selector from the query state.
// Used by QueryXxx methods to create a sub-select for graph traversal.
func (q *CategoryQuery) buildQuery(ctx context.Context) (*sql.Selector, error) {
	return runtime.BuildQueryFrom(ctx, q)
}

// buildSelector constructs a fully-configured *sql.Selector ready for execution.
// Adds column selection, FK columns, and DISTINCT on top of buildQuery.
func (q *CategoryQuery) buildSelector(ctx context.Context) (*sql.Selector, error) {
	return runtime.BuildSelectorFrom(ctx, q)
}

// Where adds predicates to the CategoryQuery.
func (q *CategoryQuery) Where(ps ...predicate.Category) entity.CategoryQuerier {
	for _, p := range ps {
		q.predicates = append(q.predicates, p)
	}
	return q
}

// Limit the number of records to be returned by this query.
func (q *CategoryQuery) Limit(n int) entity.CategoryQuerier {
	q.ctx.Limit = &n
	return q
}

// Offset to start from.
func (q *CategoryQuery) Offset(n int) entity.CategoryQuerier {
	q.ctx.Offset = &n
	return q
}

// Unique configures the query builder to filter duplicate records.
func (q *CategoryQuery) Unique(unique bool) entity.CategoryQuerier {
	q.ctx.Unique = &unique
	return q
}

// Order specifies how the records should be ordered.
func (q *CategoryQuery) Order(o ...func(*sql.Selector)) entity.CategoryQuerier {
	q.order = append(q.order, o...)
	return q
}

// WithProducts tells the query-builder to eager-load the "products" edge.
func (q *CategoryQuery) WithProducts(opts ...func(entity.ProductQuerier)) entity.CategoryQuerier {
	tq := NewProductQuery(q.config)
	tq.inters = q.inters
	for _, opt := range opts {
		opt(tq)
	}
	q.withProducts = tq
	return q
}

// WithNamedProducts tells the query-builder to eager-load the "products" edge with the given name.
// The optional arguments are used to configure the query builder of the edge.
func (q *CategoryQuery) WithNamedProducts(name string, opts ...func(*ProductQuery)) *CategoryQuery {
	query := NewProductQuery(q.config)
	query.inters = q.inters
	for _, opt := range opts {
		opt(query)
	}
	if q.withNamedProducts == nil {
		q.withNamedProducts = make(map[string]*ProductQuery)
	}
	q.withNamedProducts[name] = query
	return q
}

// QueryProducts chains the current query on the "products" edge.
func (q *CategoryQuery) QueryProducts() entity.ProductQuerier {
	tq := NewProductQuery(q.config)
	tq.inters = q.inters
	tq.path = func(ctx context.Context) (*sql.Selector, error) {
		from, err := q.buildQuery(ctx)
		if err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(sqlgraph.From(category.Table, category.FieldID), sqlgraph.To(product.Table, product.FieldID), sqlgraph.Edge(sqlgraph.O2M, false, category.ProductsTable, category.ProductsColumn))
		step.From.V = from
		return sqlgraph.SetNeighbors(q.config.Driver.Dialect(), step), nil
	}
	return tq
}

// Clone returns a duplicate of the CategoryQuery builder.
func (q *CategoryQuery) Clone() entity.CategoryQuerier {
	return q.clone()
}

// sqlAll executes the SQL query and returns scanned Category entities.
func (q *CategoryQuery) sqlAll(ctx context.Context) ([]*entity.Category, error) {
	nodes, err := runtime.ScanAll[entity.Category, *entity.Category](ctx, q.config.Driver, q.buildSelector)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if err := q.eagerLoad(ctx, nodes); err != nil {
		return nil, err
	}
	return nodes, nil
}

// eagerLoad loads the edges this query was asked to eager-load into nodes
// and injects the runtime config. sqlAll calls it after scanning; the
// many-to-many loaders of other queries call it on the rows they scan.
func (q *CategoryQuery) eagerLoad(ctx context.Context, nodes []*entity.Category) error {
	if query := q.withProducts; query != nil {
		if err := q.loadProducts(ctx, query, nodes, func(n *entity.Category) {
			n.Edges.Products = []*entity.Product{}
			n.Edges.MarkProductsLoaded()
		}, func(n *entity.Category, e *entity.Product) {
			n.Edges.Products = append(n.Edges.Products, e)
		}); err != nil {
			return err
		}
	}
	for name, query := range q.withNamedProducts {
		if err := q.loadProducts(ctx, query, nodes, func(n *entity.Category) {
			n.AppendNamedProducts(name)
		}, func(n *entity.Category, e *entity.Product) {
			n.AppendNamedProducts(name, e)
		}); err != nil {
			return err
		}
	}
	for _, node := range nodes {
		node.SetConfig(q.config)
	}
	return nil
}

// prepareQuery evaluates the privacy policy (if any) and runs
// Traversers from the interceptor list. Privacy is invoked
// explicitly here — it is NOT part of the interceptor chain.
func (q *CategoryQuery) prepareQuery(ctx context.Context) error {
	return runtime.RunTraversers(ctx, q, q.inters.Category)
}

// All executes the query and returns a list of Category.
func (q *CategoryQuery) All(ctx context.Context) ([]*entity.Category, error) {
	ctx = setContextOp(ctx, q.ctx, velox.OpQueryAll)
	if err := q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	if len(q.inters.Category) > 0 {
		return velox.WithInterceptors[[]*entity.Category](ctx, q, querierAll[[]*entity.Category, *CategoryQuery](), q.inters.Category)
	}
	return q.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (q *CategoryQuery) AllX(ctx context.Context) []*entity.Category {
	nodes, err := q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// First returns the first Category entity from the query.
func (q *CategoryQuery) First(ctx context.Context) (*entity.Category, error) {
	clone := q.clone()
	clone.ctx.Limit = intP(1)
	nodes, err := clone.All(setContextOp(ctx, q.ctx, velox.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, runtime.NewNotFoundError("Category")
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (q *CategoryQuery) FirstX(ctx context.Context) *entity.Category {
	node, err := q.First(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Only returns a single Category entity found by the query, ensuring it only returns one.
func (q *CategoryQuery) Only(ctx context.Context) (*entity.Category, error) {
	clone := q.clone()
	clone.ctx.Limit = intP(2)
	nodes, err := clone.All(setContextOp(ctx, q.ctx, velox.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 0:
		return nil, runtime.NewNotFoundError("Category")
	case 1:
		return nodes[0], nil
	default:
		return nil, runtime.NewNotSingularError("Category")
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (q *CategoryQuery) OnlyX(ctx context.Context) *entity.Category {
	node, err := q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// sqlCount executes the SQL COUNT query and returns the result.
func (q *CategoryQuery) sqlCount(ctx context.Context) (int, error) {
	var from *sql.Selector
	if q.path != nil {
		var err error
		from, err = q.path(ctx)
		if err != nil {
			return 0, err
		}
	}
	spec := q.querySpec()
	spec.Node.Columns = nil
	spec.From = from
	return sqlgraph.CountNodes(ctx, q.config.Driver, spec)
}

// Count returns the count of the given query.
func (q *CategoryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, q.ctx, velox.OpQueryCount)
	if err := q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	if len(q.inters.Category) > 0 {
		return velox.WithInterceptors[int](ctx, q, querierCount[*CategoryQuery](), q.inters.Category)
	}
	return q.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (q *CategoryQuery) CountX(ctx context.Context) int {
	count, err := q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has results.
func (q *CategoryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, q.ctx, velox.OpQueryExist)
	_, err := q.FirstID(ctx)
	if err == nil {
		return true, nil
	}
	if runtime.IsNotFound(err) {
		return false, nil
	}
	return false, fmt.Errorf("velox: check existence: %w", err)
}

// ExistX is like Exist, but panics if an error occurs.
func (q *CategoryQuery) ExistX(ctx context.Context) bool {
	exist, err := q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// SQL returns the SQL query string and arguments for debugging.
// It runs prepareQuery (privacy traversers) and builds the selector,
// but does not execute the query.
func (q *CategoryQuery) SQL(ctx context.Context) (string, []any, error) {
	if err := q.prepareQuery(ctx); err != nil {
		return "", nil, err
	}
	selector, err := q.buildSelector(ctx)
	if err != nil {
		return "", nil, err
	}
	query, args := selector.Query()
	return query, args, nil
}

// Explain returns the query's execution plan without executing it.
// Includes the SQL, arguments, planned edge loads, and active interceptors.
func (q *CategoryQuery) Explain(ctx context.Context) (*runtime.QueryPlan, error) {
	if err := q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	selector, err := q.buildSelector(ctx)
	if err != nil {
		return nil, err
	}
	query, args := selector.Query()
	plan := &runtime.QueryPlan{
		Args: args,
		SQL:  query,
	}
	for _, inter := range q.inters.Category {
		plan.Interceptors = append(plan.Interceptors, fmt.Sprintf("%T", inter))
	}
	if q.withProducts != nil {
		eSel, eErr := q.withProducts.buildSelector(ctx)
		if eErr == nil {
			eq, ea := eSel.Query()
			plan.Edges = append(plan.Edges, runtime.EdgePlan{
				Args: ea,
				Name: "products",
				SQL:  eq,
			})
		}
	}
	return plan, nil
}

// IDs executes the query and returns a list of Category IDs.
func (q *CategoryQuery) IDs(ctx context.Context) ([]int, error) {
	ctx = setContextOp(ctx, q.ctx, velox.OpQueryIDs)
	if err := q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	if len(q.inters.Category) > 0 {
		return velox.WithInterceptors[[]int](ctx, q, querierIDs[[]int, *CategoryQuery](), q.inters.Category)
	}
	return q.sqlIDs(ctx)
}

// sqlIDs executes the ID-only SQL SELECT for Category.
func (q *CategoryQuery) sqlIDs(ctx context.Context) ([]int, error) {
	var from *sql.Selector
	if q.path != nil {
		var err error
		from, err = q.path(ctx)
		if err != nil {
			return nil, err
		}
		if q.ctx.Unique == nil {
			q.Unique(true)
		}
	}
	spec := q.querySpec()
	spec.Node.Columns = []string{category.FieldID}
	spec.From = from
	var ids []int
	spec.ScanValues = func(_ []string) ([]any, error) {
		return runtime.IDScanValues(field.TypeInt), nil
	}
	spec.Assign = func(_ []string, values []any) error {
		if len(values) == 0 {
			return fmt.Errorf("velox: IDs: no values returned")
		}
		id, err := runtime.ExtractID(values[0], field.TypeInt)
		if err != nil {
			return err
		}
		ids = append(ids, id.(int))
		return nil
	}
	if err := sqlgraph.QueryNodes(ctx, q.config.Driver, spec); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (q *CategoryQuery) IDsX(ctx context.Context) []int {
	ids, err := q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// FirstID returns the first Category ID from the query.
func (q *CategoryQuery) FirstID(ctx context.Context) (int, error) {
	var zero int
	clone := q.clone()
	clone.ctx.Limit = intP(1)
	ids, err := clone.IDs(setContextOp(ctx, q.ctx, velox.OpQueryFirstID))
	if err != nil {
		return zero, err
	}
	if len(ids) == 0 {
		return zero, runtime.NewNotFoundError("Category")
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (q *CategoryQuery) FirstIDX(ctx context.Context) int {
	id, err := q.FirstID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OnlyID returns the only Category ID in the query.
func (q *CategoryQuery) OnlyID(ctx context.Context) (int, error) {
	var zero int
	clone := q.clone()
	clone.ctx.Limit = intP(2)
	ids, err := clone.IDs(setContextOp(ctx, q.ctx, velox.OpQueryOnlyID))
	if err != nil {
		return zero, err
	}
	switch len(ids) {
	case 0:
		return zero, runtime.NewNotFoundError("Category")
	case 1:
		return ids[0], nil
	default:
		return zero, runtime.NewNotSingularError("Category")
	}
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (q *CategoryQuery) OnlyIDX(ctx context.Context) int {
	id, err := q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (q *CategoryQuery) ForUpdate(opts ...sql.LockOption) entity.CategoryQuerier {
	if caps := dialect.GetCapabilities(q.config.Driver.Dialect()); caps.Has(dialect.CapForUpdate) && !caps.Has(dialect.CapLockWithDistinct) {
		q.Unique(false)
	}
	q.modifiers = append(q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (q *CategoryQuery) ForShare(opts ...sql.LockOption) entity.CategoryQuerier {
	if caps := dialect.GetCapabilities(q.config.Driver.Dialect()); caps.Has(dialect.CapForShare) && !caps.Has(dialect.CapLockWithDistinct) {
		q.Unique(false)
	}
	q.modifiers = append(q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return q
}

// GetDriver returns the dialect driver. Implements runtime.QueryReader.
func (q *CategoryQuery) GetDriver() dialect.Driver {
	return q.config.Driver
}

// GetTable returns the primary table name. Implements runtime.QueryReader.
func (q *CategoryQuery) GetTable() string {
	return category.Table
}

// GetColumns returns the default column list. Implements runtime.QueryReader.
func (q *CategoryQuery) GetColumns() []string {
	return category.Columns
}

// GetFKColumns returns the foreign-key columns. Implements runtime.QueryReader.
func (q *CategoryQuery) GetFKColumns() []string {
	return category.ForeignKeys
}

// GetIDFieldType returns the schema type of the ID field. Implements runtime.QueryReader.
func (q *CategoryQuery) GetIDFieldType() field.Type {
	return field.TypeInt
}

// GetPath returns the graph-traversal path function. Implements runtime.QueryReader.
func (q *CategoryQuery) GetPath() func(context.Context) (*sql.Selector, error) {
	return q.path
}

// GetPredicates returns the registered WHERE predicates. Implements runtime.QueryReader.
func (q *CategoryQuery) GetPredicates() []func(*sql.Selector) {
	return q.predicates
}

// GetOrder returns the registered ORDER BY functions. Implements runtime.QueryReader.
func (q *CategoryQuery) GetOrder() []func(*sql.Selector) {
	return q.order
}

// GetModifiers returns the registered query modifiers. Implements runtime.QueryReader.
func (q *CategoryQuery) GetModifiers() []func(*sql.Selector) {
	return q.modifiers
}

// GetWithFKs returns whether FK columns should be included. Implements runtime.QueryReader.
func (q *CategoryQuery) GetWithFKs() bool {
	return false
}

// Select allows the selection of one or more fields/columns for the given query,
// returning a CategorySelect builder with scalar accessor methods (Strings, Ints, etc.).
func (q *CategoryQuery) Select(fields ...string) entity.CategorySelector {
	q.ctx.Fields = append(q.ctx.Fields, fields...)
	s := &CategorySelect{CategoryQuery: q}
	s.Selector = runtime.NewSelector("CategorySelect", &q.ctx.Fields, s.Scan)
	return s
}

// Modify adds a query modifier for attaching custom logic to queries.
func (q *CategoryQuery) Modify(modifiers ...func(*sql.Selector)) entity.CategoryQuerier {
	q.modifiers = append(q.modifiers, modifiers...)
	return q
}

// Aggregate returns a CategorySelect configured with the given aggregations.
func (q *CategoryQuery) Aggregate(fns ...runtime.AggregateFunc) entity.CategorySelector {
	return q.Select().Aggregate(fns...)
}

// GroupBy is used to group vertices by one or more fields/columns.
func (q *CategoryQuery) GroupBy(field string, fields ...string) entity.CategoryGroupByer {
	g := &CategoryGroupBy{
		build:  q,
		fields: append([]string{field}, fields...),
	}
	g.Selector = runtime.NewSelector("CategoryGroupBy", &g.fields, g.Scan)
	return g
}

// Scan applies the selector query and scans the result into the given value.
func (q *CategoryQuery) Scan(ctx context.Context, v any) error {
	if err := q.prepareQuery(ctx); err != nil {
		return err
	}
	return runtime.QueryScan(ctx, q, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (q *CategoryQuery) ScanX(ctx context.Context, v any) {
	if err := q.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// CategorySelect is the builder for selecting fields of Category entities.
type CategorySelect struct {
	CategoryQuery *CategoryQuery
	runtime.Selector
}

// All forwards to the underlying CategoryQuery.
func (s *CategorySelect) All(ctx context.Context) ([]*entity.Category, error) {
	return s.CategoryQuery.All(ctx)
}

// AllX forwards to the underlying CategoryQuery.
func (s *CategorySelect) AllX(ctx context.Context) []*entity.Category {
	return s.CategoryQuery.AllX(ctx)
}

// First forwards to the underlying CategoryQuery.
func (s *CategorySelect) First(ctx context.Context) (*entity.Category, error) {
	return s.CategoryQuery.First(ctx)
}

// FirstX forwards to the underlying CategoryQuery.
func (s *CategorySelect) FirstX(ctx context.Context) *entity.Category {
	return s.CategoryQuery.FirstX(ctx)
}

// Only forwards to the underlying CategoryQuery.
func (s *CategorySelect) Only(ctx context.Context) (*entity.Category, error) {
	return s.CategoryQuery.Only(ctx)
}

// OnlyX forwards to the underlying CategoryQuery.
func (s *CategorySelect) OnlyX(ctx context.Context) *entity.Category {
	return s.CategoryQuery.OnlyX(ctx)
}

// Count forwards to the underlying CategoryQuery.
func (s *CategorySelect) Count(ctx context.Context) (int, error) {
	return s.CategoryQuery.Count(ctx)
}

// CountX forwards to the underlying CategoryQuery.
func (s *CategorySelect) CountX(ctx context.Context) int {
	return s.CategoryQuery.CountX(ctx)
}

// Exist forwards to the underlying CategoryQuery.
func (s *CategorySelect) Exist(ctx context.Context) (bool, error) {
	return s.CategoryQuery.Exist(ctx)
}

// ExistX forwards to the underlying CategoryQuery.
func (s *CategorySelect) ExistX(ctx context.Context) bool {
	return s.CategoryQuery.ExistX(ctx)
}

// IDs forwards to the underlying CategoryQuery.
func (s *CategorySelect) IDs(ctx context.Context) ([]int, error) {
	return s.CategoryQuery.IDs(ctx)
}

// FirstID forwards to the underlying CategoryQuery.
func (s *CategorySelect) FirstID(ctx context.Context) (int, error) {
	return s.CategoryQuery.FirstID(ctx)
}

// OnlyID forwards to the underlying CategoryQuery.
func (s *CategorySelect) OnlyID(ctx context.Context) (int, error) {
	return s.CategoryQuery.OnlyID(ctx)
}

// Aggregate adds the given aggregation functions to the selector query.
func (s *CategorySelect) Aggregate(fns ...runtime.AggregateFunc) entity.CategorySelector {
	s.AppendFns(fns...)
	return s
}
func (s *CategorySelect) sqlScan(ctx context.Context, v any) error {
	return runtime.QuerySelect(ctx, s.CategoryQuery, s.Fns(), v)
}

// Scan applies the selector query and scans the result into the given value.
func (s *CategorySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, s.CategoryQuery.ctx, velox.OpQuerySelect)
	if err := s.CategoryQuery.prepareQuery(ctx); err != nil {
		return err
	}
	return runtime.ScanWithInterceptors(ctx, s.CategoryQuery, s.CategoryQuery.inters.Category, s.sqlScan, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (s *CategorySelect) ScanX(ctx context.Context, v any) {
	if err := s.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// CategoryGroupBy is the group-by builder for Category entities.
type CategoryGroupBy struct {
	runtime.Selector
	build  *CategoryQuery
	fields []string
}

// Aggregate adds the given aggregation functions to the group-by query.
func (g *CategoryGroupBy) Aggregate(fns ...runtime.AggregateFunc) entity.CategoryGroupByer {
	g.AppendFns(fns...)
	return g
}

// Scan applies the group-by query and scans the result into the given value.
func (g *CategoryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, g.build.ctx, velox.OpQueryGroupBy)
	if g.build == nil {
		return g.sqlScan(ctx, v)
	}
	if err := g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return runtime.ScanWithInterceptors(ctx, g.build, g.build.inters.Category, g.sqlScan, v)
}
func (g *CategoryGroupBy) sqlScan(ctx context.Context, v any) error {
	return runtime.QueryGroupBy(ctx, g.build, g.fields, g.Fns(), v)
}

// clone returns a concrete clone of the CategoryQuery for internal use by First/Only.
func (q *CategoryQuery) clone() *CategoryQuery {
	if q == nil {
		return nil
	}
	c := &CategoryQuery{
		config:       q.config,
		ctx:          q.ctx.Clone(),
		inters:       q.inters,
		modifiers:    runtime.CloneSlice(q.modifiers),
		order:        runtime.CloneSlice(q.order),
		path:         q.path,
		predicates:   runtime.CloneSlice(q.predicates),
		withProducts: q.withProducts.clone(),
	}
	if q.withNamedProducts != nil {
		c.withNamedProducts = make(map[string]*ProductQuery, len(q.withNamedProducts))
		for name, q := range q.withNamedProducts {
			c.withNamedProducts[name] = q.clone()
		}
	}
	return c
}

// loadProducts eagerly loads the "products" edge for the given nodes.
func (q *CategoryQuery) loadProducts(ctx context.Context, query *ProductQuery, nodes []*entity.Category, init func(*entity.Category), assign func(*entity.Category, *entity.Product)) error {
	query = query.clone()
	fks := make([]any, 0, len(nodes))
	nodeids := make(map[int]*entity.Category, len(nodes))
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(func(s *sql.Selector) {
		s.Where(sql.In(s.C(category.ProductsColumn), fks...))
	})
	limit, err := runtime.PlanPerParentLimit[int](ctx, query.ctx, query.config.Driver, "products")
	if err != nil {
		return err
	}
	if limit.Active {
		query.modifiers = append(query.modifiers, func(s *sql.Selector) {
			limit.Apply(s, s.C(category.ProductsColumn), s.C(product.FieldID))
		})
	}
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.FKValue("category_products")
		if fk == nil {
			return fmt.Errorf("velox: foreign-key %q is nil for node %v", "category_products", n.ID)
		}
		parentID := derefFK(fk).(int)
		node, ok := nodeids[parentID]
		if !ok {
			return fmt.Errorf("velox: unexpected foreign-key %q returned %v for node %v", "category_products", parentID, n.ID)
		}
		if !limit.Keep(parentID) {
			continue
		}
		assign(node, n)
	}
	return nil
}

// Verify CategoryQuery implements entity.CategoryQuerier at compile time.
var _ entity.CategoryQuerier = (*CategoryQuery)(nil)
