// Code generated by velox. DO NOT EDIT.

package query

import (
	"context"

	entity "github.com/syssam/graphql-go/examples/veloxfx/velox/entity"
	"github.com/syssam/graphql-go/examples/veloxfx/velox/todo"
	"github.com/syssam/graphql-go/examples/veloxfx/velox/user"
	"github.com/syssam/velox/contrib/graphql/gqlrelay"
	"github.com/syssam/velox/runtime"
)

// CollectFields tells the query-builder to project the columns and
// eager-load the edges the GraphQL selection of the resolver in ctx
// reads. Call it in resolvers that return entities; Paginate collects
// on its own. It is part of the entity's Querier interface, so it is
// reachable from Query() without a type assertion.
func (q *TodoQuery) CollectFields(ctx context.Context, satisfies ...string) (entity.TodoQuerier, error) {
	return q, gqlrelay.CollectFields(ctx, q, &todo.TodoCollectMeta, satisfies...)
}

// CollectMeta returns the GraphQL field collection metadata of Todo.
func (q *TodoQuery) CollectMeta() *runtime.CollectMeta {
	return &todo.TodoCollectMeta
}

// CollectFields tells the query-builder to project the columns and
// eager-load the edges the GraphQL selection of the resolver in ctx
// reads. Call it in resolvers that return entities; Paginate collects
// on its own. It is part of the entity's Querier interface, so it is
// reachable from Query() without a type assertion.
func (q *UserQuery) CollectFields(ctx context.Context, satisfies ...string) (entity.UserQuerier, error) {
	return q, gqlrelay.CollectFields(ctx, q, &user.UserCollectMeta, satisfies...)
}

// CollectMeta returns the GraphQL field collection metadata of User.
func (q *UserQuery) CollectMeta() *runtime.CollectMeta {
	return &user.UserCollectMeta
}
