// Code generated by velox. DO NOT EDIT.

package query

import (
	"context"
	"reflect"

	velox "github.com/syssam/velox"
	runtime "github.com/syssam/velox/runtime"
)

func init() {
	runtime.RegisterQueryFactory("Todo", func(cfg runtime.Config) any {
		return NewTodoQuery(cfg)
	})
	runtime.RegisterQueryFactory("User", func(cfg runtime.Config) any {
		return NewUserQuery(cfg)
	})
}

// intP returns a pointer to the given int value.
func intP(v int) *int {
	return &v
}

// idsToAny converts a typed int ID slice to []any for sql.InValues.
func idsToAny(ids []int) []any {
	out := make([]any, len(ids))
	for i, v := range ids {
		out[i] = v
	}
	return out
}

// fkToID extracts an int from an FK any value (supports *int and int).
func fkToID(v any) int {
	switch val := v.(type) {
	case int:
		return val
	case *int:
		if val != nil {
			return *val
		}
	case int64:
		return int(val)
	case *int64:
		if val != nil {
			return int(*val)
		}
	}
	return 0
}

// derefFK dereferences a pointer FK value to its underlying comparable value.
func derefFK(v any) any {
	rv := reflect.ValueOf(v)
	if rv.Kind() == reflect.Ptr && !rv.IsNil() {
		return rv.Elem().Interface()
	}
	return v
}

// querierAll returns a Querier that calls sqlAll on the concrete query type.
func querierAll[V any, Q interface {
	sqlAll(context.Context) (V, error)
}]() velox.Querier {
	return velox.QuerierFunc(func(ctx context.Context, q velox.Query) (velox.Value, error) {
		return q.(Q).sqlAll(ctx)
	})
}

// querierCount returns a Querier that calls sqlCount on the concrete query type.
func querierCount[Q interface {
	sqlCount(context.Context) (int, error)
}]() velox.Querier {
	return velox.QuerierFunc(func(ctx context.Context, q velox.Query) (velox.Value, error) {
		return q.(Q).sqlCount(ctx)
	})
}

// querierIDs returns a Querier that calls sqlIDs on the concrete query type.
func querierIDs[IDs any, Q interface {
	sqlIDs(context.Context) (IDs, error)
}]() velox.Querier {
	return velox.QuerierFunc(func(ctx context.Context, q velox.Query) (velox.Value, error) {
		return q.(Q).sqlIDs(ctx)
	})
}

// setContextOp returns a new context with the given QueryContext attached (including its op) in case it does not exist.
func setContextOp(ctx context.Context, qc *runtime.QueryContext, op string) context.Context {
	if velox.QueryFromContext(ctx) == nil {
		ctx = velox.NewQueryContext(ctx, &velox.QueryContext{
			Fields: qc.Fields,
			Limit:  qc.Limit,
			Offset: qc.Offset,
			Op:     op,
			Type:   qc.Type,
			Unique: qc.Unique,
		})
	}
	return ctx
}
