// Code generated by velox. DO NOT EDIT.

package query

import (
	"context"
	"fmt"

	category "github.com/syssam/graphql-go/examples/veloxfx/velox/category"
	entity "github.com/syssam/graphql-go/examples/veloxfx/velox/entity"
	orderitem "github.com/syssam/graphql-go/examples/veloxfx/velox/orderitem"
	predicate "github.com/syssam/graphql-go/examples/veloxfx/velox/predicate"
	product "github.com/syssam/graphql-go/examples/veloxfx/velox/product"
	stock "github.com/syssam/graphql-go/examples/veloxfx/velox/stock"
	velox "github.com/syssam/velox"
	dialect "github.com/syssam/velox/dialect"
	sql "github.com/syssam/velox/dialect/sql"
	sqlgraph "github.com/syssam/velox/dialect/sql/sqlgraph"
	runtime "github.com/syssam/velox/runtime"
	field "github.com/syssam/velox/schema/field"
)

// ProductQuery is the query builder for Product entities.
// It implements entity.ProductQuerier.
type ProductQuery struct {
	config              runtime.Config
	ctx                 *runtime.QueryContext
	predicates          []func(*sql.Selector)
	order               []func(*sql.Selector)
	modifiers           []func(*sql.Selector)
	inters              *entity.InterceptorStore
	withFKs             bool
	withCategory        *CategoryQuery
	withStocks          *StockQuery
	withOrderItems      *OrderItemQuery
	withNamedStocks     map[string]*StockQuery
	withNamedOrderItems map[string]*OrderItemQuery
	path                func(context.Context) (*sql.Selector, error)
}

// NewProductQuery creates a new ProductQuery.
func NewProductQuery(cfg runtime.Config) *ProductQuery {
	return &ProductQuery{
		config: cfg,
		ctx:    &runtime.QueryContext{Type: "Product"},
	}
}

// SetPath sets the graph traversal path for this query.
func (q *ProductQuery) SetPath(p func(context.Context) (*sql.Selector, error)) {
	q.path = p
}

// SetInterStore wires the shared client-level interceptor store onto this query.
// Called by the entity client constructor and by query derivation code paths.
// Not for direct use — call via the SetInterStore inline interface assertion.
func (q *ProductQuery) SetInterStore(s *entity.InterceptorStore) {
	q.inters = s
}

// GetIDColumn returns the primary key column name for Product.
func (q *ProductQuery) GetIDColumn() string {
	return product.FieldID
}

// GetCtx returns the query context for field projection.
func (q *ProductQuery) GetCtx() *runtime.QueryContext {
	return q.ctx
}

// WithEdgeLoad enables eager loading of the named edge, applies opts to
// the edge query and returns it (nil for an unknown edge). runtime.Limit
// caps the rows of each parent, not the total. Used by the GraphQL field
// collector for generic edge loading.
func (q *ProductQuery) WithEdgeLoad(name string, opts ...runtime.LoadOption) runtime.FieldCollectable {
	switch name {
	case "category":
		if q.withCategory == nil {
			q.withCategory = NewCategoryQuery(q.config)
			q.withCategory.inters = q.inters
			q.withCategory.ctx.EdgeLoadCreated = true
		}
		q.withFKs = true
		q.withCategory.applyLoad(runtime.NewLoadConfig(opts...), false)
		return q.withCategory
	case "stocks":
		if q.withStocks == nil {
			q.withStocks = NewStockQuery(q.config)
			q.withStocks.inters = q.inters
			q.withStocks.ctx.EdgeLoadCreated = true
		}
		q.withStocks.applyLoad(runtime.NewLoadConfig(opts...), true)
		return q.withStocks
	case "order_items":
		if q.withOrderItems == nil {
			q.withOrderItems = NewOrderItemQuery(q.config)
			q.withOrderItems.inters = q.inters
			q.withOrderItems.ctx.EdgeLoadCreated = true
		}
		q.withOrderItems.applyLoad(runtime.NewLoadConfig(opts...), true)
		return q.withOrderItems
	}
	return nil
}

// applyLoad applies an edge's load configuration to this query when a
// parent eager-loads it through WithEdgeLoad. A limit is kept only on a
// to-many edge, where the parent's loader applies it per parent.
func (q *ProductQuery) applyLoad(cfg *runtime.LoadConfig, toMany bool) {
	for _, f := range cfg.Fields {
		q.ctx.AppendFieldOnce(f)
	}
	q.predicates = append(q.predicates, cfg.Predicates...)
	q.order = append(q.order, cfg.Orders...)
	if toMany && cfg.Limit != nil {
		n := *cfg.Limit
		q.ctx.PartitionLimit = &n
	}
	for name, opts := range cfg.Edges {
		q.WithEdgeLoad(name, opts...)
	}
}

// querySpec builds a *sqlgraph.QuerySpec from the query's direct fields.
func (q *ProductQuery) querySpec() *sqlgraph.QuerySpec {
	return runtime.MakeQuerySpec(q, field.TypeInt)
}

// buildQuery constructs a *sql.Selector from the query state.
// Used by QueryXxx methods to create a sub-select for graph traversal.
func (q *ProductQuery) buildQuery(ctx context.Context) (*sql.Selector, error) {
	return runtime.BuildQueryFrom(ctx, q)
}

// buildSelector constructs a fully-configured *sql.Selector ready for execution.
// Adds column selection, FK columns, and DISTINCT on top of buildQuery.
func (q *ProductQuery) buildSelector(ctx context.Context) (*sql.Selector, error) {
	return runtime.BuildSelectorFrom(ctx, q)
}

// Where adds predicates to the ProductQuery.
func (q *ProductQuery) Where(ps ...predicate.Product) entity.ProductQuerier {
	for _, p := range ps {
		q.predicates = append(q.predicates, p)
	}
	return q
}

// Limit the number of records to be returned by this query.
func (q *ProductQuery) Limit(n int) entity.ProductQuerier {
	q.ctx.Limit = &n
	return q
}

// Offset to start from.
func (q *ProductQuery) Offset(n int) entity.ProductQuerier {
	q.ctx.Offset = &n
	return q
}

// Unique configures the query builder to filter duplicate records.
func (q *ProductQuery) Unique(unique bool) entity.ProductQuerier {
	q.ctx.Unique = &unique
	return q
}

// Order specifies how the records should be ordered.
func (q *ProductQuery) Order(o ...func(*sql.Selector)) entity.ProductQuerier {
	q.order = append(q.order, o...)
	return q
}

// WithCategory tells the query-builder to eager-load the "category" edge.
func (q *ProductQuery) WithCategory(opts ...func(entity.CategoryQuerier)) entity.ProductQuerier {
	tq := NewCategoryQuery(q.config)
	tq.inters = q.inters
	for _, opt := range opts {
		opt(tq)
	}
	q.withCategory = tq
	q.withFKs = true
	return q
}

// WithStocks tells the query-builder to eager-load the "stocks" edge.
func (q *ProductQuery) WithStocks(opts ...func(entity.StockQuerier)) entity.ProductQuerier {
	tq := NewStockQuery(q.config)
	tq.inters = q.inters
	for _, opt := range opts {
		opt(tq)
	}
	q.withStocks = tq
	return q
}

// WithOrderItems tells the query-builder to eager-load the "order_items" edge.
func (q *ProductQuery) WithOrderItems(opts ...func(entity.OrderItemQuerier)) entity.ProductQuerier {
	tq := NewOrderItemQuery(q.config)
	tq.inters = q.inters
	for _, opt := range opts {
		opt(tq)
	}
	q.withOrderItems = tq
	return q
}

// WithNamedStocks tells the query-builder to eager-load the "stocks" edge with the given name.
// The optional arguments are used to configure the query builder of the edge.
func (q *ProductQuery) WithNamedStocks(name string, opts ...func(*StockQuery)) *ProductQuery {
	query := NewStockQuery(q.config)
	query.inters = q.inters
	for _, opt := range opts {
		opt(query)
	}
	if q.withNamedStocks == nil {
		q.withNamedStocks = make(map[string]*StockQuery)
	}
	q.withNamedStocks[name] = query
	return q
}

// WithNamedOrderItems tells the query-builder to eager-load the "order_items" edge with the given name.
// The optional arguments are used to configure the query builder of the edge.
func (q *ProductQuery) WithNamedOrderItems(name string, opts ...func(*OrderItemQuery)) *ProductQuery {
	query := NewOrderItemQuery(q.config)
	query.inters = q.inters
	for _, opt := range opts {
		opt(query)
	}
	if q.withNamedOrderItems == nil {
		q.withNamedOrderItems = make(map[string]*OrderItemQuery)
	}
	q.withNamedOrderItems[name] = query
	return q
}

// QueryCategory chains the current query on the "category" edge.
func (q *ProductQuery) QueryCategory() entity.CategoryQuerier {
	tq := NewCategoryQuery(q.config)
	tq.inters = q.inters
	tq.path = func(ctx context.Context) (*sql.Selector, error) {
		if err := q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		from, err := q.buildQuery(ctx)
		if err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(sqlgraph.From(product.Table, product.FieldID), sqlgraph.To(category.Table, category.FieldID), sqlgraph.Edge(sqlgraph.M2O, true, product.CategoryTable, product.CategoryColumn))
		step.From.V = from
		return sqlgraph.SetNeighbors(q.config.Driver.Dialect(), step), nil
	}
	return tq
}

// QueryStocks chains the current query on the "stocks" edge.
func (q *ProductQuery) QueryStocks() entity.StockQuerier {
	tq := NewStockQuery(q.config)
	tq.inters = q.inters
	tq.path = func(ctx context.Context) (*sql.Selector, error) {
		if err := q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		from, err := q.buildQuery(ctx)
		if err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(sqlgraph.From(product.Table, product.FieldID), sqlgraph.To(stock.Table, stock.FieldID), sqlgraph.Edge(sqlgraph.O2M, false, product.StocksTable, product.StocksColumn))
		step.From.V = from
		return sqlgraph.SetNeighbors(q.config.Driver.Dialect(), step), nil
	}
	return tq
}

// QueryOrderItems chains the current query on the "order_items" edge.
func (q *ProductQuery) QueryOrderItems() entity.OrderItemQuerier {
	tq := NewOrderItemQuery(q.config)
	tq.inters = q.inters
	tq.path = func(ctx context.Context) (*sql.Selector, error) {
		if err := q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		from, err := q.buildQuery(ctx)
		if err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(sqlgraph.From(product.Table, product.FieldID), sqlgraph.To(orderitem.Table, orderitem.FieldID), sqlgraph.Edge(sqlgraph.O2M, false, product.OrderItemsTable, product.OrderItemsColumn))
		step.From.V = from
		return sqlgraph.SetNeighbors(q.config.Driver.Dialect(), step), nil
	}
	return tq
}

// Clone returns a duplicate of the ProductQuery builder.
func (q *ProductQuery) Clone() entity.ProductQuerier {
	return q.clone()
}

// sqlAll executes the SQL query and returns scanned Product entities.
func (q *ProductQuery) sqlAll(ctx context.Context) ([]*entity.Product, error) {
	nodes, err := runtime.ScanAll[entity.Product, *entity.Product](ctx, q.config.Driver, q.buildSelector)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if err := q.eagerLoad(ctx, nodes); err != nil {
		return nil, err
	}
	return nodes, nil
}

// eagerLoad loads the edges this query was asked to eager-load into nodes
// and injects the runtime config. sqlAll calls it after scanning; the
// many-to-many loaders of other queries call it on the rows they scan.
func (q *ProductQuery) eagerLoad(ctx context.Context, nodes []*entity.Product) error {
	if query := q.withCategory; query != nil {
		if err := q.loadCategory(ctx, query, nodes, func(n *entity.Product) {
			n.Edges.MarkCategoryLoaded()
		}, func(n *entity.Product, e *entity.Category) {
			n.Edges.Category = e
		}); err != nil {
			return err
		}
	}
	if query := q.withStocks; query != nil {
		if err := q.loadStocks(ctx, query, nodes, func(n *entity.Product) {
			n.Edges.Stocks = []*entity.Stock{}
			n.Edges.MarkStocksLoaded()
		}, func(n *entity.Product, e *entity.Stock) {
			n.Edges.Stocks = append(n.Edges.Stocks, e)
		}); err != nil {
			return err
		}
	}
	if query := q.withOrderItems; query != nil {
		if err := q.loadOrderItems(ctx, query, nodes, func(n *entity.Product) {
			n.Edges.OrderItems = []*entity.OrderItem{}
			n.Edges.MarkOrderItemsLoaded()
		}, func(n *entity.Product, e *entity.OrderItem) {
			n.Edges.OrderItems = append(n.Edges.OrderItems, e)
		}); err != nil {
			return err
		}
	}
	for name, query := range q.withNamedStocks {
		if err := q.loadStocks(ctx, query, nodes, func(n *entity.Product) {
			n.AppendNamedStocks(name)
		}, func(n *entity.Product, e *entity.Stock) {
			n.AppendNamedStocks(name, e)
		}); err != nil {
			return err
		}
	}
	for name, query := range q.withNamedOrderItems {
		if err := q.loadOrderItems(ctx, query, nodes, func(n *entity.Product) {
			n.AppendNamedOrderItems(name)
		}, func(n *entity.Product, e *entity.OrderItem) {
			n.AppendNamedOrderItems(name, e)
		}); err != nil {
			return err
		}
	}
	for _, node := range nodes {
		node.SetConfig(q.config)
	}
	return nil
}

// prepareQuery evaluates the privacy policy (if any) and runs
// Traversers from the interceptor list. Privacy is invoked
// explicitly here — it is NOT part of the interceptor chain.
func (q *ProductQuery) prepareQuery(ctx context.Context) error {
	for _, f := range q.ctx.Fields {
		if !product.ValidColumn(f) {
			return &runtime.ValidationError{
				Entity: "Product",
				Err:    fmt.Errorf("invalid field %q for query", f),
				Field:  f,
				Name:   f,
			}
		}
	}
	return runtime.RunTraversers(ctx, q, q.inters.Product)
}

// All executes the query and returns a list of Product.
func (q *ProductQuery) All(ctx context.Context) ([]*entity.Product, error) {
	ctx = setContextOp(ctx, q.ctx, velox.OpQueryAll)
	if err := q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	if len(q.inters.Product) > 0 {
		return velox.WithInterceptors[[]*entity.Product](ctx, q, querierAll[[]*entity.Product, *ProductQuery](), q.inters.Product)
	}
	return q.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (q *ProductQuery) AllX(ctx context.Context) []*entity.Product {
	nodes, err := q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// First returns the first Product entity from the query.
func (q *ProductQuery) First(ctx context.Context) (*entity.Product, error) {
	clone := q.clone()
	clone.ctx.Limit = intP(1)
	nodes, err := clone.All(setContextOp(ctx, q.ctx, velox.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, runtime.NewNotFoundError("Product")
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (q *ProductQuery) FirstX(ctx context.Context) *entity.Product {
	node, err := q.First(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Only returns a single Product entity found by the query, ensuring it only returns one.
func (q *ProductQuery) Only(ctx context.Context) (*entity.Product, error) {
	clone := q.clone()
	clone.ctx.Limit = intP(2)
	nodes, err := clone.All(setContextOp(ctx, q.ctx, velox.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 0:
		return nil, runtime.NewNotFoundError("Product")
	case 1:
		return nodes[0], nil
	default:
		return nil, runtime.NewNotSingularError("Product")
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (q *ProductQuery) OnlyX(ctx context.Context) *entity.Product {
	node, err := q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// sqlCount executes the SQL COUNT query and returns the result.
func (q *ProductQuery) sqlCount(ctx context.Context) (int, error) {
	var from *sql.Selector
	if q.path != nil {
		var err error
		from, err = q.path(ctx)
		if err != nil {
			return 0, err
		}
	}
	spec := q.querySpec()
	spec.Node.Columns = q.ctx.Fields
	spec.From = from
	return sqlgraph.CountNodes(ctx, q.config.Driver, spec)
}

// Count returns the count of the given query.
func (q *ProductQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, q.ctx, velox.OpQueryCount)
	if err := q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	if len(q.inters.Product) > 0 {
		return velox.WithInterceptors[int](ctx, q, querierCount[*ProductQuery](), q.inters.Product)
	}
	return q.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (q *ProductQuery) CountX(ctx context.Context) int {
	count, err := q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has results.
func (q *ProductQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, q.ctx, velox.OpQueryExist)
	_, err := q.FirstID(ctx)
	if err == nil {
		return true, nil
	}
	if runtime.IsNotFound(err) {
		return false, nil
	}
	return false, fmt.Errorf("velox: check existence: %w", err)
}

// ExistX is like Exist, but panics if an error occurs.
func (q *ProductQuery) ExistX(ctx context.Context) bool {
	exist, err := q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// SQL returns the SQL query string and arguments for debugging.
// It runs prepareQuery (privacy traversers) and builds the selector,
// but does not execute the query.
func (q *ProductQuery) SQL(ctx context.Context) (string, []any, error) {
	if err := q.prepareQuery(ctx); err != nil {
		return "", nil, err
	}
	selector, err := q.buildSelector(ctx)
	if err != nil {
		return "", nil, err
	}
	query, args := selector.Query()
	return query, args, nil
}

// Explain returns the query's execution plan without executing it.
// Includes the SQL, arguments, planned edge loads, and active interceptors.
func (q *ProductQuery) Explain(ctx context.Context) (*runtime.QueryPlan, error) {
	if err := q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	selector, err := q.buildSelector(ctx)
	if err != nil {
		return nil, err
	}
	query, args := selector.Query()
	plan := &runtime.QueryPlan{
		Args: args,
		SQL:  query,
	}
	for _, inter := range q.inters.Product {
		plan.Interceptors = append(plan.Interceptors, fmt.Sprintf("%T", inter))
	}
	if q.withCategory != nil {
		eSel, eErr := q.withCategory.buildSelector(ctx)
		if eErr == nil {
			eq, ea := eSel.Query()
			plan.Edges = append(plan.Edges, runtime.EdgePlan{
				Args: ea,
				Name: "category",
				SQL:  eq,
			})
		}
	}
	if q.withStocks != nil {
		eSel, eErr := q.withStocks.buildSelector(ctx)
		if eErr == nil {
			eq, ea := eSel.Query()
			plan.Edges = append(plan.Edges, runtime.EdgePlan{
				Args: ea,
				Name: "stocks",
				SQL:  eq,
			})
		}
	}
	if q.withOrderItems != nil {
		eSel, eErr := q.withOrderItems.buildSelector(ctx)
		if eErr == nil {
			eq, ea := eSel.Query()
			plan.Edges = append(plan.Edges, runtime.EdgePlan{
				Args: ea,
				Name: "order_items",
				SQL:  eq,
			})
		}
	}
	return plan, nil
}

// IDs executes the query and returns a list of Product IDs.
func (q *ProductQuery) IDs(ctx context.Context) ([]int, error) {
	ctx = setContextOp(ctx, q.ctx, velox.OpQueryIDs)
	if err := q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	if len(q.inters.Product) > 0 {
		return velox.WithInterceptors[[]int](ctx, q, querierIDs[[]int, *ProductQuery](), q.inters.Product)
	}
	return q.sqlIDs(ctx)
}

// sqlIDs executes the ID-only SQL SELECT for Product.
func (q *ProductQuery) sqlIDs(ctx context.Context) ([]int, error) {
	var from *sql.Selector
	if q.path != nil {
		var err error
		from, err = q.path(ctx)
		if err != nil {
			return nil, err
		}
	}
	spec := q.querySpec()
	spec.Node.Columns = []string{product.FieldID}
	spec.From = from
	var ids []int
	spec.ScanValues = func(_ []string) ([]any, error) {
		return runtime.IDScanValues(field.TypeInt), nil
	}
	spec.Assign = func(_ []string, values []any) error {
		if len(values) == 0 {
			return fmt.Errorf("velox: IDs: no values returned")
		}
		id, err := runtime.ExtractID(values[0], field.TypeInt)
		if err != nil {
			return err
		}
		ids = append(ids, id.(int))
		return nil
	}
	if err := sqlgraph.QueryNodes(ctx, q.config.Driver, spec); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (q *ProductQuery) IDsX(ctx context.Context) []int {
	ids, err := q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// FirstID returns the first Product ID from the query.
func (q *ProductQuery) FirstID(ctx context.Context) (int, error) {
	var zero int
	clone := q.clone()
	clone.ctx.Limit = intP(1)
	ids, err := clone.IDs(setContextOp(ctx, q.ctx, velox.OpQueryFirstID))
	if err != nil {
		return zero, err
	}
	if len(ids) == 0 {
		return zero, runtime.NewNotFoundError("Product")
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (q *ProductQuery) FirstIDX(ctx context.Context) int {
	id, err := q.FirstID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OnlyID returns the only Product ID in the query.
func (q *ProductQuery) OnlyID(ctx context.Context) (int, error) {
	var zero int
	clone := q.clone()
	clone.ctx.Limit = intP(2)
	ids, err := clone.IDs(setContextOp(ctx, q.ctx, velox.OpQueryOnlyID))
	if err != nil {
		return zero, err
	}
	switch len(ids) {
	case 0:
		return zero, runtime.NewNotFoundError("Product")
	case 1:
		return ids[0], nil
	default:
		return zero, runtime.NewNotSingularError("Product")
	}
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (q *ProductQuery) OnlyIDX(ctx context.Context) int {
	id, err := q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (q *ProductQuery) ForUpdate(opts ...sql.LockOption) entity.ProductQuerier {
	if caps := dialect.GetCapabilities(q.config.Driver.Dialect()); caps.Has(dialect.CapForUpdate) && !caps.Has(dialect.CapLockWithDistinct) {
		q.Unique(false)
	}
	q.modifiers = append(q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (q *ProductQuery) ForShare(opts ...sql.LockOption) entity.ProductQuerier {
	if caps := dialect.GetCapabilities(q.config.Driver.Dialect()); caps.Has(dialect.CapForShare) && !caps.Has(dialect.CapLockWithDistinct) {
		q.Unique(false)
	}
	q.modifiers = append(q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return q
}

// GetDriver returns the dialect driver. Implements runtime.QueryReader.
func (q *ProductQuery) GetDriver() dialect.Driver {
	return q.config.Driver
}

// GetTable returns the primary table name. Implements runtime.QueryReader.
func (q *ProductQuery) GetTable() string {
	return product.Table
}

// GetColumns returns the default column list. Implements runtime.QueryReader.
func (q *ProductQuery) GetColumns() []string {
	return product.Columns
}

// GetFKColumns returns the foreign-key columns. Implements runtime.QueryReader.
func (q *ProductQuery) GetFKColumns() []string {
	return product.ForeignKeys
}

// GetIDFieldType returns the schema type of the ID field. Implements runtime.QueryReader.
func (q *ProductQuery) GetIDFieldType() field.Type {
	return field.TypeInt
}

// GetPath returns the graph-traversal path function. Implements runtime.QueryReader.
func (q *ProductQuery) GetPath() func(context.Context) (*sql.Selector, error) {
	return q.path
}

// GetPredicates returns the registered WHERE predicates. Implements runtime.QueryReader.
func (q *ProductQuery) GetPredicates() []func(*sql.Selector) {
	return q.predicates
}

// GetOrder returns the registered ORDER BY functions. Implements runtime.QueryReader.
func (q *ProductQuery) GetOrder() []func(*sql.Selector) {
	return q.order
}

// GetModifiers returns the registered query modifiers. Implements runtime.QueryReader.
func (q *ProductQuery) GetModifiers() []func(*sql.Selector) {
	return q.modifiers
}

// GetWithFKs returns whether FK columns should be included. Implements runtime.QueryReader.
func (q *ProductQuery) GetWithFKs() bool {
	return q.withFKs
}

// Select allows the selection of one or more fields/columns for the given query,
// returning a ProductSelect builder with scalar accessor methods (Strings, Ints, etc.).
func (q *ProductQuery) Select(fields ...string) entity.ProductSelector {
	q.ctx.Fields = append(q.ctx.Fields, fields...)
	s := &ProductSelect{ProductQuery: q}
	s.Selector = runtime.NewSelector("ProductSelect", &q.ctx.Fields, s.Scan)
	return s
}

// Modify adds a query modifier for attaching custom logic to queries.
func (q *ProductQuery) Modify(modifiers ...func(*sql.Selector)) entity.ProductQuerier {
	q.modifiers = append(q.modifiers, modifiers...)
	return q
}

// Aggregate returns a ProductSelect configured with the given aggregations.
func (q *ProductQuery) Aggregate(fns ...runtime.AggregateFunc) entity.ProductSelector {
	return q.Select().Aggregate(fns...)
}

// GroupBy is used to group vertices by one or more fields/columns.
func (q *ProductQuery) GroupBy(field string, fields ...string) entity.ProductGroupByer {
	g := &ProductGroupBy{
		build:  q,
		fields: append([]string{field}, fields...),
	}
	g.Selector = runtime.NewSelector("ProductGroupBy", &g.fields, g.Scan)
	return g
}

// Scan applies the selector query and scans the result into the given value.
func (q *ProductQuery) Scan(ctx context.Context, v any) error {
	if err := q.prepareQuery(ctx); err != nil {
		return err
	}
	return runtime.QueryScan(ctx, q, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (q *ProductQuery) ScanX(ctx context.Context, v any) {
	if err := q.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// ProductSelect is the builder for selecting fields of Product entities.
type ProductSelect struct {
	ProductQuery *ProductQuery
	runtime.Selector
}

// All forwards to the underlying ProductQuery.
func (s *ProductSelect) All(ctx context.Context) ([]*entity.Product, error) {
	return s.ProductQuery.All(ctx)
}

// AllX forwards to the underlying ProductQuery.
func (s *ProductSelect) AllX(ctx context.Context) []*entity.Product {
	return s.ProductQuery.AllX(ctx)
}

// First forwards to the underlying ProductQuery.
func (s *ProductSelect) First(ctx context.Context) (*entity.Product, error) {
	return s.ProductQuery.First(ctx)
}

// FirstX forwards to the underlying ProductQuery.
func (s *ProductSelect) FirstX(ctx context.Context) *entity.Product {
	return s.ProductQuery.FirstX(ctx)
}

// Only forwards to the underlying ProductQuery.
func (s *ProductSelect) Only(ctx context.Context) (*entity.Product, error) {
	return s.ProductQuery.Only(ctx)
}

// OnlyX forwards to the underlying ProductQuery.
func (s *ProductSelect) OnlyX(ctx context.Context) *entity.Product {
	return s.ProductQuery.OnlyX(ctx)
}

// Count forwards to the underlying ProductQuery.
func (s *ProductSelect) Count(ctx context.Context) (int, error) {
	return s.ProductQuery.Count(ctx)
}

// CountX forwards to the underlying ProductQuery.
func (s *ProductSelect) CountX(ctx context.Context) int {
	return s.ProductQuery.CountX(ctx)
}

// Exist forwards to the underlying ProductQuery.
func (s *ProductSelect) Exist(ctx context.Context) (bool, error) {
	return s.ProductQuery.Exist(ctx)
}

// ExistX forwards to the underlying ProductQuery.
func (s *ProductSelect) ExistX(ctx context.Context) bool {
	return s.ProductQuery.ExistX(ctx)
}

// IDs forwards to the underlying ProductQuery.
func (s *ProductSelect) IDs(ctx context.Context) ([]int, error) {
	return s.ProductQuery.IDs(ctx)
}

// FirstID forwards to the underlying ProductQuery.
func (s *ProductSelect) FirstID(ctx context.Context) (int, error) {
	return s.ProductQuery.FirstID(ctx)
}

// OnlyID forwards to the underlying ProductQuery.
func (s *ProductSelect) OnlyID(ctx context.Context) (int, error) {
	return s.ProductQuery.OnlyID(ctx)
}

// Aggregate adds the given aggregation functions to the selector query.
func (s *ProductSelect) Aggregate(fns ...runtime.AggregateFunc) entity.ProductSelector {
	s.AppendFns(fns...)
	return s
}
func (s *ProductSelect) sqlScan(ctx context.Context, v any) error {
	return runtime.QuerySelect(ctx, s.ProductQuery, s.Fns(), v)
}

// Scan applies the selector query and scans the result into the given value.
func (s *ProductSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, s.ProductQuery.ctx, velox.OpQuerySelect)
	if err := s.ProductQuery.prepareQuery(ctx); err != nil {
		return err
	}
	return runtime.ScanWithInterceptors(ctx, s.ProductQuery, s.ProductQuery.inters.Product, s.sqlScan, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (s *ProductSelect) ScanX(ctx context.Context, v any) {
	if err := s.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// ProductGroupBy is the group-by builder for Product entities.
type ProductGroupBy struct {
	runtime.Selector
	build  *ProductQuery
	fields []string
}

// Aggregate adds the given aggregation functions to the group-by query.
func (g *ProductGroupBy) Aggregate(fns ...runtime.AggregateFunc) entity.ProductGroupByer {
	g.AppendFns(fns...)
	return g
}

// Scan applies the group-by query and scans the result into the given value.
func (g *ProductGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, g.build.ctx, velox.OpQueryGroupBy)
	for _, f := range g.fields {
		if !product.ValidColumn(f) {
			return &runtime.ValidationError{
				Entity: "Product",
				Err:    fmt.Errorf("invalid field %q for query", f),
				Field:  f,
				Name:   f,
			}
		}
	}
	if g.build == nil {
		return g.sqlScan(ctx, v)
	}
	if err := g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return runtime.ScanWithInterceptors(ctx, g.build, g.build.inters.Product, g.sqlScan, v)
}
func (g *ProductGroupBy) sqlScan(ctx context.Context, v any) error {
	return runtime.QueryGroupBy(ctx, g.build, g.fields, g.Fns(), v)
}

// clone returns a concrete clone of the ProductQuery for internal use by First/Only.
func (q *ProductQuery) clone() *ProductQuery {
	if q == nil {
		return nil
	}
	c := &ProductQuery{
		config:         q.config,
		ctx:            q.ctx.Clone(),
		inters:         q.inters,
		modifiers:      runtime.CloneSlice(q.modifiers),
		order:          runtime.CloneSlice(q.order),
		path:           q.path,
		predicates:     runtime.CloneSlice(q.predicates),
		withCategory:   q.withCategory.clone(),
		withFKs:        q.withFKs,
		withOrderItems: q.withOrderItems.clone(),
		withStocks:     q.withStocks.clone(),
	}
	if q.withNamedStocks != nil {
		c.withNamedStocks = make(map[string]*StockQuery, len(q.withNamedStocks))
		for name, q := range q.withNamedStocks {
			c.withNamedStocks[name] = q.clone()
		}
	}
	if q.withNamedOrderItems != nil {
		c.withNamedOrderItems = make(map[string]*OrderItemQuery, len(q.withNamedOrderItems))
		for name, q := range q.withNamedOrderItems {
			c.withNamedOrderItems[name] = q.clone()
		}
	}
	return c
}

// loadCategory eagerly loads the "category" edge for the given nodes.
func (q *ProductQuery) loadCategory(ctx context.Context, query *CategoryQuery, nodes []*entity.Product, init func(*entity.Product), assign func(*entity.Product, *entity.Category)) error {
	query = query.clone()
	fkSeen := make(map[int]struct{}, len(nodes))
	var fks []any
	for _, n := range nodes {
		if init != nil {
			init(n)
		}
		fkRaw := n.FKValue("category_products")
		if fkRaw == nil {
			continue
		}
		fkVal := derefFK(fkRaw).(int)
		if _, ok := fkSeen[fkVal]; !ok {
			fkSeen[fkVal] = struct{}{}
			fks = append(fks, any(fkVal))
		}
	}
	if len(fks) == 0 {
		return nil
	}
	query.Where(func(s *sql.Selector) {
		s.Where(sql.In(s.C(category.FieldID), fks...))
	})
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	neighborByID := make(map[int]*entity.Category, len(neighbors))
	for _, n := range neighbors {
		neighborByID[n.ID] = n
	}
	for _, n := range nodes {
		fkRaw := n.FKValue("category_products")
		if fkRaw == nil {
			continue
		}
		fkVal := derefFK(fkRaw).(int)
		if neighbor, ok := neighborByID[fkVal]; ok {
			assign(n, neighbor)
		}
	}
	return nil
}

// loadStocks eagerly loads the "stocks" edge for the given nodes.
func (q *ProductQuery) loadStocks(ctx context.Context, query *StockQuery, nodes []*entity.Product, init func(*entity.Product), assign func(*entity.Product, *entity.Stock)) error {
	query = query.clone()
	fks := make([]any, 0, len(nodes))
	nodeids := make(map[int]*entity.Product, len(nodes))
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(func(s *sql.Selector) {
		s.Where(sql.In(s.C(product.StocksColumn), fks...))
	})
	limit, err := runtime.PlanPerParentLimit[int](ctx, query.ctx, query.config.Driver, "stocks")
	if err != nil {
		return err
	}
	if limit.Active {
		query.modifiers = append(query.modifiers, func(s *sql.Selector) {
			limit.Apply(s, s.C(product.StocksColumn), s.C(stock.FieldID))
		})
	}
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.FKValue("product_stocks")
		if fk == nil {
			return fmt.Errorf("velox: foreign-key %q is nil for node %v", "product_stocks", n.ID)
		}
		parentID := derefFK(fk).(int)
		node, ok := nodeids[parentID]
		if !ok {
			return fmt.Errorf("velox: unexpected foreign-key %q returned %v for node %v", "product_stocks", parentID, n.ID)
		}
		if !limit.Keep(parentID) {
			continue
		}
		assign(node, n)
	}
	return nil
}

// loadOrderItems eagerly loads the "order_items" edge for the given nodes.
func (q *ProductQuery) loadOrderItems(ctx context.Context, query *OrderItemQuery, nodes []*entity.Product, init func(*entity.Product), assign func(*entity.Product, *entity.OrderItem)) error {
	query = query.clone()
	fks := make([]any, 0, len(nodes))
	nodeids := make(map[int]*entity.Product, len(nodes))
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(func(s *sql.Selector) {
		s.Where(sql.In(s.C(product.OrderItemsColumn), fks...))
	})
	limit, err := runtime.PlanPerParentLimit[int](ctx, query.ctx, query.config.Driver, "order_items")
	if err != nil {
		return err
	}
	if limit.Active {
		query.modifiers = append(query.modifiers, func(s *sql.Selector) {
			limit.Apply(s, s.C(product.OrderItemsColumn), s.C(orderitem.FieldID))
		})
	}
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.FKValue("product_order_items")
		if fk == nil {
			return fmt.Errorf("velox: foreign-key %q is nil for node %v", "product_order_items", n.ID)
		}
		parentID := derefFK(fk).(int)
		node, ok := nodeids[parentID]
		if !ok {
			return fmt.Errorf("velox: unexpected foreign-key %q returned %v for node %v", "product_order_items", parentID, n.ID)
		}
		if !limit.Keep(parentID) {
			continue
		}
		assign(node, n)
	}
	return nil
}

// Verify ProductQuery implements entity.ProductQuerier at compile time.
var _ entity.ProductQuerier = (*ProductQuery)(nil)
