// Code generated by velox. DO NOT EDIT.

package todo

import "github.com/syssam/velox/runtime"

// TodoCollectMeta holds GraphQL field collection metadata for Todo.
var TodoCollectMeta runtime.CollectMeta

func init() {
	TodoCollectMeta.FieldColumns = map[string]string{"createdAt": FieldCreatedAt, "updatedAt": FieldUpdatedAt, "title": FieldTitle, "status": FieldStatus}
	TodoCollectMeta.Edges = map[string]runtime.EdgeMeta{"owner": {
		FKColumns:   []string{"user_todos"},
		Inverse:     "todos",
		Name:        "owner",
		PagesLoaded: false,
		Relay:       false,
		Target:      "users",
		Unique:      true,
	}}
}
