// Code generated by velox. DO NOT EDIT.

package todo

import (
	"time"

	predicate "github.com/syssam/graphql-go/examples/veloxfx/velox/predicate"
	sql "github.com/syssam/velox/dialect/sql"
	sqlgraph "github.com/syssam/velox/dialect/sql/sqlgraph"
)

// IDField is the predicate for the id field.
var IDField = sql.IntField[predicate.Todo](FieldID)

// CreatedAtField is the predicate for the "created_at" field.
var CreatedAtField = sql.TimeField[predicate.Todo, time.Time](FieldCreatedAt)

// UpdatedAtField is the predicate for the "updated_at" field.
var UpdatedAtField = sql.TimeField[predicate.Todo, time.Time](FieldUpdatedAt)

// TitleField is the predicate for the "title" field.
var TitleField = sql.StringField[predicate.Todo](FieldTitle)

// StatusField is the predicate for the "status" field.
var StatusField = sql.EnumField[predicate.Todo, Status](FieldStatus)

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.Todo {
	return predicate.Todo(func(s *sql.Selector) {
		step := sqlgraph.NewStep(sqlgraph.From(Table, FieldID), sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn))
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.Todo {
	return predicate.Todo(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
var And = sql.PredicateAnd[predicate.Todo]

// Or groups predicates with the OR operator between them.
var Or = sql.PredicateOr[predicate.Todo]

// Not applies the not operator on the given predicate.
var Not = sql.PredicateNot[predicate.Todo]
