// Code generated by gqlc. DO NOT EDIT.

// Package orderitem holds the types generated from the GraphQL schema.
package orderitem

import (
	gqlrelay "github.com/syssam/velox/contrib/graphql/gqlrelay"
)

type OrderItemOrderField string

const (
	OrderItemOrderFieldQuantity         OrderItemOrderField = "QUANTITY"
	OrderItemOrderFieldUnit_price_cents OrderItemOrderField = "UNIT_PRICE_CENTS"
)

type OrderItemOrder struct {
	Direction gqlrelay.OrderDirection `graphql:"direction"`
	Field     OrderItemOrderField     `graphql:"field"`
}
