// Code generated by velox. DO NOT EDIT.

package userclient

import (
	"context"
	"errors"
	"fmt"

	entity "github.com/syssam/graphql-go/examples/veloxfx/velox/entity"
	user "github.com/syssam/graphql-go/examples/veloxfx/velox/user"
	velox "github.com/syssam/velox"
	sqlgraph "github.com/syssam/velox/dialect/sql/sqlgraph"
	runtime "github.com/syssam/velox/runtime"
	field "github.com/syssam/velox/schema/field"
)

// userIDFieldType is the field.Type for User's primary key column.
var userIDFieldType = field.TypeInt

// userFieldTypes maps column names to field.Type for User.
var userFieldTypes = map[string]field.Type{"id": field.TypeInt, "name": field.TypeString, "email": field.TypeString}

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config   runtime.Config
	mutation *UserMutation
	hooks    []runtime.Hook
}

// NewUserCreate creates a new UserCreate builder.
func NewUserCreate(c runtime.Config, mutation *UserMutation, hooks []runtime.Hook) *UserCreate {
	return &UserCreate{
		config:   c,
		hooks:    hooks,
		mutation: mutation,
	}
}

// SetName sets the "name" field.
func (c *UserCreate) SetName(v string) *UserCreate {
	c.mutation.SetName(v)
	return c
}

// SetEmail sets the "email" field.
func (c *UserCreate) SetEmail(v string) *UserCreate {
	c.mutation.SetEmail(v)
	return c
}

// AddTodoIDs adds the "todos" edge by ids.
func (c *UserCreate) AddTodoIDs(ids ...int) *UserCreate {
	c.mutation.AddTodoIDs(ids...)
	return c
}

// AddTodos adds the "todos" edge to the given entities.
func (c *UserCreate) AddTodos(v ...*entity.Todo) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	c.AddTodoIDs(ids...)
	return c
}

// Mutation returns the UserMutation.
func (c *UserCreate) Mutation() *UserMutation {
	return c.mutation
}

// check runs all checks and user-defined validators on the builder.
func (c *UserCreate) check() error {
	if _, ok := c.mutation.Name(); !ok {
		return &runtime.ValidationError{
			Entity: "User",
			Err:    errors.New("missing required field \"User.name\""),
			Field:  "name",
			Name:   "name",
		}
	}
	if v, ok := c.mutation.Name(); ok {
		if err := user.NameValidator(v); err != nil {
			return &runtime.ValidationError{
				Entity: "User",
				Err:    fmt.Errorf("validator failed for field \"User.name\": %w", err),
				Field:  "name",
				Name:   "name",
			}
		}
	}
	if _, ok := c.mutation.Email(); !ok {
		return &runtime.ValidationError{
			Entity: "User",
			Err:    errors.New("missing required field \"User.email\""),
			Field:  "email",
			Name:   "email",
		}
	}
	return nil
}

// sqlSave executes the SQL create for User after hooks have run.
func (c *UserCreate) sqlSave(ctx context.Context) (*entity.User, error) {
	if err := c.check(); err != nil {
		return nil, err
	}
	_node, _spec := c.createSpec()
	if err := sqlgraph.CreateNode(ctx, c.config.Driver, _spec); err != nil {
		return nil, runtime.MayWrapConstraintError(err)
	}
	_node.SetConfig(c.config)
	if _spec.ID.Value != nil {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	c.mutation.SetID(_node.ID)
	return _node, nil
}

// createSpec builds the User node and sqlgraph.CreateSpec from mutation fields.
func (c *UserCreate) createSpec() (*entity.User, *sqlgraph.CreateSpec) {
	var (
		_node = &entity.User{}
		_spec = sqlgraph.NewCreateSpec(user.Table, &sqlgraph.FieldSpec{
			Column: user.FieldID,
			Type:   userIDFieldType,
		})
	)
	if c.mutation._name != nil {
		v := *c.mutation._name
		_spec.SetField("name", field.TypeString, v)
		_node.Name = v
	}
	if c.mutation._email != nil {
		v := *c.mutation._email
		_spec.SetField("email", field.TypeString, v)
		_node.Email = v
	}
	if nodes := c.mutation.TodosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"user_todos"},
			Inverse: false,
			Rel:     sqlgraph.O2M,
			Table:   "todos",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// Save creates the User in the database.
func (c *UserCreate) Save(ctx context.Context) (*entity.User, error) {
	hooks := c.hooks
	return velox.WithHooks[*entity.User, UserMutation, *UserMutation](ctx, c.sqlSave, c.mutation, hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (c *UserCreate) SaveX(ctx context.Context) *entity.User {
	v, err := c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (c *UserCreate) Exec(ctx context.Context) error {
	_, err := c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (c *UserCreate) ExecX(ctx context.Context) {
	if err := c.Exec(ctx); err != nil {
		panic(err)
	}
}

// UserCreateBulk is the builder for creating many User entities in bulk.
type UserCreateBulk struct {
	config    runtime.Config
	err       error
	builders  []*UserCreate
	batchSize int
}

// NewUserCreateBulk creates a new UserCreateBulk builder.
func NewUserCreateBulk(c runtime.Config, builders []*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{
		builders: builders,
		config:   c,
	}
}

// BatchSize sets the chunk size for the bulk insert.
// A value of 0 (default) means no chunking — all builders
// go through a single BatchCreate. When set, Save splits the
// builders into chunks of at most n and runs one INSERT per
// chunk. Use this to stay under SQLite's SQL-variable cap.
//
// Atomicity across chunks is NOT automatic. Wrap the call
// in client.Tx(ctx) if you need all-or-nothing semantics.
func (_cb *UserCreateBulk) BatchSize(n int) *UserCreateBulk {
	_cb.batchSize = n
	return _cb
}

// Save creates the User entities in the database.
//
// When BatchSize is 0 (default), all builders go through a
// single mutator chain ending in one BatchCreate. When
// BatchSize > 0, the builders are sliced into chunks of at
// most N and each chunk runs its own mutator chain + one
// INSERT. A mid-loop error returns the rows persisted so far
// together with the error — wrap in client.Tx(ctx) for
// all-or-nothing semantics.
func (_cb *UserCreateBulk) Save(ctx context.Context) ([]*entity.User, error) {
	if _cb.err != nil {
		return nil, _cb.err
	}
	if _cb.batchSize <= 0 || _cb.batchSize >= len(_cb.builders) {
		return _cb.saveChunk(ctx, _cb.builders)
	}
	nodes := make([]*entity.User, 0, len(_cb.builders))
	for start := 0; start < len(_cb.builders); start += _cb.batchSize {
		end := start + _cb.batchSize
		if end > len(_cb.builders) {
			end = len(_cb.builders)
		}
		chunk, err := _cb.saveChunk(ctx, _cb.builders[start:end])
		nodes = append(nodes, chunk...)
		if err != nil {
			return nodes, err
		}
	}
	return nodes, nil
}

// saveChunk runs one mutator chain over a sub-slice of the builders.
func (_cb *UserCreateBulk) saveChunk(ctx context.Context, builders []*UserCreate) ([]*entity.User, error) {
	if len(builders) == 0 {
		return []*entity.User{}, nil
	}
	specs := make([]*sqlgraph.CreateSpec, len(builders))
	nodes := make([]*entity.User, len(builders))
	mutators := make([]runtime.Mutator, len(builders))
	for i := range builders {
		func(i int, root context.Context) {
			builder := builders[i]
			var mut runtime.Mutator = runtime.MutateFunc(func(ctx context.Context, m runtime.Mutation) (runtime.Value, error) {
				mutation, ok := m.(*UserMutation)
				if !ok {
					return nil, fmt.Errorf("velox: unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				nodes[i].SetConfig(_cb.config)
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					if err = sqlgraph.BatchCreate(ctx, _cb.config.Driver, spec); err != nil {
						err = runtime.MayWrapConstraintError(err)
					}
				}
				if err != nil {
					return nil, err
				}
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
					mutation.SetID(int(id))
				}
				return nodes[i], nil
			})
			allHooks := builder.hooks
			for j := len(allHooks) - 1; j >= 0; j-- {
				mut = allHooks[j](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_cb *UserCreateBulk) SaveX(ctx context.Context) []*entity.User {
	v, err := _cb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_cb *UserCreateBulk) Exec(ctx context.Context) error {
	_, err := _cb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_cb *UserCreateBulk) ExecX(ctx context.Context) {
	if err := _cb.Exec(ctx); err != nil {
		panic(err)
	}
}
