// Code generated by velox. DO NOT EDIT.

package userclient

// CreateUserInput represents a mutation input for creating users.
type CreateUserInput struct {
	Name    string `json:"name"`
	Email   string `json:"email"`
	TodoIDs []int  `json:"todoIDs,omitempty"`
}

// Mutate applies the CreateUserInput on the UserMutation builder.
func (i *CreateUserInput) Mutate(m *UserMutation) {
	m.SetName(i.Name)
	m.SetEmail(i.Email)
	if len(i.TodoIDs) > 0 {
		m.AddTodoIDs(i.TodoIDs...)
	}
}

// SetInput applies the change-set in the CreateUserInput on the UserCreate builder.
func (c *UserCreate) SetInput(i CreateUserInput) *UserCreate {
	i.Mutate(c.Mutation())
	return c
}
