// Code generated by velox. DO NOT EDIT.

package userclient

import (
	"context"
	"fmt"

	entity "github.com/syssam/graphql-go/examples/veloxfx/velox/entity"
	predicate "github.com/syssam/graphql-go/examples/veloxfx/velox/predicate"
	velox "github.com/syssam/velox"
	sql "github.com/syssam/velox/dialect/sql"
	runtime "github.com/syssam/velox/runtime"
)

// UserMutation represents an operation that mutates the User nodes in the graph.
type UserMutation struct {
	config        runtime.Config
	op            runtime.Op
	id            *int
	_name         *string
	_email        *string
	clearedFields map[string]struct{}
	oldValue      func(context.Context) (*entity.User, error)
	oldLoaded     bool
	oldCache      *entity.User
	todos         map[int]struct{}
	removedTodos  map[int]struct{}
	clearedTodos  bool
	predicates    []predicate.User
}

var _ velox.Mutation = (*UserMutation)(nil)

// userOption allows management of the mutation configuration using functional options.
type userOption func(*UserMutation)

// NewUserMutation creates new mutation for the User entity.
func NewUserMutation(c runtime.Config, op runtime.Op, opts ...userOption) *UserMutation {
	m := &UserMutation{
		config: c,
		op:     runtime.Op(op),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// Op returns the operation name.
func (m *UserMutation) Op() runtime.Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *UserMutation) SetOp(op runtime.Op) {
	m.op = op
}

// Type returns the schema type name of this mutation ("User").
func (m *UserMutation) Type() string {
	return "User"
}

// ID returns the ID value in the mutation, if it was provided by the caller.
// The second bool return indicates whether the ID field was set.
func (m *UserMutation) ID() (id any, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetID sets the entity ID value on the mutation.
func (m *UserMutation) SetID(id int) {
	m.id = &id
}

// loadOld lazily loads the pre-mutation entity state for OldXxx methods.
func (m *UserMutation) loadOld(ctx context.Context) (*entity.User, error) {
	if m.op != runtime.OpUpdateOne {
		return nil, fmt.Errorf("OldField is only allowed on UpdateOne operations")
	}
	if m.oldValue == nil {
		return nil, fmt.Errorf("OldField is not supported: no old value loader configured")
	}
	if m.oldLoaded {
		return m.oldCache, nil
	}
	old, err := m.oldValue(ctx)
	if err != nil {
		return nil, fmt.Errorf("querying old values: %w", err)
	}
	m.oldCache = old
	m.oldLoaded = true
	return old, nil
}

// Where appends a list predicates to the UserMutation builder.
func (m *UserMutation) Where(ps ...predicate.User) {
	m.predicates = append(m.predicates, ps...)
}

// PredicatesFuncs returns the predicates as untyped selector functions.
func (m *UserMutation) PredicatesFuncs() []func(*sql.Selector) {
	ps := make([]func(*sql.Selector), len(m.predicates))
	for i, p := range m.predicates {
		ps[i] = p
	}
	return ps
}

// SetName sets the "name" field.
func (m *UserMutation) SetName(v string) {
	m._name = &v
}

// Name returns the value of the "name" field in the mutation.
func (m *UserMutation) Name() (r string, exists bool) {
	if m._name == nil {
		return
	}
	return *m._name, true
}

// ResetName resets all changes to the "name" field.
func (m *UserMutation) ResetName() {
	m._name = nil
	delete(m.clearedFields, "name")
}

// SetEmail sets the "email" field.
func (m *UserMutation) SetEmail(v string) {
	m._email = &v
}

// Email returns the value of the "email" field in the mutation.
func (m *UserMutation) Email() (r string, exists bool) {
	if m._email == nil {
		return
	}
	return *m._email, true
}

// ResetEmail resets all changes to the "email" field.
func (m *UserMutation) ResetEmail() {
	m._email = nil
	delete(m.clearedFields, "email")
}

// AddTodoIDs adds the "todos" edge to the Todo entity by ids.
func (m *UserMutation) AddTodoIDs(ids ...int) {
	if m.todos == nil {
		m.todos = make(map[int]struct{})
	}
	for _, id := range ids {
		m.todos[id] = struct{}{}
	}
}

// RemoveTodoIDs removes the "todos" edge to the Todo entity by ids.
func (m *UserMutation) RemoveTodoIDs(ids ...int) {
	if m.removedTodos == nil {
		m.removedTodos = make(map[int]struct{})
	}
	for _, id := range ids {
		delete(m.todos, id)
		m.removedTodos[id] = struct{}{}
	}
}

// ClearTodos clears the "todos" edge.
func (m *UserMutation) ClearTodos() {
	m.clearedTodos = true
}

// TodosCleared reports if the "todos" edge was cleared.
func (m *UserMutation) TodosCleared() bool {
	return m.clearedTodos
}

// RemovedTodosIDs returns the removed IDs of the "todos" edge.
func (m *UserMutation) RemovedTodosIDs() (ids []int) {
	for id := range m.removedTodos {
		ids = append(ids, id)
	}
	return
}

// ResetTodos resets all changes to the "todos" edge.
func (m *UserMutation) ResetTodos() {
	m.todos = nil
	m.clearedTodos = false
	m.removedTodos = nil
}

// TodosIDs returns the "todos" edge IDs in the mutation.
func (m *UserMutation) TodosIDs() (ids []int) {
	for id := range m.todos {
		ids = append(ids, id)
	}
	return
}

// Fields returns all fields that were changed during this mutation.
func (m *UserMutation) Fields() []string {
	var fields []string
	if m._name != nil {
		fields = append(fields, "name")
	}
	if m._email != nil {
		fields = append(fields, "email")
	}
	return fields
}

// Field returns the value of a field with the given name.
func (m *UserMutation) Field(name string) (runtime.Value, bool) {
	switch name {
	case "name":
		if m._name != nil {
			return *m._name, true
		}
	case "email":
		if m._email != nil {
			return *m._email, true
		}
	}
	return nil, false
}

// SetField sets the value of a field with the given name. It returns an error if the field is not defined in the schema, or if the value type does not match.
func (m *UserMutation) SetField(name string, value runtime.Value) error {
	switch name {
	case "name":
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field name", value)
		}
		m.SetName(v)
		return nil
	case "email":
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field email", value)
		}
		m.SetEmail(v)
		return nil
	default:
		return fmt.Errorf("unknown User field %s", name)
	}
}

// AddedFields returns all numeric fields that were incremented or decremented during this mutation.
func (m *UserMutation) AddedFields() []string {
	var fields []string
	return fields
}

// AddedField returns the numeric value that was incremented or decremented for a field.
func (m *UserMutation) AddedField(name string) (runtime.Value, bool) {
	switch name {
	}
	return nil, false
}

// AddField adds the value for the given name. It returns an error if the field is not defined in the schema, or if the value type does not match.
func (m *UserMutation) AddField(name string, value runtime.Value) error {
	switch name {
	default:
		return fmt.Errorf("unknown User addable field %s", name)
	}
}

// ClearedFields returns all fields that were cleared during this mutation.
func (m *UserMutation) ClearedFields() []string {
	var fields []string
	for f := range m.clearedFields {
		fields = append(fields, f)
	}
	return fields
}

// FieldCleared reports if a field with the given name was cleared in this mutation.
func (m *UserMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an error if the field is not defined in the schema or is not nullable.
func (m *UserMutation) ClearField(name string) error {
	return fmt.Errorf("unknown User nullable field %s", name)
}

// ResetField resets all changes for the field with the given name. It returns an error if the field is not defined in the schema.
func (m *UserMutation) ResetField(name string) error {
	switch name {
	case "name":
		m._name = nil
		delete(m.clearedFields, "name")
	case "email":
		m._email = nil
		delete(m.clearedFields, "email")
	default:
		return fmt.Errorf("unknown User field %s", name)
	}
	return nil
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UserMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.todos != nil {
		edges = append(edges, "todos")
	}
	return edges
}

// AddedIDs returns all IDs that were added for the given edge name.
func (m *UserMutation) AddedIDs(name string) []velox.Value {
	switch name {
	case "todos":
		ids := make([]velox.Value, 0, len(m.todos))
		for id := range m.todos {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UserMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedTodos != nil {
		edges = append(edges, "todos")
	}
	return edges
}

// RemovedIDs returns all IDs that were removed for the given edge name.
func (m *UserMutation) RemovedIDs(name string) []velox.Value {
	switch name {
	case "todos":
		ids := make([]velox.Value, 0, len(m.removedTodos))
		for id := range m.removedTodos {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UserMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedTodos {
		edges = append(edges, "todos")
	}
	return edges
}

// EdgeCleared reports if the given edge was cleared in this mutation.
func (m *UserMutation) EdgeCleared(name string) bool {
	switch name {
	case "todos":
		return m.clearedTodos
	}
	return false
}

// ClearEdge clears the value of the edge with the given name.
func (m *UserMutation) ClearEdge(name string) error {
	switch name {
	case "todos":
		m.ClearTodos()
		return nil
	}
	return fmt.Errorf("unknown User unique edge %s", name)
}

// ResetEdge resets all changes for the edge with the given name.
func (m *UserMutation) ResetEdge(name string) error {
	switch name {
	case "todos":
		m.ResetTodos()
		return nil
	}
	return fmt.Errorf("unknown User edge %s", name)
}

// OldField returns the old value of a field from the database.
// An error is returned if the mutation operation is not UpdateOne,
// or the query to the database fails.
func (m *UserMutation) OldField(ctx context.Context, name string) (velox.Value, error) {
	switch name {
	case "name":
		return m.OldName(ctx)
	case "email":
		return m.OldEmail(ctx)
	}
	return nil, fmt.Errorf("unknown User field %s", name)
}

// OldName returns the old "name" field value, if exists.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldName(ctx context.Context) (v string, err error) {
	old, loadErr := m.loadOld(ctx)
	if loadErr != nil {
		err = loadErr
		return
	}
	v = old.Name
	return
}

// OldEmail returns the old "email" field value, if exists.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldEmail(ctx context.Context) (v string, err error) {
	old, loadErr := m.loadOld(ctx)
	if loadErr != nil {
		err = loadErr
		return
	}
	v = old.Email
	return
}
