// Code generated by velox. DO NOT EDIT.

package userclient

import (
	"context"
	"errors"
	"fmt"

	entity "github.com/syssam/graphql-go/examples/veloxfx/velox/entity"
	predicate "github.com/syssam/graphql-go/examples/veloxfx/velox/predicate"
	user "github.com/syssam/graphql-go/examples/veloxfx/velox/user"
	velox "github.com/syssam/velox"
	sql "github.com/syssam/velox/dialect/sql"
	sqlgraph "github.com/syssam/velox/dialect/sql/sqlgraph"
	runtime "github.com/syssam/velox/runtime"
	field "github.com/syssam/velox/schema/field"
)

// UserUpdate is the update builder for User entities.
//
// Query interceptors do NOT run on mutations. A row filter registered
// with Intercept() leaves this builder unscoped, so express row-level
// authorization as a schema Policy() — it covers reads and writes.
type UserUpdate struct {
	config    runtime.Config
	mutation  *UserMutation
	hooks     []runtime.Hook
	modifiers []func(*sql.UpdateBuilder)
}

// NewUserUpdate creates a new UserUpdate builder.
func NewUserUpdate(c runtime.Config, mutation *UserMutation, hooks []runtime.Hook) *UserUpdate {
	return &UserUpdate{
		config:   c,
		hooks:    hooks,
		mutation: mutation,
	}
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *UserUpdate) SetName(v string) *UserUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUpdate) SetNillableName(v *string) *UserUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdate) SetEmail(v string) *UserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmail(v *string) *UserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// AddTodoIDs adds the "todos" edge by ids.
func (_u *UserUpdate) AddTodoIDs(ids ...int) *UserUpdate {
	_u.mutation.AddTodoIDs(ids...)
	return _u
}

// RemoveTodoIDs removes the "todos" edge by ids.
func (_u *UserUpdate) RemoveTodoIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveTodoIDs(ids...)
	return _u
}

// ClearTodos clears the "todos" edge.
func (_u *UserUpdate) ClearTodos() *UserUpdate {
	_u.mutation.ClearTodos()
	return _u
}

// AddTodos adds the "todos" edge to the given entities.
func (_u *UserUpdate) AddTodos(v ...*entity.Todo) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	_u.AddTodoIDs(ids...)
	return _u
}

// RemoveTodos removes the "todos" edge to the given entities.
func (_u *UserUpdate) RemoveTodos(v ...*entity.Todo) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	_u.RemoveTodoIDs(ids...)
	return _u
}

// Mutation returns the UserMutation.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UserUpdate) Modify(modifiers ...func(*sql.UpdateBuilder)) *UserUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

// check runs the user-defined validators on the fields this mutation sets
// and guards required unique edges against being cleared.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := user.NameValidator(v); err != nil {
			return &runtime.ValidationError{
				Entity: "User",
				Err:    fmt.Errorf("validator failed for field \"User.name\": %w", err),
				Field:  "name",
				Name:   "name",
			}
		}
	}
	return nil
}

// sqlSave executes the SQL update for User after hooks have run.
func (_u *UserUpdate) sqlSave(ctx context.Context) (int, error) {
	if err := _u.check(); err != nil {
		return 0, err
	}
	spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, &sqlgraph.FieldSpec{
		Column: user.FieldID,
		Type:   userIDFieldType,
	})
	if _u.mutation._name != nil {
		spec.SetField("name", field.TypeString, *_u.mutation._name)
	}
	if _u.mutation._email != nil {
		spec.SetField("email", field.TypeString, *_u.mutation._email)
	}
	ps := _u.mutation.PredicatesFuncs()
	if len(ps) > 0 {
		spec.Predicate = func(s *sql.Selector) {
			for i := range ps {
				ps[i](s)
			}
		}
	}
	if _u.mutation.TodosCleared() {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"user_todos"},
			Inverse: false,
			Rel:     sqlgraph.O2M,
			Table:   "todos",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		spec.Edges.Clear = append(spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTodosIDs(); len(nodes) > 0 && !_u.mutation.TodosCleared() {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"user_todos"},
			Inverse: false,
			Rel:     sqlgraph.O2M,
			Table:   "todos",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		spec.Edges.Clear = append(spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TodosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"user_todos"},
			Inverse: false,
			Rel:     sqlgraph.O2M,
			Table:   "todos",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		spec.Edges.Add = append(spec.Edges.Add, edge)
	}
	if len(_u.modifiers) > 0 {
		spec.AddModifiers(_u.modifiers...)
	}
	affected, err := sqlgraph.UpdateNodes(ctx, _u.config.Driver, spec)
	if err != nil {
		return 0, runtime.MayWrapConstraintError(err)
	}
	return affected, nil
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	hooks := _u.hooks
	return velox.WithHooks[int, UserMutation, *UserMutation](ctx, _u.sqlSave, _u.mutation, hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// UserUpdateOne is the update builder for a single User entity.
type UserUpdateOne struct {
	config       runtime.Config
	mutation     *UserMutation
	hooks        []runtime.Hook
	modifiers    []func(*sql.UpdateBuilder)
	selectFields []string
}

// NewUserUpdateOne creates a new UserUpdateOne builder.
func NewUserUpdateOne(c runtime.Config, mutation *UserMutation, hooks []runtime.Hook) *UserUpdateOne {
	return &UserUpdateOne{
		config:   c,
		hooks:    hooks,
		mutation: mutation,
	}
}

// Where appends a list predicates to the UserUpdateOne builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema. It narrows
// only what is read back — every field set on this builder is still written.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.selectFields = append([]string{field}, fields...)
	return _u
}

// SetName sets the "name" field.
func (_u *UserUpdateOne) SetName(v string) *UserUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdateOne) SetEmail(v string) *UserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmail(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// AddTodoIDs adds the "todos" edge by ids.
func (_u *UserUpdateOne) AddTodoIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddTodoIDs(ids...)
	return _u
}

// RemoveTodoIDs removes the "todos" edge by ids.
func (_u *UserUpdateOne) RemoveTodoIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveTodoIDs(ids...)
	return _u
}

// ClearTodos clears the "todos" edge.
func (_u *UserUpdateOne) ClearTodos() *UserUpdateOne {
	_u.mutation.ClearTodos()
	return _u
}

// AddTodos adds the "todos" edge to the given entities.
func (_u *UserUpdateOne) AddTodos(v ...*entity.Todo) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	_u.AddTodoIDs(ids...)
	return _u
}

// RemoveTodos removes the "todos" edge to the given entities.
func (_u *UserUpdateOne) RemoveTodos(v ...*entity.Todo) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	_u.RemoveTodoIDs(ids...)
	return _u
}

// Mutation returns the UserMutation.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UserUpdateOne) Modify(modifiers ...func(*sql.UpdateBuilder)) *UserUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

// check runs the user-defined validators on the fields this mutation sets
// and guards required unique edges against being cleared.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := user.NameValidator(v); err != nil {
			return &runtime.ValidationError{
				Entity: "User",
				Err:    fmt.Errorf("validator failed for field \"User.name\": %w", err),
				Field:  "name",
				Name:   "name",
			}
		}
	}
	return nil
}

// sqlSave executes the SQL update for a single User after hooks have run.
func (_u *UserUpdateOne) sqlSave(ctx context.Context) (*entity.User, error) {
	if err := _u.check(); err != nil {
		return nil, err
	}
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, errors.New("velox: missing ID for UpdateOne")
	}
	spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, &sqlgraph.FieldSpec{
		Column: user.FieldID,
		Type:   userIDFieldType,
	})
	if _u.mutation._name != nil {
		spec.SetField("name", field.TypeString, *_u.mutation._name)
	}
	if _u.mutation._email != nil {
		spec.SetField("email", field.TypeString, *_u.mutation._email)
	}
	spec.Node.ID.Value = id
	ps := _u.mutation.PredicatesFuncs()
	spec.Predicate = func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(user.FieldID), id))
		for i := range ps {
			ps[i](s)
		}
	}
	if _u.mutation.TodosCleared() {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"user_todos"},
			Inverse: false,
			Rel:     sqlgraph.O2M,
			Table:   "todos",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		spec.Edges.Clear = append(spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTodosIDs(); len(nodes) > 0 && !_u.mutation.TodosCleared() {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"user_todos"},
			Inverse: false,
			Rel:     sqlgraph.O2M,
			Table:   "todos",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		spec.Edges.Clear = append(spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TodosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"user_todos"},
			Inverse: false,
			Rel:     sqlgraph.O2M,
			Table:   "todos",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		spec.Edges.Add = append(spec.Edges.Add, edge)
	}
	if len(_u.modifiers) > 0 {
		spec.AddModifiers(_u.modifiers...)
	}
	if err := sqlgraph.UpdateNode(ctx, _u.config.Driver, spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			return nil, velox.NewNotFoundError("User")
		}
		return nil, runtime.MayWrapConstraintError(err)
	}
	columns := user.Columns
	if len(_u.selectFields) > 0 {
		columns = make([]string, 0, len(_u.selectFields)+1)
		columns = append(columns, user.FieldID)
		for _, f := range _u.selectFields {
			if !user.ValidColumn(f) {
				return nil, &runtime.ValidationError{
					Entity: "User",
					Err:    errors.New("invalid field for query"),
					Field:  f,
					Name:   f,
				}
			}
			if f != user.FieldID {
				columns = append(columns, f)
			}
		}
	}
	build := func(_ context.Context) (*sql.Selector, error) {
		s := sql.Select(columns...).From(sql.Table(user.Table))
		s.SetDialect(_u.config.Driver.Dialect())
		s.Where(sql.EQ(s.C(user.FieldID), id))
		s.Limit(1)
		return s, nil
	}
	_node, err2 := runtime.ScanFirst[entity.User, *entity.User](ctx, _u.config.Driver, build, "User")
	if err2 != nil {
		return nil, err2
	}
	_node.SetConfig(_u.config)
	return _node, nil
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*entity.User, error) {
	_u.mutation.oldValue = func(ctx context.Context) (*entity.User, error) {
		id, ok := _u.mutation.ID()
		if !ok {
			return nil, errors.New("velox: missing ID for OldField")
		}
		build := func(_ context.Context) (*sql.Selector, error) {
			s := sql.Select(user.Columns...).From(sql.Table(user.Table))
			s.SetDialect(_u.config.Driver.Dialect())
			s.Where(sql.EQ(s.C(user.FieldID), id))
			s.Limit(1)
			return s, nil
		}
		_old, err := runtime.ScanFirst[entity.User, *entity.User](ctx, _u.config.Driver, build, "User")
		if err != nil {
			return nil, err
		}
		_old.SetConfig(_u.config)
		return _old, nil
	}
	hooks := _u.hooks
	return velox.WithHooks[*entity.User, UserMutation, *UserMutation](ctx, _u.sqlSave, _u.mutation, hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *entity.User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}
