// Code generated by gqlc. DO NOT EDIT.

// Package warehouse holds the generated GraphQL bindings for the warehouse group.
package warehouse

import (
	"context"

	"github.com/syssam/graphql-go"
	warehouse "github.com/syssam/graphql-go/examples/veloxfx/velox/client/warehouse"
	entity "github.com/syssam/graphql-go/examples/veloxfx/velox/entity"
	filter "github.com/syssam/graphql-go/examples/veloxfx/velox/filter"
	gqlrelay "github.com/syssam/velox/contrib/graphql/gqlrelay"
)

type CreateWarehouseArgs struct {
	Input warehouse.CreateWarehouseInput `graphql:"input"`
}

type UpdateWarehouseArgs struct {
	ID    int                            `graphql:"id"`
	Input warehouse.UpdateWarehouseInput `graphql:"input"`
}

type DeleteWarehouseArgs struct {
	ID int `graphql:"id"`
}

type WarehouseArgs struct {
	ID int `graphql:"id"`
}

type WarehouseOrdersArgs struct {
	After   *gqlrelay.Cursor        `graphql:"after"`
	First   *int                    `graphql:"first"`
	Before  *gqlrelay.Cursor        `graphql:"before"`
	Last    *int                    `graphql:"last"`
	OrderBy *entity.OrderOrder      `graphql:"orderBy"`
	Where   *filter.OrderWhereInput `graphql:"where"`
}

// Resolver holds methods for fields that are not struct data.
type Resolver interface {
	CreateWarehouse(ctx context.Context, args CreateWarehouseArgs) (*entity.Warehouse, error)
	UpdateWarehouse(ctx context.Context, args UpdateWarehouseArgs) (*entity.Warehouse, error)
	DeleteWarehouse(ctx context.Context, args DeleteWarehouseArgs) (int, error)
	Warehouses(ctx context.Context) ([]*entity.Warehouse, error)
	Warehouse(ctx context.Context, args WarehouseArgs) (*entity.Warehouse, error)
}

func Bindings(r Resolver) graphql.SchemaOption {
	return graphql.Options(
		graphql.Input[warehouse.CreateWarehouseInput]("CreateWarehouseInput", graphql.ZeroForNull()),
		graphql.Input[warehouse.UpdateWarehouseInput]("UpdateWarehouseInput", graphql.ZeroForNull()),
		graphql.Object[entity.Warehouse]("Warehouse",
			graphql.Field("id", func(v *entity.Warehouse) int { return v.ID }),
			graphql.Field("name", func(v *entity.Warehouse) string { return v.Name }),
			graphql.Resolve("stocks", func(ctx context.Context, v *entity.Warehouse) ([]*entity.Stock, error) { return v.Stocks(ctx) }),
			graphql.ResolveArgs("orders", func(ctx context.Context, v *entity.Warehouse, a WarehouseOrdersArgs) (*entity.OrderConnection, error) {
				return v.Orders(ctx, a.After, a.First, a.Before, a.Last, a.OrderBy, a.Where)
			}),
		),
		graphql.Query(
			graphql.Resolve("warehouses", func(ctx context.Context, _ graphql.Root) ([]*entity.Warehouse, error) { return r.Warehouses(ctx) }),
			graphql.ResolveArgs("warehouse", func(ctx context.Context, _ graphql.Root, a WarehouseArgs) (*entity.Warehouse, error) {
				return r.Warehouse(ctx, a)
			}),
		),
		graphql.Mutation(
			graphql.ResolveArgs("createWarehouse", func(ctx context.Context, _ graphql.Root, a CreateWarehouseArgs) (*entity.Warehouse, error) {
				return r.CreateWarehouse(ctx, a)
			}),
			graphql.ResolveArgs("updateWarehouse", func(ctx context.Context, _ graphql.Root, a UpdateWarehouseArgs) (*entity.Warehouse, error) {
				return r.UpdateWarehouse(ctx, a)
			}),
			graphql.ResolveArgs("deleteWarehouse", func(ctx context.Context, _ graphql.Root, a DeleteWarehouseArgs) (int, error) {
				return r.DeleteWarehouse(ctx, a)
			}),
		),
		graphql.Args[CreateWarehouseArgs](),
		graphql.Args[UpdateWarehouseArgs](),
		graphql.Args[DeleteWarehouseArgs](),
		graphql.Args[WarehouseArgs](),
		graphql.Args[WarehouseOrdersArgs](),
	)
}
