// Code generated by gqlc. DO NOT EDIT.

// Package orderitem holds the generated GraphQL bindings for the orderitem group.
package orderitem

import (
	"context"

	"github.com/syssam/graphql-go"
	orderitem "github.com/syssam/graphql-go/examples/veloxfx/velox/client/orderitem"
	entity "github.com/syssam/graphql-go/examples/veloxfx/velox/entity"
)

type CreateOrderItemArgs struct {
	Input orderitem.CreateOrderItemInput `graphql:"input"`
}

// Resolver holds methods for fields that are not struct data.
type Resolver interface {
	CreateOrderItem(ctx context.Context, args CreateOrderItemArgs) (*entity.OrderItem, error)
	OrderItemID(ctx context.Context, obj *entity.OrderItem) (graphql.ID, error)
	OrderItems(ctx context.Context) ([]*entity.OrderItem, error)
}

func Bindings(r Resolver) graphql.SchemaOption {
	return graphql.Options(
		graphql.Input[orderitem.CreateOrderItemInput]("CreateOrderItemInput", graphql.ZeroForNull()),
		graphql.Object[entity.OrderItem]("OrderItem",
			graphql.Resolve("id", func(ctx context.Context, v *entity.OrderItem) (graphql.ID, error) { return r.OrderItemID(ctx, v) }),
			graphql.Field("quantity", func(v *entity.OrderItem) int { return v.Quantity }),
			graphql.Field("unitPriceCents", func(v *entity.OrderItem) int { return v.UnitPriceCents }),
			graphql.Resolve("order", func(ctx context.Context, v *entity.OrderItem) (*entity.Order, error) { return v.Order(ctx) }),
			graphql.Resolve("product", func(ctx context.Context, v *entity.OrderItem) (*entity.Product, error) { return v.Product(ctx) }),
		),
		graphql.Query(
			graphql.Resolve("orderItems", func(ctx context.Context, _ graphql.Root) ([]*entity.OrderItem, error) { return r.OrderItems(ctx) }),
		),
		graphql.Mutation(
			graphql.ResolveArgs("createOrderItem", func(ctx context.Context, _ graphql.Root, a CreateOrderItemArgs) (*entity.OrderItem, error) {
				return r.CreateOrderItem(ctx, a)
			}),
		),
		graphql.Args[CreateOrderItemArgs](),
	)
}
