// Code generated by gqlc. DO NOT EDIT.

// Package orderitem holds the generated GraphQL bindings for the orderitem group.
package orderitem

import (
	"context"

	"github.com/syssam/graphql-go"
	entity "github.com/syssam/graphql-go/examples/veloxfx/velox/entity"
)

type OrderItemArgs struct {
	ID int `graphql:"id"`
}

// Resolver holds methods for fields that are not struct data.
type Resolver interface {
	OrderItems(ctx context.Context) ([]*entity.OrderItem, error)
	OrderItem(ctx context.Context, args OrderItemArgs) (*entity.OrderItem, error)
}

func Bindings(r Resolver) graphql.SchemaOption {
	return graphql.Options(
		graphql.Object[entity.OrderItem]("OrderItem",
			graphql.Field("id", func(v *entity.OrderItem) int { return v.ID }),
			graphql.Field("quantity", func(v *entity.OrderItem) int { return v.Quantity }),
			graphql.Field("unitPriceCents", func(v *entity.OrderItem) int { return v.UnitPriceCents }),
			graphql.Resolve("order", func(ctx context.Context, v *entity.OrderItem) (*entity.Order, error) { return v.Order(ctx) }),
			graphql.Resolve("product", func(ctx context.Context, v *entity.OrderItem) (*entity.Product, error) { return v.Product(ctx) }),
		),
		graphql.Query(
			graphql.Resolve("orderItems", func(ctx context.Context, _ graphql.Root) ([]*entity.OrderItem, error) { return r.OrderItems(ctx) }),
			graphql.ResolveArgs("orderItem", func(ctx context.Context, _ graphql.Root, a OrderItemArgs) (*entity.OrderItem, error) {
				return r.OrderItem(ctx, a)
			}),
		),
		graphql.Args[OrderItemArgs](),
	)
}
