// Code generated by velox. DO NOT EDIT.

package hook

import (
	"context"
	"fmt"

	velox "github.com/syssam/graphql-go/examples/veloxfx/velox"
	todo "github.com/syssam/graphql-go/examples/veloxfx/velox/client/todo"
	user "github.com/syssam/graphql-go/examples/veloxfx/velox/client/user"
	velox1 "github.com/syssam/velox"
)

// The TodoFunc type is an adapter to allow the use of ordinary
// function as Todo mutator.
type TodoFunc func(context.Context, *todo.TodoMutation) (velox.Value, error)

// Mutate calls f(ctx, m).
func (f TodoFunc) Mutate(ctx context.Context, m velox1.Mutation) (velox1.Value, error) {
	if mv, ok := m.(*todo.TodoMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *github.com/syssam/graphql-go/examples/veloxfx/velox/client/todo.TodoMutation", m)
}

// The UserFunc type is an adapter to allow the use of ordinary
// function as User mutator.
type UserFunc func(context.Context, *user.UserMutation) (velox.Value, error)

// Mutate calls f(ctx, m).
func (f UserFunc) Mutate(ctx context.Context, m velox1.Mutation) (velox1.Value, error) {
	if mv, ok := m.(*user.UserMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *github.com/syssam/graphql-go/examples/veloxfx/velox/client/user.UserMutation", m)
}

// Condition is a hook condition function.
type Condition func(context.Context, velox1.Mutation) bool

// And groups conditions with the AND operator.
func And(first Condition, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m velox1.Mutation) bool {
		if !first(ctx, m) || !second(ctx, m) {
			return false
		}
		for _, cond := range rest {
			if !cond(ctx, m) {
				return false
			}
		}
		return true
	}
}

// Or groups conditions with the OR operator.
func Or(first Condition, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m velox1.Mutation) bool {
		if first(ctx, m) || second(ctx, m) {
			return true
		}
		for _, cond := range rest {
			if cond(ctx, m) {
				return true
			}
		}
		return false
	}
}

// Not negates a given condition.
func Not(cond Condition) Condition {
	return func(ctx context.Context, m velox1.Mutation) bool {
		return !cond(ctx, m)
	}
}

// HasOp is a condition testing mutation operation.
func HasOp(op velox1.Op) Condition {
	return func(_ context.Context, m velox1.Mutation) bool {
		return m.Op().Is(op)
	}
}

// HasFields is a condition validating `.Field` on fields.
func HasFields(field string, fields ...string) Condition {
	return func(_ context.Context, m velox1.Mutation) bool {
		if _, exists := m.Field(field); !exists {
			return false
		}
		for _, f := range fields {
			if _, exists := m.Field(f); !exists {
				return false
			}
		}
		return true
	}
}

// HasAddedFields is a condition validating `.AddedField` on fields.
func HasAddedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m velox1.Mutation) bool {
		if _, exists := m.AddedField(field); !exists {
			return false
		}
		for _, f := range fields {
			if _, exists := m.AddedField(f); !exists {
				return false
			}
		}
		return true
	}
}

// HasClearedFields is a condition validating `.FieldCleared` on fields.
func HasClearedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m velox1.Mutation) bool {
		if !m.FieldCleared(field) {
			return false
		}
		for _, f := range fields {
			if !m.FieldCleared(f) {
				return false
			}
		}
		return true
	}
}

// HasEdge is a condition validating `.AddedEdges` OR `.RemovedEdges` on edges.
func HasEdge(edge string, edges ...string) Condition {
	return func(_ context.Context, m velox1.Mutation) bool {
		if len(m.AddedIDs(edge)) == 0 && len(m.RemovedIDs(edge)) == 0 {
			return false
		}
		for _, e := range edges {
			if len(m.AddedIDs(e)) == 0 && len(m.RemovedIDs(e)) == 0 {
				return false
			}
		}
		return true
	}
}

// HasClearedEdge is a condition validating `.EdgeCleared` on edges.
func HasClearedEdge(edge string, edges ...string) Condition {
	return func(_ context.Context, m velox1.Mutation) bool {
		if !m.EdgeCleared(edge) {
			return false
		}
		for _, e := range edges {
			if !m.EdgeCleared(e) {
				return false
			}
		}
		return true
	}
}

// If executes the given hook under condition.
//
//	hook.If(ComputeAverage, And(HasFields(...), HasAddedFields(...)))
func If(hk velox1.Hook, cond Condition) velox1.Hook {
	return func(next velox1.Mutator) velox1.Mutator {
		return velox1.MutateFunc(func(ctx context.Context, m velox1.Mutation) (velox1.Value, error) {
			if cond(ctx, m) {
				return hk(next).Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}

// On executes the given hook only for the given operation.
//
//	hook.On(Log, velox.Delete|velox.Create)
func On(hk velox1.Hook, op velox1.Op) velox1.Hook {
	return If(hk, HasOp(op))
}

// Unless skips the given hook only for the given operation.
//
//	hook.Unless(Log, velox.Update|velox.UpdateOne)
func Unless(hk velox1.Hook, op velox1.Op) velox1.Hook {
	return If(hk, Not(HasOp(op)))
}

// FixedError is a hook returning a fixed error.
func FixedError(err error) velox1.Hook {
	return func(velox1.Mutator) velox1.Mutator {
		return velox1.MutateFunc(func(context.Context, velox1.Mutation) (velox1.Value, error) {
			return nil, err
		})
	}
}

// Reject returns a hook that rejects all operations that match op.
//
//	func (T) Hooks() []velox.Hook {
//		return []velox.Hook{
//			Reject(velox.Delete|velox.Update),
//		}
//	}
func Reject(op velox1.Op) velox1.Hook {
	hk := FixedError(fmt.Errorf("%s operation is not allowed", op))
	return On(hk, op)
}

// Chain acts as a list of hooks and is effectively immutable.
// Once created, it will always hold the same set of hooks in the same order.
type Chain struct {
	hooks []velox1.Hook
}

// NewChain creates a new chain of hooks.
func NewChain(hooks ...velox1.Hook) Chain {
	return Chain{hooks: append([]velox1.Hook(nil), hooks...)}
}

// Hook chains the list of hooks and returns the final hook.
func (c Chain) Hook() velox1.Hook {
	return func(mutator velox1.Mutator) velox1.Mutator {
		for i := len(c.hooks) - 1; i >= 0; i-- {
			mutator = c.hooks[i](mutator)
		}
		return mutator
	}
}

// Append extends a chain, adding the specified hook
// as the last ones in the mutation flow.
func (c Chain) Append(hooks ...velox1.Hook) Chain {
	newHooks := make([]velox1.Hook, 0, len(c.hooks)+len(hooks))
	newHooks = append(newHooks, c.hooks...)
	newHooks = append(newHooks, hooks...)
	return Chain{hooks: newHooks}
}

// Extend extends a chain, adding the specified chain
// as the last ones in the mutation flow.
func (c Chain) Extend(chain Chain) Chain {
	return c.Append(chain.hooks...)
}
