// Code generated by gqlc. DO NOT EDIT.

package graph

import (
	"github.com/syssam/graphql-go"
	"github.com/syssam/graphql-go/examples/basic/graph/model"
)

type CreatePostArgs struct {
	AuthorID graphql.ID
	Title    string
	Body     string
}

type UpdatePostArgs struct {
	ID    graphql.ID
	Input model.UpdatePostInput
}

type NodeArgs struct {
	ID graphql.ID
}

type UserArgs struct {
	ID graphql.ID
}

type PostsArgs struct {
	Filter *model.PostFilter
}

type SearchArgs struct {
	Term string
}

type UserPostsArgs struct {
	First *int
}
