// Code generated by gqlc. DO NOT EDIT.

package graph

import (
	"context"
	"time"

	"github.com/syssam/graphql-go"
	"github.com/syssam/graphql-go/examples/basic/graph/model"
)

type CreatePostArgs struct {
	AuthorID graphql.ID
	Title    string
	Body     string
}

type UpdatePostArgs struct {
	ID    graphql.ID
	Input model.UpdatePostInput
}

type NodeArgs struct {
	ID graphql.ID
}

type UserArgs struct {
	ID graphql.ID
}

type PostsArgs struct {
	Filter *model.PostFilter
}

type SearchArgs struct {
	Term string
}

type UserPostsArgs struct {
	First *int
}

// Resolver holds methods for fields that are not struct data.
type Resolver interface {
	CreatePost(ctx context.Context, args CreatePostArgs) (*model.Post, error)
	UpdatePost(ctx context.Context, args UpdatePostArgs) (*model.Post, error)
	PostAuthor(ctx context.Context, obj *model.Post) (*model.User, error)
	Node(ctx context.Context, args NodeArgs) (any, error)
	User(ctx context.Context, args UserArgs) (*model.User, error)
	Users(ctx context.Context) ([]*model.User, error)
	Posts(ctx context.Context, args PostsArgs) ([]*model.Post, error)
	Search(ctx context.Context, args SearchArgs) ([]any, error)
	UserPosts(ctx context.Context, obj *model.User, args UserPostsArgs) ([]*model.Post, error)
}

func Bindings(r Resolver) graphql.SchemaOption {
	return graphql.Options(
		graphql.Enum[model.Role]("Role", map[model.Role]string{
			model.RoleAdmin: "ADMIN",
			model.RoleUser:  "USER",
		}),
		graphql.Input[model.PostFilter]("PostFilter"),
		graphql.Input[model.UpdatePostInput]("UpdatePostInput"),
		graphql.Interface[any]("Node"),
		graphql.Union[any]("SearchResult"),
		graphql.Object[model.Post]("Post",
			graphql.Field("id", func(v *model.Post) graphql.ID { return v.ID }),
			graphql.Field("title", func(v *model.Post) string { return v.Title }),
			graphql.Field("body", func(v *model.Post) string { return v.Body }),
			graphql.Resolve("author", func(ctx context.Context, v *model.Post) (*model.User, error) { return r.PostAuthor(ctx, v) }),
			graphql.Field("tags", func(v *model.Post) []string { return v.Tags }),
			graphql.Field("publishedAt", func(v *model.Post) *time.Time { return v.PublishedAt }),
		),
		graphql.Object[model.User]("User",
			graphql.Field("id", func(v *model.User) graphql.ID { return v.ID }),
			graphql.Field("name", func(v *model.User) string { return v.Name }),
			graphql.Field("email", func(v *model.User) string { return v.Email }),
			graphql.Field("role", func(v *model.User) model.Role { return v.Role }),
			graphql.ResolveArgs("posts", func(ctx context.Context, v *model.User, a UserPostsArgs) ([]*model.Post, error) {
				return r.UserPosts(ctx, v, a)
			}),
			graphql.Field("createdAt", func(v *model.User) time.Time { return v.CreatedAt }),
		),
		graphql.Query(
			graphql.ResolveArgs("node", func(ctx context.Context, _ graphql.Root, a NodeArgs) (any, error) { return r.Node(ctx, a) }),
			graphql.ResolveArgs("user", func(ctx context.Context, _ graphql.Root, a UserArgs) (*model.User, error) { return r.User(ctx, a) }),
			graphql.Resolve("users", func(ctx context.Context, _ graphql.Root) ([]*model.User, error) { return r.Users(ctx) }),
			graphql.ResolveArgs("posts", func(ctx context.Context, _ graphql.Root, a PostsArgs) ([]*model.Post, error) { return r.Posts(ctx, a) }),
			graphql.ResolveArgs("search", func(ctx context.Context, _ graphql.Root, a SearchArgs) ([]any, error) { return r.Search(ctx, a) }),
		),
		graphql.Mutation(
			graphql.ResolveArgs("createPost", func(ctx context.Context, _ graphql.Root, a CreatePostArgs) (*model.Post, error) {
				return r.CreatePost(ctx, a)
			}),
			graphql.ResolveArgs("updatePost", func(ctx context.Context, _ graphql.Root, a UpdatePostArgs) (*model.Post, error) {
				return r.UpdatePost(ctx, a)
			}),
		),
		graphql.Args[CreatePostArgs](),
		graphql.Args[UpdatePostArgs](),
		graphql.Args[NodeArgs](),
		graphql.Args[UserArgs](),
		graphql.Args[PostsArgs](),
		graphql.Args[SearchArgs](),
		graphql.Args[UserPostsArgs](),
	)
}
