// Code generated by velox. DO NOT EDIT.

package stockclient

import (
	"context"

	predicate "github.com/syssam/graphql-go/examples/veloxfx/velox/predicate"
	stock "github.com/syssam/graphql-go/examples/veloxfx/velox/stock"
	velox "github.com/syssam/velox"
	runtime "github.com/syssam/velox/runtime"
)

// StockDelete is the builder for deleting a Stock entity.
//
// Query interceptors do NOT run on mutations. A row filter registered
// with Intercept() leaves this builder unscoped, so express row-level
// authorization as a schema Policy() — it covers reads and writes.
type StockDelete struct {
	config   runtime.Config
	hooks    []runtime.Hook
	mutation *StockMutation
}

// NewStockDelete creates a new StockDelete builder.
func NewStockDelete(c runtime.Config, mutation *StockMutation, hooks []runtime.Hook) *StockDelete {
	return &StockDelete{
		config:   c,
		hooks:    hooks,
		mutation: mutation,
	}
}

// Where appends a list predicates to the StockDelete builder.
func (_d *StockDelete) Where(ps ...predicate.Stock) *StockDelete {
	_d.mutation.Where(ps...)
	return _d
}

// sqlExec executes the SQL delete for Stock after hooks have run.
func (_d *StockDelete) sqlExec(ctx context.Context) (int, error) {
	ps := _d.mutation.PredicatesFuncs()
	base := &runtime.DeleterBase{
		Driver:     _d.config.Driver,
		FieldTypes: stockFieldTypes,
		IDColumn:   stock.FieldID,
		IDType:     stockIDFieldType,
		Predicates: ps,
		Table:      stock.Table,
	}
	affected, err := runtime.DeleteNodes(ctx, base)
	if err != nil {
		return 0, err
	}
	return affected, nil
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *StockDelete) Exec(ctx context.Context) (int, error) {
	hooks := _d.hooks
	return velox.WithHooks[int, StockMutation, *StockMutation](ctx, _d.sqlExec, _d.mutation, hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *StockDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

// Mutation returns the StockMutation.
func (_d *StockDelete) Mutation() *StockMutation {
	return _d.mutation
}

// StockDeleteOne is the builder for deleting a single Stock entity.
type StockDeleteOne struct {
	d *StockDelete
}

// NewStockDeleteOne creates a new StockDeleteOne builder.
func NewStockDeleteOne(inner *StockDelete) *StockDeleteOne {
	return &StockDeleteOne{d: inner}
}

// Exec executes the deletion query.
func (_d *StockDeleteOne) Exec(ctx context.Context) error {
	n, err := _d.d.Exec(ctx)
	if err != nil {
		return err
	}
	if n == 0 {
		return velox.NewNotFoundError("Stock")
	}
	return nil
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *StockDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}

// Where appends a list predicates to the StockDeleteOne builder.
func (_d *StockDeleteOne) Where(ps ...predicate.Stock) *StockDeleteOne {
	_d.d.mutation.Where(ps...)
	return _d
}

// Mutation returns the StockMutation.
func (_d *StockDeleteOne) Mutation() *StockMutation {
	return _d.d.mutation
}
