// Code generated by velox. DO NOT EDIT.

package stockclient

// CreateStockInput represents a mutation input for creating stocks.
type CreateStockInput struct {
	Quantity    int `json:"quantity"`
	WarehouseID int `json:"warehouseID"`
	ProductID   int `json:"productID"`
}

// Mutate applies the CreateStockInput on the StockMutation builder.
func (i *CreateStockInput) Mutate(m *StockMutation) {
	m.SetQuantity(i.Quantity)
	m.SetWarehouseID(i.WarehouseID)
	m.SetProductID(i.ProductID)
}

// SetInput applies the change-set in the CreateStockInput on the StockCreate builder.
func (c *StockCreate) SetInput(i CreateStockInput) *StockCreate {
	i.Mutate(c.Mutation())
	return c
}
