// Code generated by velox. DO NOT EDIT.

package stockclient

import (
	"context"
	"fmt"

	entity "github.com/syssam/graphql-go/examples/veloxfx/velox/entity"
	predicate "github.com/syssam/graphql-go/examples/veloxfx/velox/predicate"
	velox "github.com/syssam/velox"
	sql "github.com/syssam/velox/dialect/sql"
	runtime "github.com/syssam/velox/runtime"
)

// StockMutation represents an operation that mutates the Stock nodes in the graph.
type StockMutation struct {
	config           runtime.Config
	op               runtime.Op
	id               *int
	_quantity        *int
	_addquantity     *int
	clearedFields    map[string]struct{}
	oldValue         func(context.Context) (*entity.Stock, error)
	oldLoaded        bool
	oldCache         *entity.Stock
	done             bool
	warehouse        map[int]struct{}
	removedWarehouse map[int]struct{}
	clearedWarehouse bool
	product          map[int]struct{}
	removedProduct   map[int]struct{}
	clearedProduct   bool
	predicates       []predicate.Stock
}

var _ velox.Mutation = (*StockMutation)(nil)

// stockOption allows management of the mutation configuration using functional options.
type stockOption func(*StockMutation)

// NewStockMutation creates new mutation for the Stock entity.
func NewStockMutation(c runtime.Config, op runtime.Op, opts ...stockOption) *StockMutation {
	m := &StockMutation{
		config: c,
		op:     runtime.Op(op),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// Op returns the operation name.
func (m *StockMutation) Op() runtime.Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *StockMutation) SetOp(op runtime.Op) {
	m.op = op
}

// Type returns the schema type name of this mutation ("Stock").
func (m *StockMutation) Type() string {
	return "Stock"
}

// ID returns the ID value in the mutation, if it was provided by the caller.
// The second bool return indicates whether the ID field was set.
func (m *StockMutation) ID() (id any, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetID sets the entity ID value on the mutation.
func (m *StockMutation) SetID(id int) {
	m.id = &id
}

// loadOld lazily loads the pre-mutation entity state for OldXxx methods.
func (m *StockMutation) loadOld(ctx context.Context) (*entity.Stock, error) {
	if m.op != runtime.OpUpdateOne {
		return nil, fmt.Errorf("OldField is only allowed on UpdateOne operations")
	}
	if m.oldValue == nil {
		return nil, fmt.Errorf("OldField is not supported: no old value loader configured")
	}
	if m.oldLoaded {
		return m.oldCache, nil
	}
	if m.done {
		return nil, fmt.Errorf("%w: call Stock.OldXxx in the hook before next.Mutate", runtime.ErrOldValueAfterMutation)
	}
	old, err := m.oldValue(ctx)
	if err != nil {
		return nil, fmt.Errorf("querying old values: %w", err)
	}
	m.oldCache = old
	m.oldLoaded = true
	return old, nil
}

// Where appends a list predicates to the StockMutation builder.
func (m *StockMutation) Where(ps ...predicate.Stock) {
	m.predicates = append(m.predicates, ps...)
}

// PredicatesFuncs returns the predicates as untyped selector functions.
func (m *StockMutation) PredicatesFuncs() []func(*sql.Selector) {
	ps := make([]func(*sql.Selector), len(m.predicates))
	for i, p := range m.predicates {
		ps[i] = p
	}
	return ps
}

// SetQuantity sets the "quantity" field.
func (m *StockMutation) SetQuantity(v int) {
	m._quantity = &v
	m._addquantity = nil
}

// Quantity returns the value of the "quantity" field in the mutation.
func (m *StockMutation) Quantity() (r int, exists bool) {
	if m._quantity == nil {
		return
	}
	return *m._quantity, true
}

// AddQuantity adds v to the "quantity" field.
func (m *StockMutation) AddQuantity(v int) {
	if m._addquantity != nil {
		*m._addquantity += v
	} else {
		m._addquantity = &v
	}
}

// AddedQuantity returns the value that was added to the "quantity" field in this mutation.
func (m *StockMutation) AddedQuantity() (r int, exists bool) {
	if m._addquantity == nil {
		return
	}
	return *m._addquantity, true
}

// ResetQuantity resets all changes to the "quantity" field.
func (m *StockMutation) ResetQuantity() {
	m._quantity = nil
	m._addquantity = nil
	delete(m.clearedFields, "quantity")
}

// SetWarehouseID sets the "warehouse" edge to the Warehouse entity by id.
func (m *StockMutation) SetWarehouseID(id int) {
	m.warehouse = map[int]struct{}{id: {}}
}

// ClearWarehouse clears the "warehouse" edge.
func (m *StockMutation) ClearWarehouse() {
	m.clearedWarehouse = true
}

// WarehouseCleared reports if the "warehouse" edge was cleared.
func (m *StockMutation) WarehouseCleared() bool {
	return m.clearedWarehouse
}

// ResetWarehouse resets all changes to the "warehouse" edge.
func (m *StockMutation) ResetWarehouse() {
	m.warehouse = nil
	m.clearedWarehouse = false
	m.removedWarehouse = nil
}

// WarehouseIDs returns the "warehouse" edge IDs in the mutation.
func (m *StockMutation) WarehouseIDs() (ids []int) {
	for id := range m.warehouse {
		ids = append(ids, id)
	}
	return
}

// SetProductID sets the "product" edge to the Product entity by id.
func (m *StockMutation) SetProductID(id int) {
	m.product = map[int]struct{}{id: {}}
}

// ClearProduct clears the "product" edge.
func (m *StockMutation) ClearProduct() {
	m.clearedProduct = true
}

// ProductCleared reports if the "product" edge was cleared.
func (m *StockMutation) ProductCleared() bool {
	return m.clearedProduct
}

// ResetProduct resets all changes to the "product" edge.
func (m *StockMutation) ResetProduct() {
	m.product = nil
	m.clearedProduct = false
	m.removedProduct = nil
}

// ProductIDs returns the "product" edge IDs in the mutation.
func (m *StockMutation) ProductIDs() (ids []int) {
	for id := range m.product {
		ids = append(ids, id)
	}
	return
}

// Fields returns all fields that were changed during this mutation.
func (m *StockMutation) Fields() []string {
	var fields []string
	if m._quantity != nil {
		fields = append(fields, "quantity")
	}
	return fields
}

// Field returns the value of a field with the given name.
func (m *StockMutation) Field(name string) (runtime.Value, bool) {
	switch name {
	case "quantity":
		if m._quantity != nil {
			return *m._quantity, true
		}
	}
	return nil, false
}

// SetField sets the value of a field with the given name. It returns an error if the field is not defined in the schema, or if the value type does not match.
func (m *StockMutation) SetField(name string, value runtime.Value) error {
	switch name {
	case "quantity":
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field quantity", value)
		}
		m.SetQuantity(v)
		return nil
	default:
		return fmt.Errorf("unknown Stock field %s", name)
	}
}

// AddedFields returns all numeric fields that were incremented or decremented during this mutation.
func (m *StockMutation) AddedFields() []string {
	var fields []string
	if m._addquantity != nil {
		fields = append(fields, "quantity")
	}
	return fields
}

// AddedField returns the numeric value that was incremented or decremented for a field.
func (m *StockMutation) AddedField(name string) (runtime.Value, bool) {
	switch name {
	case "quantity":
		if m._addquantity != nil {
			return *m._addquantity, true
		}
	}
	return nil, false
}

// AddField adds the value for the given name. It returns an error if the field is not defined in the schema, or if the value type does not match.
func (m *StockMutation) AddField(name string, value runtime.Value) error {
	switch name {
	case "quantity":
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field quantity", value)
		}
		m.AddQuantity(v)
		return nil
	default:
		return fmt.Errorf("unknown Stock addable field %s", name)
	}
}

// ClearedFields returns all fields that were cleared during this mutation.
func (m *StockMutation) ClearedFields() []string {
	var fields []string
	for f := range m.clearedFields {
		fields = append(fields, f)
	}
	return fields
}

// FieldCleared reports if a field with the given name was cleared in this mutation.
func (m *StockMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an error if the field is not defined in the schema or is not nullable.
func (m *StockMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Stock nullable field %s", name)
}

// ResetField resets all changes for the field with the given name. It returns an error if the field is not defined in the schema.
func (m *StockMutation) ResetField(name string) error {
	switch name {
	case "quantity":
		m._quantity = nil
		m._addquantity = nil
		delete(m.clearedFields, "quantity")
	default:
		return fmt.Errorf("unknown Stock field %s", name)
	}
	return nil
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *StockMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.warehouse != nil {
		edges = append(edges, "warehouse")
	}
	if m.product != nil {
		edges = append(edges, "product")
	}
	return edges
}

// AddedIDs returns all IDs that were added for the given edge name.
func (m *StockMutation) AddedIDs(name string) []velox.Value {
	switch name {
	case "warehouse":
		ids := make([]velox.Value, 0, len(m.warehouse))
		for id := range m.warehouse {
			ids = append(ids, id)
		}
		return ids
	case "product":
		ids := make([]velox.Value, 0, len(m.product))
		for id := range m.product {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *StockMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removedWarehouse != nil {
		edges = append(edges, "warehouse")
	}
	if m.removedProduct != nil {
		edges = append(edges, "product")
	}
	return edges
}

// RemovedIDs returns all IDs that were removed for the given edge name.
func (m *StockMutation) RemovedIDs(name string) []velox.Value {
	switch name {
	case "warehouse":
		ids := make([]velox.Value, 0, len(m.removedWarehouse))
		for id := range m.removedWarehouse {
			ids = append(ids, id)
		}
		return ids
	case "product":
		ids := make([]velox.Value, 0, len(m.removedProduct))
		for id := range m.removedProduct {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *StockMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedWarehouse {
		edges = append(edges, "warehouse")
	}
	if m.clearedProduct {
		edges = append(edges, "product")
	}
	return edges
}

// EdgeCleared reports if the given edge was cleared in this mutation.
func (m *StockMutation) EdgeCleared(name string) bool {
	switch name {
	case "warehouse":
		return m.clearedWarehouse
	case "product":
		return m.clearedProduct
	}
	return false
}

// ClearEdge clears the value of the edge with the given name.
func (m *StockMutation) ClearEdge(name string) error {
	switch name {
	case "warehouse":
		m.ClearWarehouse()
		return nil
	case "product":
		m.ClearProduct()
		return nil
	}
	return fmt.Errorf("unknown Stock edge %s", name)
}

// ResetEdge resets all changes for the edge with the given name.
func (m *StockMutation) ResetEdge(name string) error {
	switch name {
	case "warehouse":
		m.ResetWarehouse()
		return nil
	case "product":
		m.ResetProduct()
		return nil
	}
	return fmt.Errorf("unknown Stock edge %s", name)
}

// OldField returns the old value of a field from the database.
// An error is returned if the mutation operation is not UpdateOne,
// or the query to the database fails.
func (m *StockMutation) OldField(ctx context.Context, name string) (velox.Value, error) {
	switch name {
	case "quantity":
		return m.OldQuantity(ctx)
	}
	return nil, fmt.Errorf("unknown Stock field %s", name)
}

// OldQuantity returns the old "quantity" field value, if exists.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StockMutation) OldQuantity(ctx context.Context) (v int, err error) {
	old, loadErr := m.loadOld(ctx)
	if loadErr != nil {
		err = loadErr
		return
	}
	v = old.Quantity
	return
}
