// Code generated by velox. DO NOT EDIT.

package orderclient

import order "github.com/syssam/graphql-go/examples/veloxfx/velox/order"

// CreateOrderInput represents a mutation input for creating orders.
type CreateOrderInput struct {
	Status     *order.Status `json:"status,omitempty"`
	CustomerID int           `json:"customerID"`
	ItemIDs    []int         `json:"itemIDs,omitempty"`
}

// Mutate applies the CreateOrderInput on the OrderMutation builder.
func (i *CreateOrderInput) Mutate(m *OrderMutation) {
	if i.Status != nil {
		m.SetStatus(*i.Status)
	}
	m.SetCustomerID(i.CustomerID)
	if len(i.ItemIDs) > 0 {
		m.AddItemIDs(i.ItemIDs...)
	}
}

// SetInput applies the change-set in the CreateOrderInput on the OrderCreate builder.
func (c *OrderCreate) SetInput(i CreateOrderInput) *OrderCreate {
	i.Mutate(c.Mutation())
	return c
}

// UpdateOrderInput represents a mutation input for updating orders.
type UpdateOrderInput struct {
	Status        *order.Status `json:"status,omitempty"`
	CustomerID    *int          `json:"customerID,omitempty"`
	ClearItems    bool          `json:"clearItems,omitempty"`
	AddItemIDs    []int         `json:"addItemIDs,omitempty"`
	RemoveItemIDs []int         `json:"removeItemIDs,omitempty"`
}

// Mutate applies the UpdateOrderInput on the OrderMutation builder.
func (i *UpdateOrderInput) Mutate(m *OrderMutation) {
	if i.Status != nil {
		m.SetStatus(*i.Status)
	}
	if i.CustomerID != nil {
		m.SetCustomerID(*i.CustomerID)
	}
	if i.ClearItems {
		m.ClearItems()
	}
	if len(i.AddItemIDs) > 0 {
		m.AddItemIDs(i.AddItemIDs...)
	}
	if len(i.RemoveItemIDs) > 0 {
		m.RemoveItemIDs(i.RemoveItemIDs...)
	}
}

// SetInput applies the change-set in the UpdateOrderInput on the OrderUpdate builder.
func (c *OrderUpdate) SetInput(i UpdateOrderInput) *OrderUpdate {
	i.Mutate(c.Mutation())
	return c
}

// SetInput applies the change-set in the UpdateOrderInput on the OrderUpdateOne builder.
func (c *OrderUpdateOne) SetInput(i UpdateOrderInput) *OrderUpdateOne {
	i.Mutate(c.Mutation())
	return c
}
