// Code generated by velox. DO NOT EDIT.

package orderclient

import (
	"context"
	"fmt"
	"time"

	entity "github.com/syssam/graphql-go/examples/veloxfx/velox/entity"
	order "github.com/syssam/graphql-go/examples/veloxfx/velox/order"
	predicate "github.com/syssam/graphql-go/examples/veloxfx/velox/predicate"
	velox "github.com/syssam/velox"
	sql "github.com/syssam/velox/dialect/sql"
	runtime "github.com/syssam/velox/runtime"
)

// OrderMutation represents an operation that mutates the Order nodes in the graph.
type OrderMutation struct {
	config           runtime.Config
	op               runtime.Op
	id               *int
	_created_at      *time.Time
	_updated_at      *time.Time
	_status          *order.Status
	clearedFields    map[string]struct{}
	oldValue         func(context.Context) (*entity.Order, error)
	oldLoaded        bool
	oldCache         *entity.Order
	done             bool
	customer         map[int]struct{}
	removedCustomer  map[int]struct{}
	clearedCustomer  bool
	warehouse        map[int]struct{}
	removedWarehouse map[int]struct{}
	clearedWarehouse bool
	items            map[int]struct{}
	removedItems     map[int]struct{}
	clearedItems     bool
	predicates       []predicate.Order
}

var _ velox.Mutation = (*OrderMutation)(nil)

// orderOption allows management of the mutation configuration using functional options.
type orderOption func(*OrderMutation)

// NewOrderMutation creates new mutation for the Order entity.
func NewOrderMutation(c runtime.Config, op runtime.Op, opts ...orderOption) *OrderMutation {
	m := &OrderMutation{
		config: c,
		op:     runtime.Op(op),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// Op returns the operation name.
func (m *OrderMutation) Op() runtime.Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *OrderMutation) SetOp(op runtime.Op) {
	m.op = op
}

// Type returns the schema type name of this mutation ("Order").
func (m *OrderMutation) Type() string {
	return "Order"
}

// ID returns the ID value in the mutation, if it was provided by the caller.
// The second bool return indicates whether the ID field was set.
func (m *OrderMutation) ID() (id any, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetID sets the entity ID value on the mutation.
func (m *OrderMutation) SetID(id int) {
	m.id = &id
}

// loadOld lazily loads the pre-mutation entity state for OldXxx methods.
func (m *OrderMutation) loadOld(ctx context.Context) (*entity.Order, error) {
	if m.op != runtime.OpUpdateOne {
		return nil, fmt.Errorf("OldField is only allowed on UpdateOne operations")
	}
	if m.oldValue == nil {
		return nil, fmt.Errorf("OldField is not supported: no old value loader configured")
	}
	if m.oldLoaded {
		return m.oldCache, nil
	}
	if m.done {
		return nil, fmt.Errorf("%w: call Order.OldXxx in the hook before next.Mutate", runtime.ErrOldValueAfterMutation)
	}
	old, err := m.oldValue(ctx)
	if err != nil {
		return nil, fmt.Errorf("querying old values: %w", err)
	}
	m.oldCache = old
	m.oldLoaded = true
	return old, nil
}

// Where appends a list predicates to the OrderMutation builder.
func (m *OrderMutation) Where(ps ...predicate.Order) {
	m.predicates = append(m.predicates, ps...)
}

// PredicatesFuncs returns the predicates as untyped selector functions.
func (m *OrderMutation) PredicatesFuncs() []func(*sql.Selector) {
	ps := make([]func(*sql.Selector), len(m.predicates))
	for i, p := range m.predicates {
		ps[i] = p
	}
	return ps
}

// SetCreatedAt sets the "created_at" field.
func (m *OrderMutation) SetCreatedAt(v time.Time) {
	m._created_at = &v
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *OrderMutation) CreatedAt() (r time.Time, exists bool) {
	if m._created_at == nil {
		return
	}
	return *m._created_at, true
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *OrderMutation) ResetCreatedAt() {
	m._created_at = nil
	delete(m.clearedFields, "created_at")
}

// SetUpdatedAt sets the "updated_at" field.
func (m *OrderMutation) SetUpdatedAt(v time.Time) {
	m._updated_at = &v
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *OrderMutation) UpdatedAt() (r time.Time, exists bool) {
	if m._updated_at == nil {
		return
	}
	return *m._updated_at, true
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *OrderMutation) ResetUpdatedAt() {
	m._updated_at = nil
	delete(m.clearedFields, "updated_at")
}

// SetStatus sets the "status" field.
func (m *OrderMutation) SetStatus(v order.Status) {
	m._status = &v
}

// Status returns the value of the "status" field in the mutation.
func (m *OrderMutation) Status() (r order.Status, exists bool) {
	if m._status == nil {
		return
	}
	return *m._status, true
}

// ResetStatus resets all changes to the "status" field.
func (m *OrderMutation) ResetStatus() {
	m._status = nil
	delete(m.clearedFields, "status")
}

// SetCustomerID sets the "customer" edge to the Customer entity by id.
func (m *OrderMutation) SetCustomerID(id int) {
	m.customer = map[int]struct{}{id: {}}
}

// ClearCustomer clears the "customer" edge.
func (m *OrderMutation) ClearCustomer() {
	m.clearedCustomer = true
}

// CustomerCleared reports if the "customer" edge was cleared.
func (m *OrderMutation) CustomerCleared() bool {
	return m.clearedCustomer
}

// ResetCustomer resets all changes to the "customer" edge.
func (m *OrderMutation) ResetCustomer() {
	m.customer = nil
	m.clearedCustomer = false
	m.removedCustomer = nil
}

// CustomerIDs returns the "customer" edge IDs in the mutation.
func (m *OrderMutation) CustomerIDs() (ids []int) {
	for id := range m.customer {
		ids = append(ids, id)
	}
	return
}

// SetWarehouseID sets the "warehouse" edge to the Warehouse entity by id.
func (m *OrderMutation) SetWarehouseID(id int) {
	m.warehouse = map[int]struct{}{id: {}}
}

// ClearWarehouse clears the "warehouse" edge.
func (m *OrderMutation) ClearWarehouse() {
	m.clearedWarehouse = true
}

// WarehouseCleared reports if the "warehouse" edge was cleared.
func (m *OrderMutation) WarehouseCleared() bool {
	return m.clearedWarehouse
}

// ResetWarehouse resets all changes to the "warehouse" edge.
func (m *OrderMutation) ResetWarehouse() {
	m.warehouse = nil
	m.clearedWarehouse = false
	m.removedWarehouse = nil
}

// WarehouseIDs returns the "warehouse" edge IDs in the mutation.
func (m *OrderMutation) WarehouseIDs() (ids []int) {
	for id := range m.warehouse {
		ids = append(ids, id)
	}
	return
}

// AddItemIDs adds the "items" edge to the OrderItem entity by ids.
func (m *OrderMutation) AddItemIDs(ids ...int) {
	if m.items == nil {
		m.items = make(map[int]struct{})
	}
	for _, id := range ids {
		m.items[id] = struct{}{}
	}
}

// RemoveItemIDs removes the "items" edge to the OrderItem entity by ids.
func (m *OrderMutation) RemoveItemIDs(ids ...int) {
	if m.removedItems == nil {
		m.removedItems = make(map[int]struct{})
	}
	for _, id := range ids {
		delete(m.items, id)
		m.removedItems[id] = struct{}{}
	}
}

// ClearItems clears the "items" edge.
func (m *OrderMutation) ClearItems() {
	m.clearedItems = true
}

// ItemsCleared reports if the "items" edge was cleared.
func (m *OrderMutation) ItemsCleared() bool {
	return m.clearedItems
}

// RemovedItemsIDs returns the removed IDs of the "items" edge.
func (m *OrderMutation) RemovedItemsIDs() (ids []int) {
	for id := range m.removedItems {
		ids = append(ids, id)
	}
	return
}

// ResetItems resets all changes to the "items" edge.
func (m *OrderMutation) ResetItems() {
	m.items = nil
	m.clearedItems = false
	m.removedItems = nil
}

// ItemsIDs returns the "items" edge IDs in the mutation.
func (m *OrderMutation) ItemsIDs() (ids []int) {
	for id := range m.items {
		ids = append(ids, id)
	}
	return
}

// Fields returns all fields that were changed during this mutation.
func (m *OrderMutation) Fields() []string {
	var fields []string
	if m._created_at != nil {
		fields = append(fields, "created_at")
	}
	if m._updated_at != nil {
		fields = append(fields, "updated_at")
	}
	if m._status != nil {
		fields = append(fields, "status")
	}
	return fields
}

// Field returns the value of a field with the given name.
func (m *OrderMutation) Field(name string) (runtime.Value, bool) {
	switch name {
	case "created_at":
		if m._created_at != nil {
			return *m._created_at, true
		}
	case "updated_at":
		if m._updated_at != nil {
			return *m._updated_at, true
		}
	case "status":
		if m._status != nil {
			return *m._status, true
		}
	}
	return nil, false
}

// SetField sets the value of a field with the given name. It returns an error if the field is not defined in the schema, or if the value type does not match.
func (m *OrderMutation) SetField(name string, value runtime.Value) error {
	switch name {
	case "created_at":
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field created_at", value)
		}
		m.SetCreatedAt(v)
		return nil
	case "updated_at":
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field updated_at", value)
		}
		m.SetUpdatedAt(v)
		return nil
	case "status":
		v, ok := value.(order.Status)
		if !ok {
			return fmt.Errorf("unexpected type %T for field status", value)
		}
		m.SetStatus(v)
		return nil
	default:
		return fmt.Errorf("unknown Order field %s", name)
	}
}

// AddedFields returns all numeric fields that were incremented or decremented during this mutation.
func (m *OrderMutation) AddedFields() []string {
	var fields []string
	return fields
}

// AddedField returns the numeric value that was incremented or decremented for a field.
func (m *OrderMutation) AddedField(name string) (runtime.Value, bool) {
	switch name {
	}
	return nil, false
}

// AddField adds the value for the given name. It returns an error if the field is not defined in the schema, or if the value type does not match.
func (m *OrderMutation) AddField(name string, value runtime.Value) error {
	switch name {
	default:
		return fmt.Errorf("unknown Order addable field %s", name)
	}
}

// ClearedFields returns all fields that were cleared during this mutation.
func (m *OrderMutation) ClearedFields() []string {
	var fields []string
	for f := range m.clearedFields {
		fields = append(fields, f)
	}
	return fields
}

// FieldCleared reports if a field with the given name was cleared in this mutation.
func (m *OrderMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an error if the field is not defined in the schema or is not nullable.
func (m *OrderMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Order nullable field %s", name)
}

// ResetField resets all changes for the field with the given name. It returns an error if the field is not defined in the schema.
func (m *OrderMutation) ResetField(name string) error {
	switch name {
	case "created_at":
		m._created_at = nil
		delete(m.clearedFields, "created_at")
	case "updated_at":
		m._updated_at = nil
		delete(m.clearedFields, "updated_at")
	case "status":
		m._status = nil
		delete(m.clearedFields, "status")
	default:
		return fmt.Errorf("unknown Order field %s", name)
	}
	return nil
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *OrderMutation) AddedEdges() []string {
	edges := make([]string, 0, 3)
	if m.customer != nil {
		edges = append(edges, "customer")
	}
	if m.warehouse != nil {
		edges = append(edges, "warehouse")
	}
	if m.items != nil {
		edges = append(edges, "items")
	}
	return edges
}

// AddedIDs returns all IDs that were added for the given edge name.
func (m *OrderMutation) AddedIDs(name string) []velox.Value {
	switch name {
	case "customer":
		ids := make([]velox.Value, 0, len(m.customer))
		for id := range m.customer {
			ids = append(ids, id)
		}
		return ids
	case "warehouse":
		ids := make([]velox.Value, 0, len(m.warehouse))
		for id := range m.warehouse {
			ids = append(ids, id)
		}
		return ids
	case "items":
		ids := make([]velox.Value, 0, len(m.items))
		for id := range m.items {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *OrderMutation) RemovedEdges() []string {
	edges := make([]string, 0, 3)
	if m.removedCustomer != nil {
		edges = append(edges, "customer")
	}
	if m.removedWarehouse != nil {
		edges = append(edges, "warehouse")
	}
	if m.removedItems != nil {
		edges = append(edges, "items")
	}
	return edges
}

// RemovedIDs returns all IDs that were removed for the given edge name.
func (m *OrderMutation) RemovedIDs(name string) []velox.Value {
	switch name {
	case "customer":
		ids := make([]velox.Value, 0, len(m.removedCustomer))
		for id := range m.removedCustomer {
			ids = append(ids, id)
		}
		return ids
	case "warehouse":
		ids := make([]velox.Value, 0, len(m.removedWarehouse))
		for id := range m.removedWarehouse {
			ids = append(ids, id)
		}
		return ids
	case "items":
		ids := make([]velox.Value, 0, len(m.removedItems))
		for id := range m.removedItems {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *OrderMutation) ClearedEdges() []string {
	edges := make([]string, 0, 3)
	if m.clearedCustomer {
		edges = append(edges, "customer")
	}
	if m.clearedWarehouse {
		edges = append(edges, "warehouse")
	}
	if m.clearedItems {
		edges = append(edges, "items")
	}
	return edges
}

// EdgeCleared reports if the given edge was cleared in this mutation.
func (m *OrderMutation) EdgeCleared(name string) bool {
	switch name {
	case "customer":
		return m.clearedCustomer
	case "warehouse":
		return m.clearedWarehouse
	case "items":
		return m.clearedItems
	}
	return false
}

// ClearEdge clears the value of the edge with the given name.
func (m *OrderMutation) ClearEdge(name string) error {
	switch name {
	case "customer":
		m.ClearCustomer()
		return nil
	case "warehouse":
		m.ClearWarehouse()
		return nil
	case "items":
		m.ClearItems()
		return nil
	}
	return fmt.Errorf("unknown Order edge %s", name)
}

// ResetEdge resets all changes for the edge with the given name.
func (m *OrderMutation) ResetEdge(name string) error {
	switch name {
	case "customer":
		m.ResetCustomer()
		return nil
	case "warehouse":
		m.ResetWarehouse()
		return nil
	case "items":
		m.ResetItems()
		return nil
	}
	return fmt.Errorf("unknown Order edge %s", name)
}

// OldField returns the old value of a field from the database.
// An error is returned if the mutation operation is not UpdateOne,
// or the query to the database fails.
func (m *OrderMutation) OldField(ctx context.Context, name string) (velox.Value, error) {
	switch name {
	case "created_at":
		return m.OldCreatedAt(ctx)
	case "updated_at":
		return m.OldUpdatedAt(ctx)
	case "status":
		return m.OldStatus(ctx)
	}
	return nil, fmt.Errorf("unknown Order field %s", name)
}

// OldCreatedAt returns the old "created_at" field value, if exists.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OrderMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	old, loadErr := m.loadOld(ctx)
	if loadErr != nil {
		err = loadErr
		return
	}
	v = old.CreatedAt
	return
}

// OldUpdatedAt returns the old "updated_at" field value, if exists.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OrderMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	old, loadErr := m.loadOld(ctx)
	if loadErr != nil {
		err = loadErr
		return
	}
	v = old.UpdatedAt
	return
}

// OldStatus returns the old "status" field value, if exists.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OrderMutation) OldStatus(ctx context.Context) (v order.Status, err error) {
	old, loadErr := m.loadOld(ctx)
	if loadErr != nil {
		err = loadErr
		return
	}
	v = old.Status
	return
}
