// Code generated by velox. DO NOT EDIT.

package velox

const (
	Version  = "v0.3.1-0.20260926152214-367e7ed10924"            // Version of velox codegen.
	Checksum = "h1:rQLDITJ+oNbeyYcq81wx8PFr6xko0pVW3bKW6b76jkQ=" // go.sum checksum of the velox module used for codegen.
)
