// Code generated by gqlc. DO NOT EDIT.

// Package graph wires the generated GraphQL schema and its bindings.
package graph

import (
	"context"
	"embed"

	"github.com/syssam/graphql-go"
	"github.com/syssam/graphql-go/examples/veloxfx/graph/category"
	"github.com/syssam/graphql-go/examples/veloxfx/graph/customer"
	"github.com/syssam/graphql-go/examples/veloxfx/graph/order"
	"github.com/syssam/graphql-go/examples/veloxfx/graph/orderitem"
	"github.com/syssam/graphql-go/examples/veloxfx/graph/product"
	"github.com/syssam/graphql-go/examples/veloxfx/graph/root"
	"github.com/syssam/graphql-go/examples/veloxfx/graph/stock"
	"github.com/syssam/graphql-go/examples/veloxfx/graph/warehouse"
	"github.com/syssam/graphql-go/fed"
)

//go:embed schema/*.graphql
var sdl embed.FS

// NewSchema builds the schema from the embedded SDL and the bindings given.
// Pass each group's bindings over its Resolver, as a gRPC server registers
// each service:
//
//	graph.NewSchema(user.Bindings(userResolver), post.Bindings(postResolver))
//
// A group that is not passed leaves its fields unbound, which NewSchema
// reports. Groups with no Resolver are included already.
//
// The schema is an Apollo Federation subgraph: entities resolves each @key
// type the router reaches through _entities, and _service returns the
// embedded SDL.
func NewSchema(entities []fed.Entity, opts ...graphql.SchemaOption) (*graphql.Schema, error) {
	src, subgraph, err := fed.SubgraphFS(sdl, []string{"schema/*.graphql"}, entities...)
	if err != nil {
		return nil, err
	}
	all := []graphql.SchemaOption{
		subgraph,
		root.Bindings(),
	}
	all = append(all, opts...)
	return graphql.NewSchema(src, all...)
}

// ValidateSchema builds the schema with no resolver behind it, so every
// binding error surfaces before a resolver is written. Building never calls a
// resolver -- Resolve captures it in a closure -- so a nil one is enough.
func ValidateSchema(opts ...graphql.SchemaOption) error {
	all := []graphql.SchemaOption{
		category.Bindings(nil),
		customer.Bindings(nil),
		order.Bindings(nil),
		orderitem.Bindings(nil),
		product.Bindings(nil),
		stock.Bindings(nil),
		warehouse.Bindings(nil),
	}
	_, err := NewSchema(placeholderEntities(), append(all, opts...)...)
	return err
}

// placeholderEntities stands in for every @key type's resolver in
// ValidateSchema, which builds the schema and resolves nothing.
func placeholderEntities() []fed.Entity {
	none := func(context.Context, fed.Representation) (*struct{}, error) { return nil, nil }
	return []fed.Entity{
		fed.Resolver("Customer", none),
		fed.Resolver("Order", none),
		fed.Resolver("Product", none),
	}
}
