// Code generated by gqlc. DO NOT EDIT.

// Package graph wires the generated GraphQL schema and its bindings.
package graph

import (
	"embed"

	"github.com/syssam/graphql-go"
	"github.com/syssam/graphql-go/examples/veloxfx/graph/category"
	"github.com/syssam/graphql-go/examples/veloxfx/graph/customer"
	"github.com/syssam/graphql-go/examples/veloxfx/graph/order"
	"github.com/syssam/graphql-go/examples/veloxfx/graph/orderitem"
	"github.com/syssam/graphql-go/examples/veloxfx/graph/product"
	"github.com/syssam/graphql-go/examples/veloxfx/graph/root"
	"github.com/syssam/graphql-go/examples/veloxfx/graph/stock"
	"github.com/syssam/graphql-go/examples/veloxfx/graph/warehouse"
)

//go:embed schema/*.graphql
var sdl embed.FS

// NewSchema builds the schema from the embedded SDL and the bindings given.
// Pass each group's bindings over its Resolver, as a gRPC server registers
// each service:
//
//	graph.NewSchema(user.Bindings(userResolver), post.Bindings(postResolver))
//
// A group that is not passed leaves its fields unbound, which NewSchema
// reports. Groups with no Resolver are included already.
func NewSchema(opts ...graphql.SchemaOption) (*graphql.Schema, error) {
	all := []graphql.SchemaOption{
		root.Bindings(),
	}
	all = append(all, opts...)
	return graphql.NewSchema(graphql.SDLFS(sdl, "schema/*.graphql"), all...)
}

// ValidateSchema builds the schema with no resolver behind it, so every
// binding error surfaces before a resolver is written. Building never calls a
// resolver -- Resolve captures it in a closure -- so a nil one is enough.
func ValidateSchema(opts ...graphql.SchemaOption) error {
	all := []graphql.SchemaOption{
		category.Bindings(nil),
		customer.Bindings(nil),
		order.Bindings(nil),
		orderitem.Bindings(nil),
		product.Bindings(nil),
		stock.Bindings(nil),
		warehouse.Bindings(nil),
	}
	_, err := NewSchema(append(all, opts...)...)
	return err
}
