// Code generated by gqlc. DO NOT EDIT.

// Package root holds the types generated from the GraphQL schema.
package root

type OrderDirection string

const (
	OrderDirectionAsc  OrderDirection = "ASC"
	OrderDirectionDesc OrderDirection = "DESC"
)
