// Code generated by velox. DO NOT EDIT.

package productclient

// CreateProductInput represents a mutation input for creating products.
type CreateProductInput struct {
	Sku        string `json:"sku"`
	Name       string `json:"name"`
	PriceCents int    `json:"priceCents"`
	CategoryID int    `json:"categoryID"`
}

// Mutate applies the CreateProductInput on the ProductMutation builder.
func (i *CreateProductInput) Mutate(m *ProductMutation) {
	m.SetSku(i.Sku)
	m.SetName(i.Name)
	m.SetPriceCents(i.PriceCents)
	m.SetCategoryID(i.CategoryID)
}

// SetInput applies the change-set in the CreateProductInput on the ProductCreate builder.
func (c *ProductCreate) SetInput(i CreateProductInput) *ProductCreate {
	i.Mutate(c.Mutation())
	return c
}

// UpdateProductInput represents a mutation input for updating products.
type UpdateProductInput struct {
	Sku        *string `json:"sku,omitempty"`
	Name       *string `json:"name,omitempty"`
	PriceCents *int    `json:"priceCents,omitempty"`
	CategoryID *int    `json:"categoryID,omitempty"`
}

// Mutate applies the UpdateProductInput on the ProductMutation builder.
func (i *UpdateProductInput) Mutate(m *ProductMutation) {
	if i.Sku != nil {
		m.SetSku(*i.Sku)
	}
	if i.Name != nil {
		m.SetName(*i.Name)
	}
	if i.PriceCents != nil {
		m.SetPriceCents(*i.PriceCents)
	}
	if i.CategoryID != nil {
		m.SetCategoryID(*i.CategoryID)
	}
}

// SetInput applies the change-set in the UpdateProductInput on the ProductUpdate builder.
func (c *ProductUpdate) SetInput(i UpdateProductInput) *ProductUpdate {
	i.Mutate(c.Mutation())
	return c
}

// SetInput applies the change-set in the UpdateProductInput on the ProductUpdateOne builder.
func (c *ProductUpdateOne) SetInput(i UpdateProductInput) *ProductUpdateOne {
	i.Mutate(c.Mutation())
	return c
}
