// Code generated by velox. DO NOT EDIT.

package productclient

import (
	"context"
	"fmt"

	entity "github.com/syssam/graphql-go/examples/veloxfx/velox/entity"
	predicate "github.com/syssam/graphql-go/examples/veloxfx/velox/predicate"
	velox "github.com/syssam/velox"
	sql "github.com/syssam/velox/dialect/sql"
	runtime "github.com/syssam/velox/runtime"
)

// ProductMutation represents an operation that mutates the Product nodes in the graph.
type ProductMutation struct {
	config            runtime.Config
	op                runtime.Op
	id                *int
	_sku              *string
	_name             *string
	_price_cents      *int
	_addprice_cents   *int
	clearedFields     map[string]struct{}
	oldValue          func(context.Context) (*entity.Product, error)
	oldLoaded         bool
	oldCache          *entity.Product
	done              bool
	category          map[int]struct{}
	removedCategory   map[int]struct{}
	clearedCategory   bool
	stocks            map[int]struct{}
	removedStocks     map[int]struct{}
	clearedStocks     bool
	order_items       map[int]struct{}
	removedOrderItems map[int]struct{}
	clearedOrderItems bool
	predicates        []predicate.Product
}

var _ velox.Mutation = (*ProductMutation)(nil)

// productOption allows management of the mutation configuration using functional options.
type productOption func(*ProductMutation)

// NewProductMutation creates new mutation for the Product entity.
func NewProductMutation(c runtime.Config, op runtime.Op, opts ...productOption) *ProductMutation {
	m := &ProductMutation{
		config: c,
		op:     runtime.Op(op),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// Op returns the operation name.
func (m *ProductMutation) Op() runtime.Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ProductMutation) SetOp(op runtime.Op) {
	m.op = op
}

// Type returns the schema type name of this mutation ("Product").
func (m *ProductMutation) Type() string {
	return "Product"
}

// ID returns the ID value in the mutation, if it was provided by the caller.
// The second bool return indicates whether the ID field was set.
func (m *ProductMutation) ID() (id any, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetID sets the entity ID value on the mutation.
func (m *ProductMutation) SetID(id int) {
	m.id = &id
}

// loadOld lazily loads the pre-mutation entity state for OldXxx methods.
func (m *ProductMutation) loadOld(ctx context.Context) (*entity.Product, error) {
	if m.op != runtime.OpUpdateOne {
		return nil, fmt.Errorf("OldField is only allowed on UpdateOne operations")
	}
	if m.oldValue == nil {
		return nil, fmt.Errorf("OldField is not supported: no old value loader configured")
	}
	if m.oldLoaded {
		return m.oldCache, nil
	}
	if m.done {
		return nil, fmt.Errorf("%w: call Product.OldXxx in the hook before next.Mutate", runtime.ErrOldValueAfterMutation)
	}
	old, err := m.oldValue(ctx)
	if err != nil {
		return nil, fmt.Errorf("querying old values: %w", err)
	}
	m.oldCache = old
	m.oldLoaded = true
	return old, nil
}

// Where appends a list predicates to the ProductMutation builder.
func (m *ProductMutation) Where(ps ...predicate.Product) {
	m.predicates = append(m.predicates, ps...)
}

// PredicatesFuncs returns the predicates as untyped selector functions.
func (m *ProductMutation) PredicatesFuncs() []func(*sql.Selector) {
	ps := make([]func(*sql.Selector), len(m.predicates))
	for i, p := range m.predicates {
		ps[i] = p
	}
	return ps
}

// SetSku sets the "sku" field.
func (m *ProductMutation) SetSku(v string) {
	m._sku = &v
}

// Sku returns the value of the "sku" field in the mutation.
func (m *ProductMutation) Sku() (r string, exists bool) {
	if m._sku == nil {
		return
	}
	return *m._sku, true
}

// ResetSku resets all changes to the "sku" field.
func (m *ProductMutation) ResetSku() {
	m._sku = nil
	delete(m.clearedFields, "sku")
}

// SetName sets the "name" field.
func (m *ProductMutation) SetName(v string) {
	m._name = &v
}

// Name returns the value of the "name" field in the mutation.
func (m *ProductMutation) Name() (r string, exists bool) {
	if m._name == nil {
		return
	}
	return *m._name, true
}

// ResetName resets all changes to the "name" field.
func (m *ProductMutation) ResetName() {
	m._name = nil
	delete(m.clearedFields, "name")
}

// SetPriceCents sets the "price_cents" field.
func (m *ProductMutation) SetPriceCents(v int) {
	m._price_cents = &v
	m._addprice_cents = nil
}

// PriceCents returns the value of the "price_cents" field in the mutation.
func (m *ProductMutation) PriceCents() (r int, exists bool) {
	if m._price_cents == nil {
		return
	}
	return *m._price_cents, true
}

// AddPriceCents adds v to the "price_cents" field.
func (m *ProductMutation) AddPriceCents(v int) {
	if m._addprice_cents != nil {
		*m._addprice_cents += v
	} else {
		m._addprice_cents = &v
	}
}

// AddedPriceCents returns the value that was added to the "price_cents" field in this mutation.
func (m *ProductMutation) AddedPriceCents() (r int, exists bool) {
	if m._addprice_cents == nil {
		return
	}
	return *m._addprice_cents, true
}

// ResetPriceCents resets all changes to the "price_cents" field.
func (m *ProductMutation) ResetPriceCents() {
	m._price_cents = nil
	m._addprice_cents = nil
	delete(m.clearedFields, "price_cents")
}

// SetCategoryID sets the "category" edge to the Category entity by id.
func (m *ProductMutation) SetCategoryID(id int) {
	m.category = map[int]struct{}{id: {}}
}

// ClearCategory clears the "category" edge.
func (m *ProductMutation) ClearCategory() {
	m.clearedCategory = true
}

// CategoryCleared reports if the "category" edge was cleared.
func (m *ProductMutation) CategoryCleared() bool {
	return m.clearedCategory
}

// ResetCategory resets all changes to the "category" edge.
func (m *ProductMutation) ResetCategory() {
	m.category = nil
	m.clearedCategory = false
	m.removedCategory = nil
}

// CategoryIDs returns the "category" edge IDs in the mutation.
func (m *ProductMutation) CategoryIDs() (ids []int) {
	for id := range m.category {
		ids = append(ids, id)
	}
	return
}

// AddStockIDs adds the "stocks" edge to the Stock entity by ids.
func (m *ProductMutation) AddStockIDs(ids ...int) {
	if m.stocks == nil {
		m.stocks = make(map[int]struct{})
	}
	for _, id := range ids {
		m.stocks[id] = struct{}{}
	}
}

// RemoveStockIDs removes the "stocks" edge to the Stock entity by ids.
func (m *ProductMutation) RemoveStockIDs(ids ...int) {
	if m.removedStocks == nil {
		m.removedStocks = make(map[int]struct{})
	}
	for _, id := range ids {
		delete(m.stocks, id)
		m.removedStocks[id] = struct{}{}
	}
}

// ClearStocks clears the "stocks" edge.
func (m *ProductMutation) ClearStocks() {
	m.clearedStocks = true
}

// StocksCleared reports if the "stocks" edge was cleared.
func (m *ProductMutation) StocksCleared() bool {
	return m.clearedStocks
}

// RemovedStocksIDs returns the removed IDs of the "stocks" edge.
func (m *ProductMutation) RemovedStocksIDs() (ids []int) {
	for id := range m.removedStocks {
		ids = append(ids, id)
	}
	return
}

// ResetStocks resets all changes to the "stocks" edge.
func (m *ProductMutation) ResetStocks() {
	m.stocks = nil
	m.clearedStocks = false
	m.removedStocks = nil
}

// StocksIDs returns the "stocks" edge IDs in the mutation.
func (m *ProductMutation) StocksIDs() (ids []int) {
	for id := range m.stocks {
		ids = append(ids, id)
	}
	return
}

// AddOrderItemIDs adds the "order_items" edge to the OrderItem entity by ids.
func (m *ProductMutation) AddOrderItemIDs(ids ...int) {
	if m.order_items == nil {
		m.order_items = make(map[int]struct{})
	}
	for _, id := range ids {
		m.order_items[id] = struct{}{}
	}
}

// RemoveOrderItemIDs removes the "order_items" edge to the OrderItem entity by ids.
func (m *ProductMutation) RemoveOrderItemIDs(ids ...int) {
	if m.removedOrderItems == nil {
		m.removedOrderItems = make(map[int]struct{})
	}
	for _, id := range ids {
		delete(m.order_items, id)
		m.removedOrderItems[id] = struct{}{}
	}
}

// ClearOrderItems clears the "order_items" edge.
func (m *ProductMutation) ClearOrderItems() {
	m.clearedOrderItems = true
}

// OrderItemsCleared reports if the "order_items" edge was cleared.
func (m *ProductMutation) OrderItemsCleared() bool {
	return m.clearedOrderItems
}

// RemovedOrderItemsIDs returns the removed IDs of the "order_items" edge.
func (m *ProductMutation) RemovedOrderItemsIDs() (ids []int) {
	for id := range m.removedOrderItems {
		ids = append(ids, id)
	}
	return
}

// ResetOrderItems resets all changes to the "order_items" edge.
func (m *ProductMutation) ResetOrderItems() {
	m.order_items = nil
	m.clearedOrderItems = false
	m.removedOrderItems = nil
}

// OrderItemsIDs returns the "order_items" edge IDs in the mutation.
func (m *ProductMutation) OrderItemsIDs() (ids []int) {
	for id := range m.order_items {
		ids = append(ids, id)
	}
	return
}

// Fields returns all fields that were changed during this mutation.
func (m *ProductMutation) Fields() []string {
	var fields []string
	if m._sku != nil {
		fields = append(fields, "sku")
	}
	if m._name != nil {
		fields = append(fields, "name")
	}
	if m._price_cents != nil {
		fields = append(fields, "price_cents")
	}
	return fields
}

// Field returns the value of a field with the given name.
func (m *ProductMutation) Field(name string) (runtime.Value, bool) {
	switch name {
	case "sku":
		if m._sku != nil {
			return *m._sku, true
		}
	case "name":
		if m._name != nil {
			return *m._name, true
		}
	case "price_cents":
		if m._price_cents != nil {
			return *m._price_cents, true
		}
	}
	return nil, false
}

// SetField sets the value of a field with the given name. It returns an error if the field is not defined in the schema, or if the value type does not match.
func (m *ProductMutation) SetField(name string, value runtime.Value) error {
	switch name {
	case "sku":
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field sku", value)
		}
		m.SetSku(v)
		return nil
	case "name":
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field name", value)
		}
		m.SetName(v)
		return nil
	case "price_cents":
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field price_cents", value)
		}
		m.SetPriceCents(v)
		return nil
	default:
		return fmt.Errorf("unknown Product field %s", name)
	}
}

// AddedFields returns all numeric fields that were incremented or decremented during this mutation.
func (m *ProductMutation) AddedFields() []string {
	var fields []string
	if m._addprice_cents != nil {
		fields = append(fields, "price_cents")
	}
	return fields
}

// AddedField returns the numeric value that was incremented or decremented for a field.
func (m *ProductMutation) AddedField(name string) (runtime.Value, bool) {
	switch name {
	case "price_cents":
		if m._addprice_cents != nil {
			return *m._addprice_cents, true
		}
	}
	return nil, false
}

// AddField adds the value for the given name. It returns an error if the field is not defined in the schema, or if the value type does not match.
func (m *ProductMutation) AddField(name string, value runtime.Value) error {
	switch name {
	case "price_cents":
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field price_cents", value)
		}
		m.AddPriceCents(v)
		return nil
	default:
		return fmt.Errorf("unknown Product addable field %s", name)
	}
}

// ClearedFields returns all fields that were cleared during this mutation.
func (m *ProductMutation) ClearedFields() []string {
	var fields []string
	for f := range m.clearedFields {
		fields = append(fields, f)
	}
	return fields
}

// FieldCleared reports if a field with the given name was cleared in this mutation.
func (m *ProductMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an error if the field is not defined in the schema or is not nullable.
func (m *ProductMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Product nullable field %s", name)
}

// ResetField resets all changes for the field with the given name. It returns an error if the field is not defined in the schema.
func (m *ProductMutation) ResetField(name string) error {
	switch name {
	case "sku":
		m._sku = nil
		delete(m.clearedFields, "sku")
	case "name":
		m._name = nil
		delete(m.clearedFields, "name")
	case "price_cents":
		m._price_cents = nil
		m._addprice_cents = nil
		delete(m.clearedFields, "price_cents")
	default:
		return fmt.Errorf("unknown Product field %s", name)
	}
	return nil
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ProductMutation) AddedEdges() []string {
	edges := make([]string, 0, 3)
	if m.category != nil {
		edges = append(edges, "category")
	}
	if m.stocks != nil {
		edges = append(edges, "stocks")
	}
	if m.order_items != nil {
		edges = append(edges, "order_items")
	}
	return edges
}

// AddedIDs returns all IDs that were added for the given edge name.
func (m *ProductMutation) AddedIDs(name string) []velox.Value {
	switch name {
	case "category":
		ids := make([]velox.Value, 0, len(m.category))
		for id := range m.category {
			ids = append(ids, id)
		}
		return ids
	case "stocks":
		ids := make([]velox.Value, 0, len(m.stocks))
		for id := range m.stocks {
			ids = append(ids, id)
		}
		return ids
	case "order_items":
		ids := make([]velox.Value, 0, len(m.order_items))
		for id := range m.order_items {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ProductMutation) RemovedEdges() []string {
	edges := make([]string, 0, 3)
	if m.removedCategory != nil {
		edges = append(edges, "category")
	}
	if m.removedStocks != nil {
		edges = append(edges, "stocks")
	}
	if m.removedOrderItems != nil {
		edges = append(edges, "order_items")
	}
	return edges
}

// RemovedIDs returns all IDs that were removed for the given edge name.
func (m *ProductMutation) RemovedIDs(name string) []velox.Value {
	switch name {
	case "category":
		ids := make([]velox.Value, 0, len(m.removedCategory))
		for id := range m.removedCategory {
			ids = append(ids, id)
		}
		return ids
	case "stocks":
		ids := make([]velox.Value, 0, len(m.removedStocks))
		for id := range m.removedStocks {
			ids = append(ids, id)
		}
		return ids
	case "order_items":
		ids := make([]velox.Value, 0, len(m.removedOrderItems))
		for id := range m.removedOrderItems {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ProductMutation) ClearedEdges() []string {
	edges := make([]string, 0, 3)
	if m.clearedCategory {
		edges = append(edges, "category")
	}
	if m.clearedStocks {
		edges = append(edges, "stocks")
	}
	if m.clearedOrderItems {
		edges = append(edges, "order_items")
	}
	return edges
}

// EdgeCleared reports if the given edge was cleared in this mutation.
func (m *ProductMutation) EdgeCleared(name string) bool {
	switch name {
	case "category":
		return m.clearedCategory
	case "stocks":
		return m.clearedStocks
	case "order_items":
		return m.clearedOrderItems
	}
	return false
}

// ClearEdge clears the value of the edge with the given name.
func (m *ProductMutation) ClearEdge(name string) error {
	switch name {
	case "category":
		m.ClearCategory()
		return nil
	case "stocks":
		m.ClearStocks()
		return nil
	case "order_items":
		m.ClearOrderItems()
		return nil
	}
	return fmt.Errorf("unknown Product edge %s", name)
}

// ResetEdge resets all changes for the edge with the given name.
func (m *ProductMutation) ResetEdge(name string) error {
	switch name {
	case "category":
		m.ResetCategory()
		return nil
	case "stocks":
		m.ResetStocks()
		return nil
	case "order_items":
		m.ResetOrderItems()
		return nil
	}
	return fmt.Errorf("unknown Product edge %s", name)
}

// OldField returns the old value of a field from the database.
// An error is returned if the mutation operation is not UpdateOne,
// or the query to the database fails.
func (m *ProductMutation) OldField(ctx context.Context, name string) (velox.Value, error) {
	switch name {
	case "sku":
		return m.OldSku(ctx)
	case "name":
		return m.OldName(ctx)
	case "price_cents":
		return m.OldPriceCents(ctx)
	}
	return nil, fmt.Errorf("unknown Product field %s", name)
}

// OldSku returns the old "sku" field value, if exists.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProductMutation) OldSku(ctx context.Context) (v string, err error) {
	old, loadErr := m.loadOld(ctx)
	if loadErr != nil {
		err = loadErr
		return
	}
	v = old.Sku
	return
}

// OldName returns the old "name" field value, if exists.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProductMutation) OldName(ctx context.Context) (v string, err error) {
	old, loadErr := m.loadOld(ctx)
	if loadErr != nil {
		err = loadErr
		return
	}
	v = old.Name
	return
}

// OldPriceCents returns the old "price_cents" field value, if exists.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProductMutation) OldPriceCents(ctx context.Context) (v int, err error) {
	old, loadErr := m.loadOld(ctx)
	if loadErr != nil {
		err = loadErr
		return
	}
	v = old.PriceCents
	return
}
