// Code generated by velox. DO NOT EDIT.

package productclient

import (
	"context"
	"errors"
	"fmt"

	entity "github.com/syssam/graphql-go/examples/veloxfx/velox/entity"
	predicate "github.com/syssam/graphql-go/examples/veloxfx/velox/predicate"
	product "github.com/syssam/graphql-go/examples/veloxfx/velox/product"
	velox "github.com/syssam/velox"
	sql "github.com/syssam/velox/dialect/sql"
	sqlgraph "github.com/syssam/velox/dialect/sql/sqlgraph"
	runtime "github.com/syssam/velox/runtime"
	field "github.com/syssam/velox/schema/field"
)

// ProductUpdate is the update builder for Product entities.
//
// Query interceptors do NOT run on mutations. A row filter registered
// with Intercept() leaves this builder unscoped, so express row-level
// authorization as a schema Policy() — it covers reads and writes.
type ProductUpdate struct {
	config    runtime.Config
	mutation  *ProductMutation
	hooks     []runtime.Hook
	modifiers []func(*sql.UpdateBuilder)
}

// NewProductUpdate creates a new ProductUpdate builder.
func NewProductUpdate(c runtime.Config, mutation *ProductMutation, hooks []runtime.Hook) *ProductUpdate {
	return &ProductUpdate{
		config:   c,
		hooks:    hooks,
		mutation: mutation,
	}
}

// Where appends a list predicates to the ProductUpdate builder.
func (_u *ProductUpdate) Where(ps ...predicate.Product) *ProductUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSku sets the "sku" field.
func (_u *ProductUpdate) SetSku(v string) *ProductUpdate {
	_u.mutation.SetSku(v)
	return _u
}

// SetNillableSku sets the "sku" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableSku(v *string) *ProductUpdate {
	if v != nil {
		_u.SetSku(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ProductUpdate) SetName(v string) *ProductUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableName(v *string) *ProductUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPriceCents sets the "price_cents" field.
func (_u *ProductUpdate) SetPriceCents(v int) *ProductUpdate {
	_u.mutation.SetPriceCents(v)
	return _u
}

// SetNillablePriceCents sets the "price_cents" field if the given value is not nil.
func (_u *ProductUpdate) SetNillablePriceCents(v *int) *ProductUpdate {
	if v != nil {
		_u.SetPriceCents(*v)
	}
	return _u
}

// AddPriceCents adds v to the "price_cents" field.
func (_u *ProductUpdate) AddPriceCents(v int) *ProductUpdate {
	_u.mutation.AddPriceCents(v)
	return _u
}

// SetCategoryID sets the "category" edge by id.
func (_u *ProductUpdate) SetCategoryID(id int) *ProductUpdate {
	_u.mutation.SetCategoryID(id)
	return _u
}

// SetNillableCategoryID sets the "category" edge by id if the given value is not nil.
func (_u *ProductUpdate) SetNillableCategoryID(id *int) *ProductUpdate {
	if id != nil {
		_u.SetCategoryID(*id)
	}
	return _u
}

// ClearCategory clears the "category" edge.
func (_u *ProductUpdate) ClearCategory() *ProductUpdate {
	_u.mutation.ClearCategory()
	return _u
}

// AddStockIDs adds the "stocks" edge by ids.
func (_u *ProductUpdate) AddStockIDs(ids ...int) *ProductUpdate {
	_u.mutation.AddStockIDs(ids...)
	return _u
}

// RemoveStockIDs removes the "stocks" edge by ids.
func (_u *ProductUpdate) RemoveStockIDs(ids ...int) *ProductUpdate {
	_u.mutation.RemoveStockIDs(ids...)
	return _u
}

// ClearStocks clears the "stocks" edge.
func (_u *ProductUpdate) ClearStocks() *ProductUpdate {
	_u.mutation.ClearStocks()
	return _u
}

// AddOrderItemIDs adds the "order_items" edge by ids.
func (_u *ProductUpdate) AddOrderItemIDs(ids ...int) *ProductUpdate {
	_u.mutation.AddOrderItemIDs(ids...)
	return _u
}

// RemoveOrderItemIDs removes the "order_items" edge by ids.
func (_u *ProductUpdate) RemoveOrderItemIDs(ids ...int) *ProductUpdate {
	_u.mutation.RemoveOrderItemIDs(ids...)
	return _u
}

// ClearOrderItems clears the "order_items" edge.
func (_u *ProductUpdate) ClearOrderItems() *ProductUpdate {
	_u.mutation.ClearOrderItems()
	return _u
}

// SetCategory sets the "category" edge to the given entity.
func (_u *ProductUpdate) SetCategory(v *entity.Category) *ProductUpdate {
	_u.SetCategoryID(v.ID)
	return _u
}

// AddStocks adds the "stocks" edge to the given entities.
func (_u *ProductUpdate) AddStocks(v ...*entity.Stock) *ProductUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	_u.AddStockIDs(ids...)
	return _u
}

// RemoveStocks removes the "stocks" edge to the given entities.
func (_u *ProductUpdate) RemoveStocks(v ...*entity.Stock) *ProductUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	_u.RemoveStockIDs(ids...)
	return _u
}

// AddOrderItems adds the "order_items" edge to the given entities.
func (_u *ProductUpdate) AddOrderItems(v ...*entity.OrderItem) *ProductUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	_u.AddOrderItemIDs(ids...)
	return _u
}

// RemoveOrderItems removes the "order_items" edge to the given entities.
func (_u *ProductUpdate) RemoveOrderItems(v ...*entity.OrderItem) *ProductUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	_u.RemoveOrderItemIDs(ids...)
	return _u
}

// Mutation returns the ProductMutation.
func (_u *ProductUpdate) Mutation() *ProductMutation {
	return _u.mutation
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ProductUpdate) Modify(modifiers ...func(*sql.UpdateBuilder)) *ProductUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

// check runs the user-defined validators on the fields this mutation sets
// and guards required unique edges against being cleared.
func (_u *ProductUpdate) check() error {
	if v, ok := _u.mutation.Sku(); ok {
		if err := product.SkuValidator(v); err != nil {
			return &runtime.ValidationError{
				Entity: "Product",
				Err:    fmt.Errorf("validator failed for field \"Product.sku\": %w", err),
				Field:  "sku",
				Name:   "sku",
			}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := product.NameValidator(v); err != nil {
			return &runtime.ValidationError{
				Entity: "Product",
				Err:    fmt.Errorf("validator failed for field \"Product.name\": %w", err),
				Field:  "name",
				Name:   "name",
			}
		}
	}
	if v, ok := _u.mutation.PriceCents(); ok {
		if err := product.PriceCentsValidator(v); err != nil {
			return &runtime.ValidationError{
				Entity: "Product",
				Err:    fmt.Errorf("validator failed for field \"Product.price_cents\": %w", err),
				Field:  "price_cents",
				Name:   "price_cents",
			}
		}
	}
	if _u.mutation.CategoryCleared() {
		return errors.New("clearing a required unique edge \"Product.category\"")
	}
	return nil
}

// sqlSave executes the SQL update for Product after hooks have run.
func (_u *ProductUpdate) sqlSave(ctx context.Context) (int, error) {
	if err := _u.check(); err != nil {
		return 0, err
	}
	spec := sqlgraph.NewUpdateSpec(product.Table, product.Columns, &sqlgraph.FieldSpec{
		Column: product.FieldID,
		Type:   productIDFieldType,
	})
	if _u.mutation._sku != nil {
		spec.SetField("sku", field.TypeString, *_u.mutation._sku)
	}
	if _u.mutation._name != nil {
		spec.SetField("name", field.TypeString, *_u.mutation._name)
	}
	if _u.mutation._price_cents != nil {
		spec.SetField("price_cents", field.TypeInt, *_u.mutation._price_cents)
	}
	if _u.mutation._addprice_cents != nil {
		spec.AddField("price_cents", field.TypeInt, *_u.mutation._addprice_cents)
	}
	ps := _u.mutation.PredicatesFuncs()
	if len(ps) > 0 {
		spec.Predicate = func(s *sql.Selector) {
			for i := range ps {
				ps[i](s)
			}
		}
	}
	if _u.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"category_products"},
			Inverse: true,
			Rel:     sqlgraph.M2O,
			Table:   "products",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		spec.Edges.Clear = append(spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"category_products"},
			Inverse: true,
			Rel:     sqlgraph.M2O,
			Table:   "products",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		spec.Edges.Add = append(spec.Edges.Add, edge)
	}
	if _u.mutation.StocksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"product_stocks"},
			Inverse: false,
			Rel:     sqlgraph.O2M,
			Table:   "stocks",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		spec.Edges.Clear = append(spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStocksIDs(); len(nodes) > 0 && !_u.mutation.StocksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"product_stocks"},
			Inverse: false,
			Rel:     sqlgraph.O2M,
			Table:   "stocks",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		spec.Edges.Clear = append(spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StocksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"product_stocks"},
			Inverse: false,
			Rel:     sqlgraph.O2M,
			Table:   "stocks",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		spec.Edges.Add = append(spec.Edges.Add, edge)
	}
	if _u.mutation.OrderItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"product_order_items"},
			Inverse: false,
			Rel:     sqlgraph.O2M,
			Table:   "order_items",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		spec.Edges.Clear = append(spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOrderItemsIDs(); len(nodes) > 0 && !_u.mutation.OrderItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"product_order_items"},
			Inverse: false,
			Rel:     sqlgraph.O2M,
			Table:   "order_items",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		spec.Edges.Clear = append(spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"product_order_items"},
			Inverse: false,
			Rel:     sqlgraph.O2M,
			Table:   "order_items",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		spec.Edges.Add = append(spec.Edges.Add, edge)
	}
	if len(_u.modifiers) > 0 {
		spec.AddModifiers(_u.modifiers...)
	}
	affected, err := sqlgraph.UpdateNodes(ctx, _u.config.Driver, spec)
	if err != nil {
		return 0, runtime.MayWrapConstraintError(err)
	}
	return affected, nil
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProductUpdate) Save(ctx context.Context) (int, error) {
	hooks := _u.hooks
	return velox.WithHooks[int, ProductMutation, *ProductMutation](ctx, _u.sqlSave, _u.mutation, hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProductUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProductUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProductUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// ProductUpdateOne is the update builder for a single Product entity.
type ProductUpdateOne struct {
	config       runtime.Config
	mutation     *ProductMutation
	hooks        []runtime.Hook
	modifiers    []func(*sql.UpdateBuilder)
	selectFields []string
}

// NewProductUpdateOne creates a new ProductUpdateOne builder.
func NewProductUpdateOne(c runtime.Config, mutation *ProductMutation, hooks []runtime.Hook) *ProductUpdateOne {
	return &ProductUpdateOne{
		config:   c,
		hooks:    hooks,
		mutation: mutation,
	}
}

// Where appends a list predicates to the ProductUpdateOne builder.
func (_u *ProductUpdateOne) Where(ps ...predicate.Product) *ProductUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema. It narrows
// only what is read back — every field set on this builder is still written.
func (_u *ProductUpdateOne) Select(field string, fields ...string) *ProductUpdateOne {
	_u.selectFields = append([]string{field}, fields...)
	return _u
}

// SetSku sets the "sku" field.
func (_u *ProductUpdateOne) SetSku(v string) *ProductUpdateOne {
	_u.mutation.SetSku(v)
	return _u
}

// SetNillableSku sets the "sku" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableSku(v *string) *ProductUpdateOne {
	if v != nil {
		_u.SetSku(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ProductUpdateOne) SetName(v string) *ProductUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableName(v *string) *ProductUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPriceCents sets the "price_cents" field.
func (_u *ProductUpdateOne) SetPriceCents(v int) *ProductUpdateOne {
	_u.mutation.SetPriceCents(v)
	return _u
}

// SetNillablePriceCents sets the "price_cents" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillablePriceCents(v *int) *ProductUpdateOne {
	if v != nil {
		_u.SetPriceCents(*v)
	}
	return _u
}

// AddPriceCents adds v to the "price_cents" field.
func (_u *ProductUpdateOne) AddPriceCents(v int) *ProductUpdateOne {
	_u.mutation.AddPriceCents(v)
	return _u
}

// SetCategoryID sets the "category" edge by id.
func (_u *ProductUpdateOne) SetCategoryID(id int) *ProductUpdateOne {
	_u.mutation.SetCategoryID(id)
	return _u
}

// SetNillableCategoryID sets the "category" edge by id if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableCategoryID(id *int) *ProductUpdateOne {
	if id != nil {
		_u.SetCategoryID(*id)
	}
	return _u
}

// ClearCategory clears the "category" edge.
func (_u *ProductUpdateOne) ClearCategory() *ProductUpdateOne {
	_u.mutation.ClearCategory()
	return _u
}

// AddStockIDs adds the "stocks" edge by ids.
func (_u *ProductUpdateOne) AddStockIDs(ids ...int) *ProductUpdateOne {
	_u.mutation.AddStockIDs(ids...)
	return _u
}

// RemoveStockIDs removes the "stocks" edge by ids.
func (_u *ProductUpdateOne) RemoveStockIDs(ids ...int) *ProductUpdateOne {
	_u.mutation.RemoveStockIDs(ids...)
	return _u
}

// ClearStocks clears the "stocks" edge.
func (_u *ProductUpdateOne) ClearStocks() *ProductUpdateOne {
	_u.mutation.ClearStocks()
	return _u
}

// AddOrderItemIDs adds the "order_items" edge by ids.
func (_u *ProductUpdateOne) AddOrderItemIDs(ids ...int) *ProductUpdateOne {
	_u.mutation.AddOrderItemIDs(ids...)
	return _u
}

// RemoveOrderItemIDs removes the "order_items" edge by ids.
func (_u *ProductUpdateOne) RemoveOrderItemIDs(ids ...int) *ProductUpdateOne {
	_u.mutation.RemoveOrderItemIDs(ids...)
	return _u
}

// ClearOrderItems clears the "order_items" edge.
func (_u *ProductUpdateOne) ClearOrderItems() *ProductUpdateOne {
	_u.mutation.ClearOrderItems()
	return _u
}

// SetCategory sets the "category" edge to the given entity.
func (_u *ProductUpdateOne) SetCategory(v *entity.Category) *ProductUpdateOne {
	_u.SetCategoryID(v.ID)
	return _u
}

// AddStocks adds the "stocks" edge to the given entities.
func (_u *ProductUpdateOne) AddStocks(v ...*entity.Stock) *ProductUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	_u.AddStockIDs(ids...)
	return _u
}

// RemoveStocks removes the "stocks" edge to the given entities.
func (_u *ProductUpdateOne) RemoveStocks(v ...*entity.Stock) *ProductUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	_u.RemoveStockIDs(ids...)
	return _u
}

// AddOrderItems adds the "order_items" edge to the given entities.
func (_u *ProductUpdateOne) AddOrderItems(v ...*entity.OrderItem) *ProductUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	_u.AddOrderItemIDs(ids...)
	return _u
}

// RemoveOrderItems removes the "order_items" edge to the given entities.
func (_u *ProductUpdateOne) RemoveOrderItems(v ...*entity.OrderItem) *ProductUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	_u.RemoveOrderItemIDs(ids...)
	return _u
}

// Mutation returns the ProductMutation.
func (_u *ProductUpdateOne) Mutation() *ProductMutation {
	return _u.mutation
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ProductUpdateOne) Modify(modifiers ...func(*sql.UpdateBuilder)) *ProductUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

// check runs the user-defined validators on the fields this mutation sets
// and guards required unique edges against being cleared.
func (_u *ProductUpdateOne) check() error {
	if v, ok := _u.mutation.Sku(); ok {
		if err := product.SkuValidator(v); err != nil {
			return &runtime.ValidationError{
				Entity: "Product",
				Err:    fmt.Errorf("validator failed for field \"Product.sku\": %w", err),
				Field:  "sku",
				Name:   "sku",
			}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := product.NameValidator(v); err != nil {
			return &runtime.ValidationError{
				Entity: "Product",
				Err:    fmt.Errorf("validator failed for field \"Product.name\": %w", err),
				Field:  "name",
				Name:   "name",
			}
		}
	}
	if v, ok := _u.mutation.PriceCents(); ok {
		if err := product.PriceCentsValidator(v); err != nil {
			return &runtime.ValidationError{
				Entity: "Product",
				Err:    fmt.Errorf("validator failed for field \"Product.price_cents\": %w", err),
				Field:  "price_cents",
				Name:   "price_cents",
			}
		}
	}
	if _u.mutation.CategoryCleared() {
		return errors.New("clearing a required unique edge \"Product.category\"")
	}
	return nil
}

// sqlSave executes the SQL update for a single Product after hooks have run.
func (_u *ProductUpdateOne) sqlSave(ctx context.Context) (*entity.Product, error) {
	if err := _u.check(); err != nil {
		return nil, err
	}
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, errors.New("velox: missing ID for UpdateOne")
	}
	spec := sqlgraph.NewUpdateSpec(product.Table, product.Columns, &sqlgraph.FieldSpec{
		Column: product.FieldID,
		Type:   productIDFieldType,
	})
	if _u.mutation._sku != nil {
		spec.SetField("sku", field.TypeString, *_u.mutation._sku)
	}
	if _u.mutation._name != nil {
		spec.SetField("name", field.TypeString, *_u.mutation._name)
	}
	if _u.mutation._price_cents != nil {
		spec.SetField("price_cents", field.TypeInt, *_u.mutation._price_cents)
	}
	if _u.mutation._addprice_cents != nil {
		spec.AddField("price_cents", field.TypeInt, *_u.mutation._addprice_cents)
	}
	spec.Node.ID.Value = id
	ps := _u.mutation.PredicatesFuncs()
	spec.Predicate = func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(product.FieldID), id))
		for i := range ps {
			ps[i](s)
		}
	}
	if _u.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"category_products"},
			Inverse: true,
			Rel:     sqlgraph.M2O,
			Table:   "products",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		spec.Edges.Clear = append(spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"category_products"},
			Inverse: true,
			Rel:     sqlgraph.M2O,
			Table:   "products",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		spec.Edges.Add = append(spec.Edges.Add, edge)
	}
	if _u.mutation.StocksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"product_stocks"},
			Inverse: false,
			Rel:     sqlgraph.O2M,
			Table:   "stocks",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		spec.Edges.Clear = append(spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStocksIDs(); len(nodes) > 0 && !_u.mutation.StocksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"product_stocks"},
			Inverse: false,
			Rel:     sqlgraph.O2M,
			Table:   "stocks",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		spec.Edges.Clear = append(spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StocksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"product_stocks"},
			Inverse: false,
			Rel:     sqlgraph.O2M,
			Table:   "stocks",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		spec.Edges.Add = append(spec.Edges.Add, edge)
	}
	if _u.mutation.OrderItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"product_order_items"},
			Inverse: false,
			Rel:     sqlgraph.O2M,
			Table:   "order_items",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		spec.Edges.Clear = append(spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOrderItemsIDs(); len(nodes) > 0 && !_u.mutation.OrderItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"product_order_items"},
			Inverse: false,
			Rel:     sqlgraph.O2M,
			Table:   "order_items",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		spec.Edges.Clear = append(spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"product_order_items"},
			Inverse: false,
			Rel:     sqlgraph.O2M,
			Table:   "order_items",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		spec.Edges.Add = append(spec.Edges.Add, edge)
	}
	if len(_u.modifiers) > 0 {
		spec.AddModifiers(_u.modifiers...)
	}
	if err := sqlgraph.UpdateNode(ctx, _u.config.Driver, spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			return nil, velox.NewNotFoundError("Product")
		}
		return nil, runtime.MayWrapConstraintError(err)
	}
	columns := product.Columns
	if len(_u.selectFields) > 0 {
		columns = make([]string, 0, len(_u.selectFields)+1)
		columns = append(columns, product.FieldID)
		for _, f := range _u.selectFields {
			if !product.ValidColumn(f) {
				return nil, &runtime.ValidationError{
					Entity: "Product",
					Err:    errors.New("invalid field for query"),
					Field:  f,
					Name:   f,
				}
			}
			if f != product.FieldID {
				columns = append(columns, f)
			}
		}
	}
	build := func(_ context.Context) (*sql.Selector, error) {
		s := sql.Select(columns...).From(sql.Table(product.Table))
		s.SetDialect(_u.config.Driver.Dialect())
		s.Where(sql.EQ(s.C(product.FieldID), id))
		s.Limit(1)
		return s, nil
	}
	_node, err2 := runtime.ScanFirst[entity.Product, *entity.Product](ctx, _u.config.Driver, build, "Product")
	if err2 != nil {
		return nil, err2
	}
	_node.SetConfig(_u.config)
	return _node, nil
}

// Save executes the query and returns the updated Product entity.
func (_u *ProductUpdateOne) Save(ctx context.Context) (*entity.Product, error) {
	_u.mutation.oldValue = func(ctx context.Context) (*entity.Product, error) {
		id, ok := _u.mutation.ID()
		if !ok {
			return nil, errors.New("velox: missing ID for OldField")
		}
		build := func(_ context.Context) (*sql.Selector, error) {
			s := sql.Select(product.Columns...).From(sql.Table(product.Table))
			s.SetDialect(_u.config.Driver.Dialect())
			s.Where(sql.EQ(s.C(product.FieldID), id))
			s.Limit(1)
			return s, nil
		}
		_old, err := runtime.ScanFirst[entity.Product, *entity.Product](ctx, _u.config.Driver, build, "Product")
		if err != nil {
			return nil, err
		}
		_old.SetConfig(_u.config)
		return _old, nil
	}
	hooks := _u.hooks
	return velox.WithHooks[*entity.Product, ProductMutation, *ProductMutation](ctx, _u.sqlSave, _u.mutation, hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProductUpdateOne) SaveX(ctx context.Context) *entity.Product {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProductUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProductUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}
