// Code generated by gqlc. DO NOT EDIT.

// Package graph wires the generated GraphQL schema and its bindings.
package graph

import (
	"embed"

	"github.com/syssam/graphql-go"
)

//go:embed schema/*.graphql
var sdl embed.FS

func NewSchema(r Resolver, opts ...graphql.SchemaOption) (*graphql.Schema, error) {
	all := append([]graphql.SchemaOption{Bindings(r)}, opts...)
	return graphql.NewSchema(graphql.SDLFS(sdl, "schema/*.graphql"), all...)
}
