// Code generated by velox. DO NOT EDIT.

package product

import "github.com/syssam/velox/runtime"

// ProductCollectMeta holds GraphQL field collection metadata for Product.
var ProductCollectMeta runtime.CollectMeta

func init() {
	ProductCollectMeta.FieldColumns = map[string]string{"sku": FieldSku, "name": FieldName, "priceCents": FieldPriceCents}
	ProductCollectMeta.Edges = map[string]runtime.EdgeMeta{"category": {
		FKColumns:   []string{"category_products"},
		Inverse:     "products",
		Name:        "category",
		PagesLoaded: false,
		Relay:       false,
		Target:      "categories",
		Unique:      true,
	}, "stocks": {
		FKColumns:   []string{},
		Inverse:     "",
		Name:        "stocks",
		PagesLoaded: false,
		Relay:       false,
		Target:      "stocks",
		Unique:      false,
	}, "orderItems": {
		FKColumns:   []string{},
		Inverse:     "",
		Name:        "order_items",
		PagesLoaded: false,
		Relay:       false,
		Target:      "order_items",
		Unique:      false,
	}}
}
