// Code generated by velox. DO NOT EDIT.

package product

import (
	predicate "github.com/syssam/graphql-go/examples/veloxfx/velox/predicate"
	sql "github.com/syssam/velox/dialect/sql"
	sqlgraph "github.com/syssam/velox/dialect/sql/sqlgraph"
	runtime "github.com/syssam/velox/runtime"
)

const (
	// Label holds the string label denoting the Product type in the database.
	Label = "product"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSku holds the string denoting the sku field in the database.
	FieldSku = "sku"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPriceCents holds the string denoting the price_cents field in the database.
	FieldPriceCents = "price_cents"
	// EdgeCategory holds the string denoting the category edge name in mutations.
	EdgeCategory = "category"
	// EdgeStocks holds the string denoting the stocks edge name in mutations.
	EdgeStocks = "stocks"
	// EdgeOrderItems holds the string denoting the order_items edge name in mutations.
	EdgeOrderItems = "order_items"
	// Table holds the table name of the Product in the database.
	Table = "products"
	// CategoryTable is the table that holds the category relation/edge.
	CategoryTable = "products"
	// CategoryInverseTable is the table name for the Category entity.
	// It exists in this package in order to avoid circular dependency with the "category" package.
	CategoryInverseTable = "categories"
	// CategoryColumn is the table column denoting the category relation/edge.
	CategoryColumn = "category_products"
	// StocksTable is the table that holds the stocks relation/edge.
	StocksTable = "stocks"
	// StocksInverseTable is the table name for the Stock entity.
	// It exists in this package in order to avoid circular dependency with the "stock" package.
	StocksInverseTable = "stocks"
	// StocksColumn is the table column denoting the stocks relation/edge.
	StocksColumn = "product_stocks"
	// OrderItemsTable is the table that holds the order_items relation/edge.
	OrderItemsTable = "order_items"
	// OrderItemsInverseTable is the table name for the OrderItem entity.
	// It exists in this package in order to avoid circular dependency with the "orderitem" package.
	OrderItemsInverseTable = "order_items"
	// OrderItemsColumn is the table column denoting the order_items relation/edge.
	OrderItemsColumn = "product_order_items"
)

// Columns holds all SQL columns for Product fields.
var Columns = []string{FieldID, FieldSku, FieldName, FieldPriceCents}

// ForeignKeys holds the SQL foreign-keys that are owned by the "products"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{"category_products"}

// columnSet holds the set of valid column names for O(1) lookups.
var columnSet = func() map[string]struct{} {
	s := make(map[string]struct{}, 5)
	for _, c := range Columns {
		s[c] = struct{}{}
	}
	for _, c := range ForeignKeys {
		s[c] = struct{}{}
	}
	return s
}()

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	_, ok := columnSet[column]
	return ok
}

var (
	// SkuValidator is a validator for the "sku" field. It is called by the builders before save.
	SkuValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// PriceCentsValidator is a validator for the "price_cents" field. It is called by the builders before save.
	PriceCentsValidator func(int) error
)

// OrderOption defines the ordering options for the Product queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySku orders the results by the sku field.
func BySku(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSku, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByPriceCents orders the results by the price_cents field.
func ByPriceCents(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriceCents, opts...).ToFunc()
}

// ByCategoryField orders the results by category field.
func ByCategoryField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCategoryStep(), sql.OrderByField(field, opts...))
	}
}

// ByStocksCount orders the results by stocks count.
func ByStocksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newStocksStep(), opts...)
	}
}

// ByStocks orders the results by stocks terms.
func ByStocks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStocksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByOrderItemsCount orders the results by order_items count.
func ByOrderItemsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOrderItemsStep(), opts...)
	}
}

// ByOrderItems orders the results by order_items terms.
func ByOrderItems(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOrderItemsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCategoryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(sqlgraph.From(Table, FieldID), sqlgraph.To(CategoryInverseTable, FieldID), sqlgraph.Edge(sqlgraph.M2O, true, CategoryTable, CategoryColumn))
}
func newStocksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(sqlgraph.From(Table, FieldID), sqlgraph.To(StocksInverseTable, FieldID), sqlgraph.Edge(sqlgraph.O2M, false, StocksTable, StocksColumn))
}
func newOrderItemsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(sqlgraph.From(Table, FieldID), sqlgraph.To(OrderItemsInverseTable, FieldID), sqlgraph.Edge(sqlgraph.O2M, false, OrderItemsTable, OrderItemsColumn))
}

// =============================================================================
// LoadOption helpers (functional options for edge loading)
// =============================================================================

// Where returns a LoadOption that adds predicates to the edge query.
func Where(ps ...predicate.Product) runtime.LoadOption {
	return func(c *runtime.LoadConfig) {
		for _, p := range ps {
			c.Predicates = append(c.Predicates, (func(*sql.Selector))(p))
		}
	}
}

// Select returns a LoadOption that selects specific fields.
func Select(fields ...string) runtime.LoadOption {
	return runtime.Select(fields...)
}

// Limit returns a LoadOption that limits the number of results.
func Limit(n int) runtime.LoadOption {
	return runtime.Limit(n)
}

// OrderBy returns a LoadOption that orders the results.
func OrderBy(o ...func(*sql.Selector)) runtime.LoadOption {
	return runtime.OrderBy(o...)
}

// WithCategory returns a LoadOption that eager-loads the "category" edge.
func WithCategory(opts ...runtime.LoadOption) runtime.LoadOption {
	return runtime.WithEdge("category", opts...)
}

// WithStocks returns a LoadOption that eager-loads the "stocks" edge.
func WithStocks(opts ...runtime.LoadOption) runtime.LoadOption {
	return runtime.WithEdge("stocks", opts...)
}

// WithOrderItems returns a LoadOption that eager-loads the "order_items" edge.
func WithOrderItems(opts ...runtime.LoadOption) runtime.LoadOption {
	return runtime.WithEdge("order_items", opts...)
}
