// Code generated by gqlc. DO NOT EDIT.

// Package stock holds the generated GraphQL bindings for the stock group.
package stock

import (
	"context"

	"github.com/syssam/graphql-go"
	stock "github.com/syssam/graphql-go/examples/veloxfx/velox/client/stock"
	entity "github.com/syssam/graphql-go/examples/veloxfx/velox/entity"
)

type CreateStockArgs struct {
	Input stock.CreateStockInput `graphql:"input"`
}

type UpdateStockArgs struct {
	ID    graphql.ID             `graphql:"id"`
	Input stock.UpdateStockInput `graphql:"input"`
}

// Resolver holds methods for fields that are not struct data.
type Resolver interface {
	CreateStock(ctx context.Context, args CreateStockArgs) (*entity.Stock, error)
	UpdateStock(ctx context.Context, args UpdateStockArgs) (*entity.Stock, error)
	Stocks(ctx context.Context) ([]*entity.Stock, error)
	StockID(ctx context.Context, obj *entity.Stock) (graphql.ID, error)
}

func Bindings(r Resolver) graphql.SchemaOption {
	return graphql.Options(
		graphql.Input[stock.CreateStockInput]("CreateStockInput", graphql.ZeroForNull()),
		graphql.Input[stock.UpdateStockInput]("UpdateStockInput", graphql.ZeroForNull()),
		graphql.Object[entity.Stock]("Stock",
			graphql.Resolve("id", func(ctx context.Context, v *entity.Stock) (graphql.ID, error) { return r.StockID(ctx, v) }),
			graphql.Field("quantity", func(v *entity.Stock) int { return v.Quantity }),
			graphql.Resolve("warehouse", func(ctx context.Context, v *entity.Stock) (*entity.Warehouse, error) { return v.Warehouse(ctx) }),
			graphql.Resolve("product", func(ctx context.Context, v *entity.Stock) (*entity.Product, error) { return v.Product(ctx) }),
		),
		graphql.Query(
			graphql.Resolve("stocks", func(ctx context.Context, _ graphql.Root) ([]*entity.Stock, error) { return r.Stocks(ctx) }),
		),
		graphql.Mutation(
			graphql.ResolveArgs("createStock", func(ctx context.Context, _ graphql.Root, a CreateStockArgs) (*entity.Stock, error) {
				return r.CreateStock(ctx, a)
			}),
			graphql.ResolveArgs("updateStock", func(ctx context.Context, _ graphql.Root, a UpdateStockArgs) (*entity.Stock, error) {
				return r.UpdateStock(ctx, a)
			}),
		),
		graphql.Args[CreateStockArgs](),
		graphql.Args[UpdateStockArgs](),
	)
}
