// Code generated by gqlc. DO NOT EDIT.

// Package stock holds the generated GraphQL bindings for the stock group.
package stock

import (
	"context"

	"github.com/syssam/graphql-go"
	stock "github.com/syssam/graphql-go/examples/veloxfx/velox/client/stock"
	entity "github.com/syssam/graphql-go/examples/veloxfx/velox/entity"
)

type CreateStockArgs struct {
	Input stock.CreateStockInput `graphql:"input"`
}

type AdjustStockArgs struct {
	ID    graphql.ID `graphql:"id"`
	Delta int        `graphql:"delta"`
}

type DeleteStockArgs struct {
	ID graphql.ID `graphql:"id"`
}

type StockArgs struct {
	ID graphql.ID `graphql:"id"`
}

// Resolver holds methods for fields that are not struct data.
type Resolver interface {
	CreateStock(ctx context.Context, args CreateStockArgs) (*entity.Stock, error)
	AdjustStock(ctx context.Context, args AdjustStockArgs) (*entity.Stock, error)
	DeleteStock(ctx context.Context, args DeleteStockArgs) (graphql.ID, error)
	Stocks(ctx context.Context) ([]*entity.Stock, error)
	Stock(ctx context.Context, args StockArgs) (*entity.Stock, error)
	StockID(ctx context.Context, obj *entity.Stock) (graphql.ID, error)
}

func Bindings(r Resolver) graphql.SchemaOption {
	return graphql.Options(
		graphql.Input[stock.CreateStockInput]("CreateStockInput", graphql.ZeroForNull()),
		graphql.Object[entity.Stock]("Stock",
			graphql.Resolve("id", func(ctx context.Context, v *entity.Stock) (graphql.ID, error) { return r.StockID(ctx, v) }),
			graphql.Field("quantity", func(v *entity.Stock) int { return v.Quantity }),
			graphql.Resolve("warehouse", func(ctx context.Context, v *entity.Stock) (*entity.Warehouse, error) { return v.Warehouse(ctx) }),
			graphql.Resolve("product", func(ctx context.Context, v *entity.Stock) (*entity.Product, error) { return v.Product(ctx) }),
		),
		graphql.Query(
			graphql.Resolve("stocks", func(ctx context.Context, _ graphql.Root) ([]*entity.Stock, error) { return r.Stocks(ctx) }),
			graphql.ResolveArgs("stock", func(ctx context.Context, _ graphql.Root, a StockArgs) (*entity.Stock, error) { return r.Stock(ctx, a) }),
		),
		graphql.Mutation(
			graphql.ResolveArgs("createStock", func(ctx context.Context, _ graphql.Root, a CreateStockArgs) (*entity.Stock, error) {
				return r.CreateStock(ctx, a)
			}),
			graphql.ResolveArgs("adjustStock", func(ctx context.Context, _ graphql.Root, a AdjustStockArgs) (*entity.Stock, error) {
				return r.AdjustStock(ctx, a)
			}),
			graphql.ResolveArgs("deleteStock", func(ctx context.Context, _ graphql.Root, a DeleteStockArgs) (graphql.ID, error) {
				return r.DeleteStock(ctx, a)
			}),
		),
		graphql.Args[CreateStockArgs](),
		graphql.Args[AdjustStockArgs](),
		graphql.Args[DeleteStockArgs](),
		graphql.Args[StockArgs](),
	)
}
