// Code generated by velox. DO NOT EDIT.

package todoclient

import (
	"context"
	"fmt"
	"reflect"

	entity "github.com/syssam/graphql-go/examples/veloxfx/velox/entity"
	todo "github.com/syssam/graphql-go/examples/veloxfx/velox/todo"
	velox "github.com/syssam/velox"
	sql "github.com/syssam/velox/dialect/sql"
	sqlgraph "github.com/syssam/velox/dialect/sql/sqlgraph"
	runtime "github.com/syssam/velox/runtime"
)

// TodoClient is the client for interacting with the Todo builders.
type TodoClient struct {
	config     runtime.Config
	hookStore  *entity.HookStore
	interStore *entity.InterceptorStore
}

// NewTodoClient creates a new TodoClient.
func NewTodoClient(c runtime.Config) *TodoClient {
	hs, _ := c.HookStore.(*entity.HookStore)
	if hs == nil {
		hs = &entity.HookStore{}
	}
	is, _ := c.InterStore.(*entity.InterceptorStore)
	if is == nil {
		is = &entity.InterceptorStore{}
	}
	return &TodoClient{
		config:     c,
		hookStore:  hs,
		interStore: is,
	}
}

// Create returns a builder for creating a Todo entity.
func (c *TodoClient) Create() *TodoCreate {
	mutation := NewTodoMutation(c.config, runtime.OpCreate)
	return NewTodoCreate(c.config, mutation, c.Hooks())
}

// CreateBulk returns a builder for creating a bulk of Todo entities.
func (c *TodoClient) CreateBulk(builders ...*TodoCreate) *TodoCreateBulk {
	return NewTodoCreateBulk(c.config, builders)
}

// MapCreateBulk creates a bulk creation builder from the given slice.
// For each item in the slice, the set function is called to configure the
// builder for that item.
func (c *TodoClient) MapCreateBulk(slice any, setFunc func(*TodoCreate, int)) *TodoCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TodoCreateBulk{err: fmt.Errorf("calling to %T.MapCreateBulk with wrong type %T, need slice", c, slice)}
	}
	builders := make([]*TodoCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return NewTodoCreateBulk(c.config, builders)
}

// Update returns an update builder for Todo.
func (c *TodoClient) Update() *TodoUpdate {
	mutation := NewTodoMutation(c.config, runtime.OpUpdate)
	return NewTodoUpdate(c.config, mutation, c.Hooks())
}

// Delete returns a delete builder for Todo.
func (c *TodoClient) Delete() *TodoDelete {
	mutation := NewTodoMutation(c.config, runtime.OpDelete)
	return NewTodoDelete(c.config, mutation, c.Hooks())
}

// UpdateOneID returns an update builder for the given id.
func (c *TodoClient) UpdateOneID(id int) *TodoUpdateOne {
	mutation := NewTodoMutation(c.config, runtime.OpUpdateOne)
	mutation.SetID(id)
	return NewTodoUpdateOne(c.config, mutation, c.Hooks())
}

// UpdateOne returns an update builder for the given Todo entity.
func (c *TodoClient) UpdateOne(v *entity.Todo) *TodoUpdateOne {
	return c.UpdateOneID(v.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *TodoClient) DeleteOneID(id int) *TodoDeleteOne {
	mutation := NewTodoMutation(c.config, runtime.OpDeleteOne)
	mutation.SetID(id)
	mutation.Where(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(todo.FieldID), id))
	})
	builder := NewTodoDelete(c.config, mutation, c.Hooks())
	return NewTodoDeleteOne(builder)
}

// DeleteOne returns a builder for deleting the given Todo entity.
func (c *TodoClient) DeleteOne(v *entity.Todo) *TodoDeleteOne {
	return c.DeleteOneID(v.ID)
}

// Query returns a query builder for Todo entities.
func (c *TodoClient) Query() entity.TodoQuerier {
	q := runtime.NewEntityQuery("Todo", c.config)
	q.(interface {
		SetInterStore(*entity.InterceptorStore)
	}).SetInterStore(c.interStore)
	return q.(entity.TodoQuerier)
}

// Get returns the Todo entity with the given id.
func (c *TodoClient) Get(ctx context.Context, id int) (*entity.Todo, error) {
	return c.Query().Where(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(todo.FieldID), id))
	}).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TodoClient) GetX(ctx context.Context, id int) *entity.Todo {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryOwner queries the "owner" edge of a Todo.
func (c *TodoClient) QueryOwner(v *entity.Todo) entity.UserQuerier {
	tq := runtime.NewEntityQuery("User", c.config)
	tq.(interface {
		SetInterStore(*entity.InterceptorStore)
	}).SetInterStore(c.interStore)
	_tp := runtime.EntityPolicy("User")
	if _tp != nil {
		if _sp, _ok := tq.(interface {
			SetPolicy(velox.Policy)
		}); _ok {
			_sp.SetPolicy(_tp)
		}
	}
	tq.(interface {
		SetPath(func(context.Context) (*sql.Selector, error))
	}).SetPath(func(ctx context.Context) (*sql.Selector, error) {
		id := v.ID
		step := sqlgraph.NewStep(sqlgraph.From(todo.Table, todo.FieldID, id), sqlgraph.To("users", "id"), sqlgraph.Edge(sqlgraph.M2O, true, todo.OwnerTable, todo.OwnerColumn))
		return sqlgraph.Neighbors(c.config.Driver.Dialect(), step), nil
	})
	return tq.(entity.UserQuerier)
}

// Use adds the mutation hooks to the TodoClient.
func (c *TodoClient) Use(hooks ...runtime.Hook) {
	c.hookStore.Todo = append(c.hookStore.Todo, hooks...)
}

// Intercept adds the query interceptors to the TodoClient.
func (c *TodoClient) Intercept(interceptors ...runtime.Interceptor) {
	c.interStore.Todo = append(c.interStore.Todo, interceptors...)
}

// Hooks returns the registered hooks of the TodoClient.
func (c *TodoClient) Hooks() []runtime.Hook {
	return c.hookStore.Todo
}

// Interceptors returns the registered interceptors of the TodoClient.
func (c *TodoClient) Interceptors() []runtime.Interceptor {
	return c.interStore.Todo
}

// mutate executes a mutation against the Todo entity based on the operation type.
func (c *TodoClient) mutate(ctx context.Context, m *TodoMutation) (any, error) {
	switch m.Op() {
	case runtime.OpCreate:
		builder := NewTodoCreate(c.config, m, c.Hooks())
		return builder.Save(ctx)
	case runtime.OpUpdate:
		builder := NewTodoUpdate(c.config, m, c.Hooks())
		return builder.Save(ctx)
	case runtime.OpUpdateOne:
		builder := NewTodoUpdateOne(c.config, m, c.Hooks())
		return builder.Save(ctx)
	case runtime.OpDelete, runtime.OpDeleteOne:
		builder := NewTodoDelete(c.config, m, c.Hooks())
		return builder.Exec(ctx)
	default:
		return nil, fmt.Errorf("unknown %s mutation op: %q", "Todo", m.Op())
	}
}
