// Code generated by velox. DO NOT EDIT.

package todoclient

import (
	"context"
	"fmt"
	"time"

	entity "github.com/syssam/graphql-go/examples/veloxfx/velox/entity"
	predicate "github.com/syssam/graphql-go/examples/veloxfx/velox/predicate"
	todo "github.com/syssam/graphql-go/examples/veloxfx/velox/todo"
	velox "github.com/syssam/velox"
	sql "github.com/syssam/velox/dialect/sql"
	runtime "github.com/syssam/velox/runtime"
)

// TodoMutation represents an operation that mutates the Todo nodes in the graph.
type TodoMutation struct {
	config        runtime.Config
	op            runtime.Op
	id            *int
	_created_at   *time.Time
	_updated_at   *time.Time
	_title        *string
	_status       *todo.Status
	clearedFields map[string]struct{}
	oldValue      func(context.Context) (*entity.Todo, error)
	oldLoaded     bool
	oldCache      *entity.Todo
	owner         map[int]struct{}
	removedOwner  map[int]struct{}
	clearedOwner  bool
	predicates    []predicate.Todo
}

var _ velox.Mutation = (*TodoMutation)(nil)

// todoOption allows management of the mutation configuration using functional options.
type todoOption func(*TodoMutation)

// NewTodoMutation creates new mutation for the Todo entity.
func NewTodoMutation(c runtime.Config, op runtime.Op, opts ...todoOption) *TodoMutation {
	m := &TodoMutation{
		config: c,
		op:     runtime.Op(op),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// Op returns the operation name.
func (m *TodoMutation) Op() runtime.Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *TodoMutation) SetOp(op runtime.Op) {
	m.op = op
}

// Type returns the schema type name of this mutation ("Todo").
func (m *TodoMutation) Type() string {
	return "Todo"
}

// ID returns the ID value in the mutation, if it was provided by the caller.
// The second bool return indicates whether the ID field was set.
func (m *TodoMutation) ID() (id any, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetID sets the entity ID value on the mutation.
func (m *TodoMutation) SetID(id int) {
	m.id = &id
}

// loadOld lazily loads the pre-mutation entity state for OldXxx methods.
func (m *TodoMutation) loadOld(ctx context.Context) (*entity.Todo, error) {
	if m.op != runtime.OpUpdateOne {
		return nil, fmt.Errorf("OldField is only allowed on UpdateOne operations")
	}
	if m.oldValue == nil {
		return nil, fmt.Errorf("OldField is not supported: no old value loader configured")
	}
	if m.oldLoaded {
		return m.oldCache, nil
	}
	old, err := m.oldValue(ctx)
	if err != nil {
		return nil, fmt.Errorf("querying old values: %w", err)
	}
	m.oldCache = old
	m.oldLoaded = true
	return old, nil
}

// Where appends a list predicates to the TodoMutation builder.
func (m *TodoMutation) Where(ps ...predicate.Todo) {
	m.predicates = append(m.predicates, ps...)
}

// PredicatesFuncs returns the predicates as untyped selector functions.
func (m *TodoMutation) PredicatesFuncs() []func(*sql.Selector) {
	ps := make([]func(*sql.Selector), len(m.predicates))
	for i, p := range m.predicates {
		ps[i] = p
	}
	return ps
}

// SetCreatedAt sets the "created_at" field.
func (m *TodoMutation) SetCreatedAt(v time.Time) {
	m._created_at = &v
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *TodoMutation) CreatedAt() (r time.Time, exists bool) {
	if m._created_at == nil {
		return
	}
	return *m._created_at, true
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *TodoMutation) ResetCreatedAt() {
	m._created_at = nil
	delete(m.clearedFields, "created_at")
}

// SetUpdatedAt sets the "updated_at" field.
func (m *TodoMutation) SetUpdatedAt(v time.Time) {
	m._updated_at = &v
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *TodoMutation) UpdatedAt() (r time.Time, exists bool) {
	if m._updated_at == nil {
		return
	}
	return *m._updated_at, true
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *TodoMutation) ResetUpdatedAt() {
	m._updated_at = nil
	delete(m.clearedFields, "updated_at")
}

// SetTitle sets the "title" field.
func (m *TodoMutation) SetTitle(v string) {
	m._title = &v
}

// Title returns the value of the "title" field in the mutation.
func (m *TodoMutation) Title() (r string, exists bool) {
	if m._title == nil {
		return
	}
	return *m._title, true
}

// ResetTitle resets all changes to the "title" field.
func (m *TodoMutation) ResetTitle() {
	m._title = nil
	delete(m.clearedFields, "title")
}

// SetStatus sets the "status" field.
func (m *TodoMutation) SetStatus(v todo.Status) {
	m._status = &v
}

// Status returns the value of the "status" field in the mutation.
func (m *TodoMutation) Status() (r todo.Status, exists bool) {
	if m._status == nil {
		return
	}
	return *m._status, true
}

// ResetStatus resets all changes to the "status" field.
func (m *TodoMutation) ResetStatus() {
	m._status = nil
	delete(m.clearedFields, "status")
}

// SetOwnerID sets the "owner" edge to the User entity by id.
func (m *TodoMutation) SetOwnerID(id int) {
	if m.owner == nil {
		m.owner = make(map[int]struct{})
	}
	m.owner[id] = struct{}{}
}

// ClearOwner clears the "owner" edge.
func (m *TodoMutation) ClearOwner() {
	m.clearedOwner = true
}

// OwnerCleared reports if the "owner" edge was cleared.
func (m *TodoMutation) OwnerCleared() bool {
	return m.clearedOwner
}

// ResetOwner resets all changes to the "owner" edge.
func (m *TodoMutation) ResetOwner() {
	m.owner = nil
	m.clearedOwner = false
	m.removedOwner = nil
}

// OwnerIDs returns the "owner" edge IDs in the mutation.
func (m *TodoMutation) OwnerIDs() (ids []int) {
	for id := range m.owner {
		ids = append(ids, id)
	}
	return
}

// Fields returns all fields that were changed during this mutation.
func (m *TodoMutation) Fields() []string {
	var fields []string
	if m._created_at != nil {
		fields = append(fields, "created_at")
	}
	if m._updated_at != nil {
		fields = append(fields, "updated_at")
	}
	if m._title != nil {
		fields = append(fields, "title")
	}
	if m._status != nil {
		fields = append(fields, "status")
	}
	return fields
}

// Field returns the value of a field with the given name.
func (m *TodoMutation) Field(name string) (runtime.Value, bool) {
	switch name {
	case "created_at":
		if m._created_at != nil {
			return *m._created_at, true
		}
	case "updated_at":
		if m._updated_at != nil {
			return *m._updated_at, true
		}
	case "title":
		if m._title != nil {
			return *m._title, true
		}
	case "status":
		if m._status != nil {
			return *m._status, true
		}
	}
	return nil, false
}

// SetField sets the value of a field with the given name. It returns an error if the field is not defined in the schema, or if the value type does not match.
func (m *TodoMutation) SetField(name string, value runtime.Value) error {
	switch name {
	case "created_at":
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field created_at", value)
		}
		m.SetCreatedAt(v)
		return nil
	case "updated_at":
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field updated_at", value)
		}
		m.SetUpdatedAt(v)
		return nil
	case "title":
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field title", value)
		}
		m.SetTitle(v)
		return nil
	case "status":
		v, ok := value.(todo.Status)
		if !ok {
			return fmt.Errorf("unexpected type %T for field status", value)
		}
		m.SetStatus(v)
		return nil
	default:
		return fmt.Errorf("unknown Todo field %s", name)
	}
}

// AddedFields returns all numeric fields that were incremented or decremented during this mutation.
func (m *TodoMutation) AddedFields() []string {
	var fields []string
	return fields
}

// AddedField returns the numeric value that was incremented or decremented for a field.
func (m *TodoMutation) AddedField(name string) (runtime.Value, bool) {
	switch name {
	}
	return nil, false
}

// AddField adds the value for the given name. It returns an error if the field is not defined in the schema, or if the value type does not match.
func (m *TodoMutation) AddField(name string, value runtime.Value) error {
	switch name {
	default:
		return fmt.Errorf("unknown Todo addable field %s", name)
	}
}

// ClearedFields returns all fields that were cleared during this mutation.
func (m *TodoMutation) ClearedFields() []string {
	var fields []string
	for f := range m.clearedFields {
		fields = append(fields, f)
	}
	return fields
}

// FieldCleared reports if a field with the given name was cleared in this mutation.
func (m *TodoMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an error if the field is not defined in the schema or is not nullable.
func (m *TodoMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Todo nullable field %s", name)
}

// ResetField resets all changes for the field with the given name. It returns an error if the field is not defined in the schema.
func (m *TodoMutation) ResetField(name string) error {
	switch name {
	case "created_at":
		m._created_at = nil
		delete(m.clearedFields, "created_at")
	case "updated_at":
		m._updated_at = nil
		delete(m.clearedFields, "updated_at")
	case "title":
		m._title = nil
		delete(m.clearedFields, "title")
	case "status":
		m._status = nil
		delete(m.clearedFields, "status")
	default:
		return fmt.Errorf("unknown Todo field %s", name)
	}
	return nil
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *TodoMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.owner != nil {
		edges = append(edges, "owner")
	}
	return edges
}

// AddedIDs returns all IDs that were added for the given edge name.
func (m *TodoMutation) AddedIDs(name string) []velox.Value {
	switch name {
	case "owner":
		ids := make([]velox.Value, 0, len(m.owner))
		for id := range m.owner {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *TodoMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedOwner != nil {
		edges = append(edges, "owner")
	}
	return edges
}

// RemovedIDs returns all IDs that were removed for the given edge name.
func (m *TodoMutation) RemovedIDs(name string) []velox.Value {
	switch name {
	case "owner":
		ids := make([]velox.Value, 0, len(m.removedOwner))
		for id := range m.removedOwner {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *TodoMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedOwner {
		edges = append(edges, "owner")
	}
	return edges
}

// EdgeCleared reports if the given edge was cleared in this mutation.
func (m *TodoMutation) EdgeCleared(name string) bool {
	switch name {
	case "owner":
		return m.clearedOwner
	}
	return false
}

// ClearEdge clears the value of the edge with the given name.
func (m *TodoMutation) ClearEdge(name string) error {
	switch name {
	case "owner":
		m.ClearOwner()
		return nil
	}
	return fmt.Errorf("unknown Todo unique edge %s", name)
}

// ResetEdge resets all changes for the edge with the given name.
func (m *TodoMutation) ResetEdge(name string) error {
	switch name {
	case "owner":
		m.ResetOwner()
		return nil
	}
	return fmt.Errorf("unknown Todo edge %s", name)
}

// OldField returns the old value of a field from the database.
// An error is returned if the mutation operation is not UpdateOne,
// or the query to the database fails.
func (m *TodoMutation) OldField(ctx context.Context, name string) (velox.Value, error) {
	switch name {
	case "created_at":
		return m.OldCreatedAt(ctx)
	case "updated_at":
		return m.OldUpdatedAt(ctx)
	case "title":
		return m.OldTitle(ctx)
	case "status":
		return m.OldStatus(ctx)
	}
	return nil, fmt.Errorf("unknown Todo field %s", name)
}

// OldCreatedAt returns the old "created_at" field value, if exists.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TodoMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	old, loadErr := m.loadOld(ctx)
	if loadErr != nil {
		err = loadErr
		return
	}
	v = old.CreatedAt
	return
}

// OldUpdatedAt returns the old "updated_at" field value, if exists.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TodoMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	old, loadErr := m.loadOld(ctx)
	if loadErr != nil {
		err = loadErr
		return
	}
	v = old.UpdatedAt
	return
}

// OldTitle returns the old "title" field value, if exists.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TodoMutation) OldTitle(ctx context.Context) (v string, err error) {
	old, loadErr := m.loadOld(ctx)
	if loadErr != nil {
		err = loadErr
		return
	}
	v = old.Title
	return
}

// OldStatus returns the old "status" field value, if exists.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TodoMutation) OldStatus(ctx context.Context) (v todo.Status, err error) {
	old, loadErr := m.loadOld(ctx)
	if loadErr != nil {
		err = loadErr
		return
	}
	v = old.Status
	return
}
