// Code generated by velox. DO NOT EDIT.

package todoclient

import (
	"context"
	"errors"
	"fmt"
	"time"

	entity "github.com/syssam/graphql-go/examples/veloxfx/velox/entity"
	predicate "github.com/syssam/graphql-go/examples/veloxfx/velox/predicate"
	todo "github.com/syssam/graphql-go/examples/veloxfx/velox/todo"
	velox "github.com/syssam/velox"
	sql "github.com/syssam/velox/dialect/sql"
	sqlgraph "github.com/syssam/velox/dialect/sql/sqlgraph"
	runtime "github.com/syssam/velox/runtime"
	field "github.com/syssam/velox/schema/field"
)

// TodoUpdate is the update builder for Todo entities.
//
// Query interceptors do NOT run on mutations. A row filter registered
// with Intercept() leaves this builder unscoped, so express row-level
// authorization as a schema Policy() — it covers reads and writes.
type TodoUpdate struct {
	config            runtime.Config
	mutation          *TodoMutation
	hooks             []runtime.Hook
	modifiers         []func(*sql.UpdateBuilder)
	skipDefaults      bool
	skipDefaultFields map[string]struct{}
}

// NewTodoUpdate creates a new TodoUpdate builder.
func NewTodoUpdate(c runtime.Config, mutation *TodoMutation, hooks []runtime.Hook) *TodoUpdate {
	return &TodoUpdate{
		config:   c,
		hooks:    hooks,
		mutation: mutation,
	}
}

// Where appends a list predicates to the TodoUpdate builder.
func (_u *TodoUpdate) Where(ps ...predicate.Todo) *TodoUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TodoUpdate) SetUpdatedAt(v time.Time) *TodoUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *TodoUpdate) SetTitle(v string) *TodoUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TodoUpdate) SetNillableTitle(v *string) *TodoUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TodoUpdate) SetStatus(v todo.Status) *TodoUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TodoUpdate) SetNillableStatus(v *todo.Status) *TodoUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetOwnerID sets the "owner" edge by id.
func (_u *TodoUpdate) SetOwnerID(id int) *TodoUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetNillableOwnerID sets the "owner" edge by id if the given value is not nil.
func (_u *TodoUpdate) SetNillableOwnerID(id *int) *TodoUpdate {
	if id != nil {
		_u.SetOwnerID(*id)
	}
	return _u
}

// ClearOwner clears the "owner" edge.
func (_u *TodoUpdate) ClearOwner() *TodoUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// SetOwner sets the "owner" edge to the given entity.
func (_u *TodoUpdate) SetOwner(v *entity.User) *TodoUpdate {
	_u.SetOwnerID(v.ID)
	return _u
}

// Mutation returns the TodoMutation.
func (_u *TodoUpdate) Mutation() *TodoMutation {
	return _u.mutation
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TodoUpdate) Modify(modifiers ...func(*sql.UpdateBuilder)) *TodoUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

// check runs the user-defined validators on the fields this mutation sets
// and guards required unique edges against being cleared.
func (_u *TodoUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := todo.TitleValidator(v); err != nil {
			return &runtime.ValidationError{
				Entity: "Todo",
				Err:    fmt.Errorf("validator failed for field \"Todo.title\": %w", err),
				Field:  "title",
				Name:   "title",
			}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := todo.StatusValidator(v); err != nil {
			return &runtime.ValidationError{
				Entity: "Todo",
				Err:    fmt.Errorf("validator failed for field \"Todo.status\": %w", err),
				Field:  "status",
				Name:   "status",
			}
		}
	}
	if _u.mutation.OwnerCleared() {
		return errors.New("clearing a required unique edge \"Todo.owner\"")
	}
	return nil
}

// sqlSave executes the SQL update for Todo after hooks have run.
func (_u *TodoUpdate) sqlSave(ctx context.Context) (int, error) {
	if err := _u.check(); err != nil {
		return 0, err
	}
	spec := sqlgraph.NewUpdateSpec(todo.Table, todo.Columns, &sqlgraph.FieldSpec{
		Column: todo.FieldID,
		Type:   todoIDFieldType,
	})
	if _u.mutation._updated_at != nil {
		spec.SetField("updated_at", field.TypeTime, *_u.mutation._updated_at)
	}
	if _u.mutation._title != nil {
		spec.SetField("title", field.TypeString, *_u.mutation._title)
	}
	if _u.mutation._status != nil {
		spec.SetField("status", field.TypeEnum, *_u.mutation._status)
	}
	ps := _u.mutation.PredicatesFuncs()
	if len(ps) > 0 {
		spec.Predicate = func(s *sql.Selector) {
			for i := range ps {
				ps[i](s)
			}
		}
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"user_todos"},
			Inverse: true,
			Rel:     sqlgraph.M2O,
			Table:   "todos",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		spec.Edges.Clear = append(spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"user_todos"},
			Inverse: true,
			Rel:     sqlgraph.M2O,
			Table:   "todos",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		spec.Edges.Add = append(spec.Edges.Add, edge)
	}
	if len(_u.modifiers) > 0 {
		spec.AddModifiers(_u.modifiers...)
	}
	affected, err := sqlgraph.UpdateNodes(ctx, _u.config.Driver, spec)
	if err != nil {
		return 0, runtime.MayWrapConstraintError(err)
	}
	return affected, nil
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TodoUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	hooks := _u.hooks
	return velox.WithHooks[int, TodoMutation, *TodoMutation](ctx, _u.sqlSave, _u.mutation, hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TodoUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TodoUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TodoUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// TodoUpdateOne is the update builder for a single Todo entity.
type TodoUpdateOne struct {
	config            runtime.Config
	mutation          *TodoMutation
	hooks             []runtime.Hook
	modifiers         []func(*sql.UpdateBuilder)
	selectFields      []string
	skipDefaults      bool
	skipDefaultFields map[string]struct{}
}

// NewTodoUpdateOne creates a new TodoUpdateOne builder.
func NewTodoUpdateOne(c runtime.Config, mutation *TodoMutation, hooks []runtime.Hook) *TodoUpdateOne {
	return &TodoUpdateOne{
		config:   c,
		hooks:    hooks,
		mutation: mutation,
	}
}

// Where appends a list predicates to the TodoUpdateOne builder.
func (_u *TodoUpdateOne) Where(ps ...predicate.Todo) *TodoUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema. It narrows
// only what is read back — every field set on this builder is still written.
func (_u *TodoUpdateOne) Select(field string, fields ...string) *TodoUpdateOne {
	_u.selectFields = append([]string{field}, fields...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TodoUpdateOne) SetUpdatedAt(v time.Time) *TodoUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *TodoUpdateOne) SetTitle(v string) *TodoUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TodoUpdateOne) SetNillableTitle(v *string) *TodoUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TodoUpdateOne) SetStatus(v todo.Status) *TodoUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TodoUpdateOne) SetNillableStatus(v *todo.Status) *TodoUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetOwnerID sets the "owner" edge by id.
func (_u *TodoUpdateOne) SetOwnerID(id int) *TodoUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetNillableOwnerID sets the "owner" edge by id if the given value is not nil.
func (_u *TodoUpdateOne) SetNillableOwnerID(id *int) *TodoUpdateOne {
	if id != nil {
		_u.SetOwnerID(*id)
	}
	return _u
}

// ClearOwner clears the "owner" edge.
func (_u *TodoUpdateOne) ClearOwner() *TodoUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// SetOwner sets the "owner" edge to the given entity.
func (_u *TodoUpdateOne) SetOwner(v *entity.User) *TodoUpdateOne {
	_u.SetOwnerID(v.ID)
	return _u
}

// Mutation returns the TodoMutation.
func (_u *TodoUpdateOne) Mutation() *TodoMutation {
	return _u.mutation
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TodoUpdateOne) Modify(modifiers ...func(*sql.UpdateBuilder)) *TodoUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

// check runs the user-defined validators on the fields this mutation sets
// and guards required unique edges against being cleared.
func (_u *TodoUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := todo.TitleValidator(v); err != nil {
			return &runtime.ValidationError{
				Entity: "Todo",
				Err:    fmt.Errorf("validator failed for field \"Todo.title\": %w", err),
				Field:  "title",
				Name:   "title",
			}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := todo.StatusValidator(v); err != nil {
			return &runtime.ValidationError{
				Entity: "Todo",
				Err:    fmt.Errorf("validator failed for field \"Todo.status\": %w", err),
				Field:  "status",
				Name:   "status",
			}
		}
	}
	if _u.mutation.OwnerCleared() {
		return errors.New("clearing a required unique edge \"Todo.owner\"")
	}
	return nil
}

// sqlSave executes the SQL update for a single Todo after hooks have run.
func (_u *TodoUpdateOne) sqlSave(ctx context.Context) (*entity.Todo, error) {
	if err := _u.check(); err != nil {
		return nil, err
	}
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, errors.New("velox: missing ID for UpdateOne")
	}
	spec := sqlgraph.NewUpdateSpec(todo.Table, todo.Columns, &sqlgraph.FieldSpec{
		Column: todo.FieldID,
		Type:   todoIDFieldType,
	})
	if _u.mutation._updated_at != nil {
		spec.SetField("updated_at", field.TypeTime, *_u.mutation._updated_at)
	}
	if _u.mutation._title != nil {
		spec.SetField("title", field.TypeString, *_u.mutation._title)
	}
	if _u.mutation._status != nil {
		spec.SetField("status", field.TypeEnum, *_u.mutation._status)
	}
	spec.Node.ID.Value = id
	ps := _u.mutation.PredicatesFuncs()
	spec.Predicate = func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(todo.FieldID), id))
		for i := range ps {
			ps[i](s)
		}
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"user_todos"},
			Inverse: true,
			Rel:     sqlgraph.M2O,
			Table:   "todos",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		spec.Edges.Clear = append(spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"user_todos"},
			Inverse: true,
			Rel:     sqlgraph.M2O,
			Table:   "todos",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		spec.Edges.Add = append(spec.Edges.Add, edge)
	}
	if len(_u.modifiers) > 0 {
		spec.AddModifiers(_u.modifiers...)
	}
	if err := sqlgraph.UpdateNode(ctx, _u.config.Driver, spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			return nil, velox.NewNotFoundError("Todo")
		}
		return nil, runtime.MayWrapConstraintError(err)
	}
	columns := todo.Columns
	if len(_u.selectFields) > 0 {
		columns = make([]string, 0, len(_u.selectFields)+1)
		columns = append(columns, todo.FieldID)
		for _, f := range _u.selectFields {
			if !todo.ValidColumn(f) {
				return nil, &runtime.ValidationError{
					Entity: "Todo",
					Err:    errors.New("invalid field for query"),
					Field:  f,
					Name:   f,
				}
			}
			if f != todo.FieldID {
				columns = append(columns, f)
			}
		}
	}
	build := func(_ context.Context) (*sql.Selector, error) {
		s := sql.Select(columns...).From(sql.Table(todo.Table))
		s.SetDialect(_u.config.Driver.Dialect())
		s.Where(sql.EQ(s.C(todo.FieldID), id))
		s.Limit(1)
		return s, nil
	}
	_node, err2 := runtime.ScanFirst[entity.Todo, *entity.Todo](ctx, _u.config.Driver, build, "Todo")
	if err2 != nil {
		return nil, err2
	}
	_node.SetConfig(_u.config)
	return _node, nil
}

// Save executes the query and returns the updated Todo entity.
func (_u *TodoUpdateOne) Save(ctx context.Context) (*entity.Todo, error) {
	_u.mutation.oldValue = func(ctx context.Context) (*entity.Todo, error) {
		id, ok := _u.mutation.ID()
		if !ok {
			return nil, errors.New("velox: missing ID for OldField")
		}
		build := func(_ context.Context) (*sql.Selector, error) {
			s := sql.Select(todo.Columns...).From(sql.Table(todo.Table))
			s.SetDialect(_u.config.Driver.Dialect())
			s.Where(sql.EQ(s.C(todo.FieldID), id))
			s.Limit(1)
			return s, nil
		}
		_old, err := runtime.ScanFirst[entity.Todo, *entity.Todo](ctx, _u.config.Driver, build, "Todo")
		if err != nil {
			return nil, err
		}
		_old.SetConfig(_u.config)
		return _old, nil
	}
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	hooks := _u.hooks
	return velox.WithHooks[*entity.Todo, TodoMutation, *TodoMutation](ctx, _u.sqlSave, _u.mutation, hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TodoUpdateOne) SaveX(ctx context.Context) *entity.Todo {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TodoUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TodoUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// todoWrapperUpdateDefaults applies update default values shared by TodoUpdate and TodoUpdateOne.
func todoWrapperUpdateDefaults(m *TodoMutation, skipDefaults bool, skipDefaultFields map[string]struct{}) {
	if skipDefaults {
		return
	}
	if _, ok := m.UpdatedAt(); !ok {
		if _, skip := skipDefaultFields["updated_at"]; !skip {
			v := todo.UpdateDefaultUpdatedAt()
			m.SetUpdatedAt(v)
		}
	}
}

// defaults sets the default values for TodoUpdate before save.
func (_u *TodoUpdate) defaults() error {
	todoWrapperUpdateDefaults(_u.mutation, _u.skipDefaults, _u.skipDefaultFields)
	return nil
}

// defaults sets the default values for TodoUpdateOne before save.
func (_u *TodoUpdateOne) defaults() error {
	todoWrapperUpdateDefaults(_u.mutation, _u.skipDefaults, _u.skipDefaultFields)
	return nil
}

// SkipDefaults skips all update default values on TodoUpdate.
func (_u *TodoUpdate) SkipDefaults() *TodoUpdate {
	_u.skipDefaults = true
	return _u
}

// SkipDefault skips a specific field's update default on TodoUpdate.
func (_u *TodoUpdate) SkipDefault(fields ...string) *TodoUpdate {
	if _u.skipDefaultFields == nil {
		_u.skipDefaultFields = make(map[string]struct{})
	}
	for _, f := range fields {
		_u.skipDefaultFields[f] = struct{}{}
	}
	return _u
}

// SkipDefaults skips all update default values on TodoUpdateOne.
func (_u *TodoUpdateOne) SkipDefaults() *TodoUpdateOne {
	_u.skipDefaults = true
	return _u
}

// SkipDefault skips a specific field's update default on TodoUpdateOne.
func (_u *TodoUpdateOne) SkipDefault(fields ...string) *TodoUpdateOne {
	if _u.skipDefaultFields == nil {
		_u.skipDefaultFields = make(map[string]struct{})
	}
	for _, f := range fields {
		_u.skipDefaultFields[f] = struct{}{}
	}
	return _u
}
