// Code generated by velox. DO NOT EDIT.

package stock

import "github.com/syssam/velox/runtime"

// StockCollectMeta holds GraphQL field collection metadata for Stock.
var StockCollectMeta runtime.CollectMeta

func init() {
	StockCollectMeta.FieldColumns = map[string]string{"quantity": FieldQuantity}
	StockCollectMeta.Edges = map[string]runtime.EdgeMeta{"warehouse": {
		FKColumns:   []string{"warehouse_stocks"},
		Inverse:     "stocks",
		Name:        "warehouse",
		PagesLoaded: false,
		Relay:       false,
		Target:      "warehouses",
		Unique:      true,
	}, "product": {
		FKColumns:   []string{"product_stocks"},
		Inverse:     "stocks",
		Name:        "product",
		PagesLoaded: false,
		Relay:       false,
		Target:      "products",
		Unique:      true,
	}}
}
