// Code generated by gqlc. DO NOT EDIT.

// Package stock holds the types generated from the GraphQL schema.
package stock

import (
	gqlrelay "github.com/syssam/velox/contrib/graphql/gqlrelay"
)

type StockOrderField string

const (
	StockOrderFieldQuantity StockOrderField = "QUANTITY"
)

type StockOrder struct {
	Direction gqlrelay.OrderDirection `graphql:"direction"`
	Field     StockOrderField         `graphql:"field"`
}
