// Code generated by velox. DO NOT EDIT.

package categoryclient

import (
	"context"
	"errors"
	"fmt"

	category "github.com/syssam/graphql-go/examples/veloxfx/velox/category"
	entity "github.com/syssam/graphql-go/examples/veloxfx/velox/entity"
	velox "github.com/syssam/velox"
	sqlgraph "github.com/syssam/velox/dialect/sql/sqlgraph"
	runtime "github.com/syssam/velox/runtime"
	field "github.com/syssam/velox/schema/field"
)

// categoryIDFieldType is the field.Type for Category's primary key column.
var categoryIDFieldType = field.TypeInt

// categoryFieldTypes maps column names to field.Type for Category.
var categoryFieldTypes = map[string]field.Type{"id": field.TypeInt, "name": field.TypeString}

// CategoryCreate is the builder for creating a Category entity.
type CategoryCreate struct {
	config   runtime.Config
	mutation *CategoryMutation
	hooks    []runtime.Hook
}

// NewCategoryCreate creates a new CategoryCreate builder.
func NewCategoryCreate(c runtime.Config, mutation *CategoryMutation, hooks []runtime.Hook) *CategoryCreate {
	return &CategoryCreate{
		config:   c,
		hooks:    hooks,
		mutation: mutation,
	}
}

// SetName sets the "name" field.
func (c *CategoryCreate) SetName(v string) *CategoryCreate {
	c.mutation.SetName(v)
	return c
}

// AddProductIDs adds the "products" edge by ids.
func (c *CategoryCreate) AddProductIDs(ids ...int) *CategoryCreate {
	c.mutation.AddProductIDs(ids...)
	return c
}

// AddProducts adds the "products" edge to the given entities.
func (c *CategoryCreate) AddProducts(v ...*entity.Product) *CategoryCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	c.AddProductIDs(ids...)
	return c
}

// Mutation returns the CategoryMutation.
func (c *CategoryCreate) Mutation() *CategoryMutation {
	return c.mutation
}

// check runs all checks and user-defined validators on the builder.
func (c *CategoryCreate) check() error {
	if _, ok := c.mutation.Name(); !ok {
		return &runtime.ValidationError{
			Entity: "Category",
			Err:    errors.New("missing required field \"Category.name\""),
			Field:  "name",
			Name:   "name",
		}
	}
	if v, ok := c.mutation.Name(); ok {
		if err := category.NameValidator(v); err != nil {
			return &runtime.ValidationError{
				Entity: "Category",
				Err:    fmt.Errorf("validator failed for field \"Category.name\": %w", err),
				Field:  "name",
				Name:   "name",
			}
		}
	}
	return nil
}

// sqlSave executes the SQL create for Category after hooks have run.
func (c *CategoryCreate) sqlSave(ctx context.Context) (*entity.Category, error) {
	if err := c.check(); err != nil {
		return nil, err
	}
	_node, _spec := c.createSpec()
	if err := sqlgraph.CreateNode(ctx, c.config.Driver, _spec); err != nil {
		return nil, runtime.MayWrapConstraintError(err)
	}
	_node.SetConfig(c.config)
	if _spec.ID.Value != nil {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	c.mutation.SetID(_node.ID)
	return _node, nil
}

// createSpec builds the Category node and sqlgraph.CreateSpec from mutation fields.
func (c *CategoryCreate) createSpec() (*entity.Category, *sqlgraph.CreateSpec) {
	var (
		_node = &entity.Category{}
		_spec = sqlgraph.NewCreateSpec(category.Table, &sqlgraph.FieldSpec{
			Column: category.FieldID,
			Type:   categoryIDFieldType,
		})
	)
	if c.mutation._name != nil {
		v := *c.mutation._name
		_spec.SetField("name", field.TypeString, v)
		_node.Name = v
	}
	if nodes := c.mutation.ProductsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"category_products"},
			Inverse: false,
			Rel:     sqlgraph.O2M,
			Table:   "products",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// Save creates the Category in the database.
func (c *CategoryCreate) Save(ctx context.Context) (*entity.Category, error) {
	hooks := c.hooks
	return velox.WithHooks[*entity.Category, CategoryMutation, *CategoryMutation](ctx, c.sqlSave, c.mutation, hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (c *CategoryCreate) SaveX(ctx context.Context) *entity.Category {
	v, err := c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (c *CategoryCreate) Exec(ctx context.Context) error {
	_, err := c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (c *CategoryCreate) ExecX(ctx context.Context) {
	if err := c.Exec(ctx); err != nil {
		panic(err)
	}
}

// CategoryCreateBulk is the builder for creating many Category entities in bulk.
type CategoryCreateBulk struct {
	config    runtime.Config
	err       error
	builders  []*CategoryCreate
	batchSize int
}

// NewCategoryCreateBulk creates a new CategoryCreateBulk builder.
func NewCategoryCreateBulk(c runtime.Config, builders []*CategoryCreate) *CategoryCreateBulk {
	return &CategoryCreateBulk{
		builders: builders,
		config:   c,
	}
}

// BatchSize sets the chunk size for the bulk insert.
// A value of 0 (default) means no chunking — all builders
// go through a single BatchCreate. When set, Save splits the
// builders into chunks of at most n and runs one INSERT per
// chunk. Use this to stay under SQLite's SQL-variable cap.
//
// Atomicity across chunks is NOT automatic. Wrap the call
// in client.Tx(ctx) if you need all-or-nothing semantics.
func (_cb *CategoryCreateBulk) BatchSize(n int) *CategoryCreateBulk {
	_cb.batchSize = n
	return _cb
}

// Save creates the Category entities in the database.
//
// When BatchSize is 0 (default), all builders go through a
// single mutator chain ending in one BatchCreate. When
// BatchSize > 0, the builders are sliced into chunks of at
// most N and each chunk runs its own mutator chain + one
// INSERT. A mid-loop error returns the rows persisted so far
// together with the error — wrap in client.Tx(ctx) for
// all-or-nothing semantics.
func (_cb *CategoryCreateBulk) Save(ctx context.Context) ([]*entity.Category, error) {
	if _cb.err != nil {
		return nil, _cb.err
	}
	if _cb.batchSize <= 0 || _cb.batchSize >= len(_cb.builders) {
		return _cb.saveChunk(ctx, _cb.builders)
	}
	nodes := make([]*entity.Category, 0, len(_cb.builders))
	for start := 0; start < len(_cb.builders); start += _cb.batchSize {
		end := start + _cb.batchSize
		if end > len(_cb.builders) {
			end = len(_cb.builders)
		}
		chunk, err := _cb.saveChunk(ctx, _cb.builders[start:end])
		nodes = append(nodes, chunk...)
		if err != nil {
			return nodes, err
		}
	}
	return nodes, nil
}

// saveChunk runs one mutator chain over a sub-slice of the builders.
func (_cb *CategoryCreateBulk) saveChunk(ctx context.Context, builders []*CategoryCreate) ([]*entity.Category, error) {
	if len(builders) == 0 {
		return []*entity.Category{}, nil
	}
	specs := make([]*sqlgraph.CreateSpec, len(builders))
	nodes := make([]*entity.Category, len(builders))
	mutators := make([]runtime.Mutator, len(builders))
	for i := range builders {
		func(i int, root context.Context) {
			builder := builders[i]
			var mut runtime.Mutator = runtime.MutateFunc(func(ctx context.Context, m runtime.Mutation) (runtime.Value, error) {
				mutation, ok := m.(*CategoryMutation)
				if !ok {
					return nil, fmt.Errorf("velox: unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				nodes[i].SetConfig(_cb.config)
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					if err = sqlgraph.BatchCreate(ctx, _cb.config.Driver, spec); err != nil {
						err = runtime.MayWrapConstraintError(err)
					}
				}
				if err != nil {
					return nil, err
				}
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
					mutation.SetID(int(id))
				}
				return nodes[i], nil
			})
			allHooks := builder.hooks
			for j := len(allHooks) - 1; j >= 0; j-- {
				mut = allHooks[j](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_cb *CategoryCreateBulk) SaveX(ctx context.Context) []*entity.Category {
	v, err := _cb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_cb *CategoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _cb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_cb *CategoryCreateBulk) ExecX(ctx context.Context) {
	if err := _cb.Exec(ctx); err != nil {
		panic(err)
	}
}
