// Code generated by velox. DO NOT EDIT.

package categoryclient

// CreateCategoryInput represents a mutation input for creating categorys.
type CreateCategoryInput struct {
	Name       string `json:"name"`
	ProductIDs []int  `json:"productIDs,omitempty"`
}

// Mutate applies the CreateCategoryInput on the CategoryMutation builder.
func (i *CreateCategoryInput) Mutate(m *CategoryMutation) {
	m.SetName(i.Name)
	if len(i.ProductIDs) > 0 {
		m.AddProductIDs(i.ProductIDs...)
	}
}

// SetInput applies the change-set in the CreateCategoryInput on the CategoryCreate builder.
func (c *CategoryCreate) SetInput(i CreateCategoryInput) *CategoryCreate {
	i.Mutate(c.Mutation())
	return c
}
