// Code generated by velox. DO NOT EDIT.

package categoryclient

import (
	"context"
	"fmt"

	entity "github.com/syssam/graphql-go/examples/veloxfx/velox/entity"
	predicate "github.com/syssam/graphql-go/examples/veloxfx/velox/predicate"
	velox "github.com/syssam/velox"
	sql "github.com/syssam/velox/dialect/sql"
	runtime "github.com/syssam/velox/runtime"
)

// CategoryMutation represents an operation that mutates the Category nodes in the graph.
type CategoryMutation struct {
	config          runtime.Config
	op              runtime.Op
	id              *int
	_name           *string
	clearedFields   map[string]struct{}
	oldValue        func(context.Context) (*entity.Category, error)
	oldLoaded       bool
	oldCache        *entity.Category
	done            bool
	products        map[int]struct{}
	removedProducts map[int]struct{}
	clearedProducts bool
	predicates      []predicate.Category
}

var _ velox.Mutation = (*CategoryMutation)(nil)

// categoryOption allows management of the mutation configuration using functional options.
type categoryOption func(*CategoryMutation)

// NewCategoryMutation creates new mutation for the Category entity.
func NewCategoryMutation(c runtime.Config, op runtime.Op, opts ...categoryOption) *CategoryMutation {
	m := &CategoryMutation{
		config: c,
		op:     runtime.Op(op),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// Op returns the operation name.
func (m *CategoryMutation) Op() runtime.Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *CategoryMutation) SetOp(op runtime.Op) {
	m.op = op
}

// Type returns the schema type name of this mutation ("Category").
func (m *CategoryMutation) Type() string {
	return "Category"
}

// ID returns the ID value in the mutation, if it was provided by the caller.
// The second bool return indicates whether the ID field was set.
func (m *CategoryMutation) ID() (id any, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetID sets the entity ID value on the mutation.
func (m *CategoryMutation) SetID(id int) {
	m.id = &id
}

// loadOld lazily loads the pre-mutation entity state for OldXxx methods.
func (m *CategoryMutation) loadOld(ctx context.Context) (*entity.Category, error) {
	if m.op != runtime.OpUpdateOne {
		return nil, fmt.Errorf("OldField is only allowed on UpdateOne operations")
	}
	if m.oldValue == nil {
		return nil, fmt.Errorf("OldField is not supported: no old value loader configured")
	}
	if m.oldLoaded {
		return m.oldCache, nil
	}
	if m.done {
		return nil, fmt.Errorf("%w: call Category.OldXxx in the hook before next.Mutate", runtime.ErrOldValueAfterMutation)
	}
	old, err := m.oldValue(ctx)
	if err != nil {
		return nil, fmt.Errorf("querying old values: %w", err)
	}
	m.oldCache = old
	m.oldLoaded = true
	return old, nil
}

// Where appends a list predicates to the CategoryMutation builder.
func (m *CategoryMutation) Where(ps ...predicate.Category) {
	m.predicates = append(m.predicates, ps...)
}

// PredicatesFuncs returns the predicates as untyped selector functions.
func (m *CategoryMutation) PredicatesFuncs() []func(*sql.Selector) {
	ps := make([]func(*sql.Selector), len(m.predicates))
	for i, p := range m.predicates {
		ps[i] = p
	}
	return ps
}

// SetName sets the "name" field.
func (m *CategoryMutation) SetName(v string) {
	m._name = &v
}

// Name returns the value of the "name" field in the mutation.
func (m *CategoryMutation) Name() (r string, exists bool) {
	if m._name == nil {
		return
	}
	return *m._name, true
}

// ResetName resets all changes to the "name" field.
func (m *CategoryMutation) ResetName() {
	m._name = nil
	delete(m.clearedFields, "name")
}

// AddProductIDs adds the "products" edge to the Product entity by ids.
func (m *CategoryMutation) AddProductIDs(ids ...int) {
	if m.products == nil {
		m.products = make(map[int]struct{})
	}
	for _, id := range ids {
		m.products[id] = struct{}{}
	}
}

// RemoveProductIDs removes the "products" edge to the Product entity by ids.
func (m *CategoryMutation) RemoveProductIDs(ids ...int) {
	if m.removedProducts == nil {
		m.removedProducts = make(map[int]struct{})
	}
	for _, id := range ids {
		delete(m.products, id)
		m.removedProducts[id] = struct{}{}
	}
}

// ClearProducts clears the "products" edge.
func (m *CategoryMutation) ClearProducts() {
	m.clearedProducts = true
}

// ProductsCleared reports if the "products" edge was cleared.
func (m *CategoryMutation) ProductsCleared() bool {
	return m.clearedProducts
}

// RemovedProductsIDs returns the removed IDs of the "products" edge.
func (m *CategoryMutation) RemovedProductsIDs() (ids []int) {
	for id := range m.removedProducts {
		ids = append(ids, id)
	}
	return
}

// ResetProducts resets all changes to the "products" edge.
func (m *CategoryMutation) ResetProducts() {
	m.products = nil
	m.clearedProducts = false
	m.removedProducts = nil
}

// ProductsIDs returns the "products" edge IDs in the mutation.
func (m *CategoryMutation) ProductsIDs() (ids []int) {
	for id := range m.products {
		ids = append(ids, id)
	}
	return
}

// Fields returns all fields that were changed during this mutation.
func (m *CategoryMutation) Fields() []string {
	var fields []string
	if m._name != nil {
		fields = append(fields, "name")
	}
	return fields
}

// Field returns the value of a field with the given name.
func (m *CategoryMutation) Field(name string) (runtime.Value, bool) {
	switch name {
	case "name":
		if m._name != nil {
			return *m._name, true
		}
	}
	return nil, false
}

// SetField sets the value of a field with the given name. It returns an error if the field is not defined in the schema, or if the value type does not match.
func (m *CategoryMutation) SetField(name string, value runtime.Value) error {
	switch name {
	case "name":
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field name", value)
		}
		m.SetName(v)
		return nil
	default:
		return fmt.Errorf("unknown Category field %s", name)
	}
}

// AddedFields returns all numeric fields that were incremented or decremented during this mutation.
func (m *CategoryMutation) AddedFields() []string {
	var fields []string
	return fields
}

// AddedField returns the numeric value that was incremented or decremented for a field.
func (m *CategoryMutation) AddedField(name string) (runtime.Value, bool) {
	switch name {
	}
	return nil, false
}

// AddField adds the value for the given name. It returns an error if the field is not defined in the schema, or if the value type does not match.
func (m *CategoryMutation) AddField(name string, value runtime.Value) error {
	switch name {
	default:
		return fmt.Errorf("unknown Category addable field %s", name)
	}
}

// ClearedFields returns all fields that were cleared during this mutation.
func (m *CategoryMutation) ClearedFields() []string {
	var fields []string
	for f := range m.clearedFields {
		fields = append(fields, f)
	}
	return fields
}

// FieldCleared reports if a field with the given name was cleared in this mutation.
func (m *CategoryMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an error if the field is not defined in the schema or is not nullable.
func (m *CategoryMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Category nullable field %s", name)
}

// ResetField resets all changes for the field with the given name. It returns an error if the field is not defined in the schema.
func (m *CategoryMutation) ResetField(name string) error {
	switch name {
	case "name":
		m._name = nil
		delete(m.clearedFields, "name")
	default:
		return fmt.Errorf("unknown Category field %s", name)
	}
	return nil
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *CategoryMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.products != nil {
		edges = append(edges, "products")
	}
	return edges
}

// AddedIDs returns all IDs that were added for the given edge name.
func (m *CategoryMutation) AddedIDs(name string) []velox.Value {
	switch name {
	case "products":
		ids := make([]velox.Value, 0, len(m.products))
		for id := range m.products {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *CategoryMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedProducts != nil {
		edges = append(edges, "products")
	}
	return edges
}

// RemovedIDs returns all IDs that were removed for the given edge name.
func (m *CategoryMutation) RemovedIDs(name string) []velox.Value {
	switch name {
	case "products":
		ids := make([]velox.Value, 0, len(m.removedProducts))
		for id := range m.removedProducts {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *CategoryMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedProducts {
		edges = append(edges, "products")
	}
	return edges
}

// EdgeCleared reports if the given edge was cleared in this mutation.
func (m *CategoryMutation) EdgeCleared(name string) bool {
	switch name {
	case "products":
		return m.clearedProducts
	}
	return false
}

// ClearEdge clears the value of the edge with the given name.
func (m *CategoryMutation) ClearEdge(name string) error {
	switch name {
	case "products":
		m.ClearProducts()
		return nil
	}
	return fmt.Errorf("unknown Category edge %s", name)
}

// ResetEdge resets all changes for the edge with the given name.
func (m *CategoryMutation) ResetEdge(name string) error {
	switch name {
	case "products":
		m.ResetProducts()
		return nil
	}
	return fmt.Errorf("unknown Category edge %s", name)
}

// OldField returns the old value of a field from the database.
// An error is returned if the mutation operation is not UpdateOne,
// or the query to the database fails.
func (m *CategoryMutation) OldField(ctx context.Context, name string) (velox.Value, error) {
	switch name {
	case "name":
		return m.OldName(ctx)
	}
	return nil, fmt.Errorf("unknown Category field %s", name)
}

// OldName returns the old "name" field value, if exists.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CategoryMutation) OldName(ctx context.Context) (v string, err error) {
	old, loadErr := m.loadOld(ctx)
	if loadErr != nil {
		err = loadErr
		return
	}
	v = old.Name
	return
}
