// Code generated by velox. DO NOT EDIT.

package categoryclient

import (
	"context"
	"errors"
	"fmt"

	schema "github.com/syssam/graphql-go/examples/veloxfx/schema"
	category "github.com/syssam/graphql-go/examples/veloxfx/velox/category"
	runtime "github.com/syssam/velox/runtime"
)

// The init function reads schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to the package variables.
func init() {
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescName is the schema descriptor for name field.
	categoryDescName := categoryFields[0].Descriptor()
	// category.NameValidator is a validator for the "name" field. It is called by the builders before save.
	category.NameValidator = categoryDescName.Validators[0].(func(string) error)
	runtime.RegisterEntity(runtime.EntityRegistration{
		Mutator: func(ctx context.Context, cfg runtime.Config, m any) (any, error) {
			return NewCategoryClient(cfg).mutate(ctx, m.(*CategoryMutation))
		},
		Name:        "Category",
		Table:       category.Table,
		ValidColumn: category.ValidColumn,
	})
	runtime.RegisterNodeResolver(category.Table, runtime.NodeResolver{
		Resolve: func(ctx context.Context, id any) (any, error) {
			cfg := runtime.ConfigFromContext(ctx)
			if cfg.Driver == nil {
				return nil, errors.New("velox: NodeResolver requires Config in context — call client.Noder so cfg is propagated")
			}
			typedID, ok := id.(int)
			if !ok {
				return nil, fmt.Errorf("%w: unexpected id type %T", runtime.ErrNodeIDTypeMismatch, id)
			}
			return NewCategoryClient(cfg).Get(ctx, typedID)
		},
		Type: "Category",
	})
}
