// Code generated by velox. DO NOT EDIT.

package orderitemclient

import (
	"context"
	"errors"
	"fmt"

	entity "github.com/syssam/graphql-go/examples/veloxfx/velox/entity"
	orderitem "github.com/syssam/graphql-go/examples/veloxfx/velox/orderitem"
	velox "github.com/syssam/velox"
	sqlgraph "github.com/syssam/velox/dialect/sql/sqlgraph"
	runtime "github.com/syssam/velox/runtime"
	field "github.com/syssam/velox/schema/field"
)

// orderItemIDFieldType is the field.Type for OrderItem's primary key column.
var orderItemIDFieldType = field.TypeInt

// orderItemFieldTypes maps column names to field.Type for OrderItem.
var orderItemFieldTypes = map[string]field.Type{"id": field.TypeInt, "quantity": field.TypeInt, "unit_price_cents": field.TypeInt}

// OrderItemCreate is the builder for creating a OrderItem entity.
type OrderItemCreate struct {
	config   runtime.Config
	mutation *OrderItemMutation
	hooks    []runtime.Hook
}

// NewOrderItemCreate creates a new OrderItemCreate builder.
func NewOrderItemCreate(c runtime.Config, mutation *OrderItemMutation, hooks []runtime.Hook) *OrderItemCreate {
	return &OrderItemCreate{
		config:   c,
		hooks:    hooks,
		mutation: mutation,
	}
}

// SetQuantity sets the "quantity" field.
func (c *OrderItemCreate) SetQuantity(v int) *OrderItemCreate {
	c.mutation.SetQuantity(v)
	return c
}

// SetUnitPriceCents sets the "unit_price_cents" field.
func (c *OrderItemCreate) SetUnitPriceCents(v int) *OrderItemCreate {
	c.mutation.SetUnitPriceCents(v)
	return c
}

// SetOrderID sets the "order" edge by id.
func (c *OrderItemCreate) SetOrderID(id int) *OrderItemCreate {
	c.mutation.SetOrderID(id)
	return c
}

// SetNillableOrderID sets the "order" edge by id if the given value is not nil.
func (c *OrderItemCreate) SetNillableOrderID(id *int) *OrderItemCreate {
	if id != nil {
		c.SetOrderID(*id)
	}
	return c
}

// SetProductID sets the "product" edge by id.
func (c *OrderItemCreate) SetProductID(id int) *OrderItemCreate {
	c.mutation.SetProductID(id)
	return c
}

// SetNillableProductID sets the "product" edge by id if the given value is not nil.
func (c *OrderItemCreate) SetNillableProductID(id *int) *OrderItemCreate {
	if id != nil {
		c.SetProductID(*id)
	}
	return c
}

// SetOrder sets the "order" edge to the given entity.
func (c *OrderItemCreate) SetOrder(v *entity.Order) *OrderItemCreate {
	c.SetOrderID(v.ID)
	return c
}

// SetProduct sets the "product" edge to the given entity.
func (c *OrderItemCreate) SetProduct(v *entity.Product) *OrderItemCreate {
	c.SetProductID(v.ID)
	return c
}

// Mutation returns the OrderItemMutation.
func (c *OrderItemCreate) Mutation() *OrderItemMutation {
	return c.mutation
}

// check runs all checks and user-defined validators on the builder.
func (c *OrderItemCreate) check() error {
	if _, ok := c.mutation.Quantity(); !ok {
		return &runtime.ValidationError{
			Entity: "OrderItem",
			Err:    errors.New("missing required field \"OrderItem.quantity\""),
			Field:  "quantity",
			Name:   "quantity",
		}
	}
	if v, ok := c.mutation.Quantity(); ok {
		if err := orderitem.QuantityValidator(v); err != nil {
			return &runtime.ValidationError{
				Entity: "OrderItem",
				Err:    fmt.Errorf("validator failed for field \"OrderItem.quantity\": %w", err),
				Field:  "quantity",
				Name:   "quantity",
			}
		}
	}
	if _, ok := c.mutation.UnitPriceCents(); !ok {
		return &runtime.ValidationError{
			Entity: "OrderItem",
			Err:    errors.New("missing required field \"OrderItem.unit_price_cents\""),
			Field:  "unit_price_cents",
			Name:   "unit_price_cents",
		}
	}
	if v, ok := c.mutation.UnitPriceCents(); ok {
		if err := orderitem.UnitPriceCentsValidator(v); err != nil {
			return &runtime.ValidationError{
				Entity: "OrderItem",
				Err:    fmt.Errorf("validator failed for field \"OrderItem.unit_price_cents\": %w", err),
				Field:  "unit_price_cents",
				Name:   "unit_price_cents",
			}
		}
	}
	if len(c.mutation.OrderIDs()) == 0 {
		return &runtime.ValidationError{
			Entity: "OrderItem",
			Err:    errors.New("missing required edge \"OrderItem.order\""),
			Field:  "order",
			Name:   "order",
		}
	}
	if len(c.mutation.ProductIDs()) == 0 {
		return &runtime.ValidationError{
			Entity: "OrderItem",
			Err:    errors.New("missing required edge \"OrderItem.product\""),
			Field:  "product",
			Name:   "product",
		}
	}
	return nil
}

// sqlSave executes the SQL create for OrderItem after hooks have run.
func (c *OrderItemCreate) sqlSave(ctx context.Context) (*entity.OrderItem, error) {
	if err := c.check(); err != nil {
		return nil, err
	}
	_node, _spec := c.createSpec()
	if err := sqlgraph.CreateNode(ctx, c.config.Driver, _spec); err != nil {
		return nil, runtime.MayWrapConstraintError(err)
	}
	_node.SetConfig(c.config)
	if _spec.ID.Value != nil {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	c.mutation.SetID(_node.ID)
	return _node, nil
}

// createSpec builds the OrderItem node and sqlgraph.CreateSpec from mutation fields.
func (c *OrderItemCreate) createSpec() (*entity.OrderItem, *sqlgraph.CreateSpec) {
	var (
		_node = &entity.OrderItem{}
		_spec = sqlgraph.NewCreateSpec(orderitem.Table, &sqlgraph.FieldSpec{
			Column: orderitem.FieldID,
			Type:   orderItemIDFieldType,
		})
	)
	if c.mutation._quantity != nil {
		v := *c.mutation._quantity
		_spec.SetField("quantity", field.TypeInt, v)
		_node.Quantity = v
	}
	if c.mutation._unit_price_cents != nil {
		v := *c.mutation._unit_price_cents
		_spec.SetField("unit_price_cents", field.TypeInt, v)
		_node.UnitPriceCents = v
	}
	if nodes := c.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"order_items"},
			Inverse: true,
			Rel:     sqlgraph.M2O,
			Table:   "order_items",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := c.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"product_order_items"},
			Inverse: true,
			Rel:     sqlgraph.M2O,
			Table:   "order_items",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// Save creates the OrderItem in the database.
func (c *OrderItemCreate) Save(ctx context.Context) (*entity.OrderItem, error) {
	hooks := c.hooks
	return velox.WithHooks[*entity.OrderItem, OrderItemMutation, *OrderItemMutation](ctx, c.sqlSave, c.mutation, hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (c *OrderItemCreate) SaveX(ctx context.Context) *entity.OrderItem {
	v, err := c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (c *OrderItemCreate) Exec(ctx context.Context) error {
	_, err := c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (c *OrderItemCreate) ExecX(ctx context.Context) {
	if err := c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OrderItemCreateBulk is the builder for creating many OrderItem entities in bulk.
type OrderItemCreateBulk struct {
	config    runtime.Config
	err       error
	builders  []*OrderItemCreate
	batchSize int
}

// NewOrderItemCreateBulk creates a new OrderItemCreateBulk builder.
func NewOrderItemCreateBulk(c runtime.Config, builders []*OrderItemCreate) *OrderItemCreateBulk {
	return &OrderItemCreateBulk{
		builders: builders,
		config:   c,
	}
}

// BatchSize sets the chunk size for the bulk insert.
// A value of 0 (default) means no chunking — all builders
// go through a single BatchCreate. When set, Save splits the
// builders into chunks of at most n and runs one INSERT per
// chunk. Use this to stay under SQLite's SQL-variable cap.
//
// Atomicity across chunks is NOT automatic. Wrap the call
// in client.Tx(ctx) if you need all-or-nothing semantics.
func (_cb *OrderItemCreateBulk) BatchSize(n int) *OrderItemCreateBulk {
	_cb.batchSize = n
	return _cb
}

// Save creates the OrderItem entities in the database.
//
// When BatchSize is 0 (default), all builders go through a
// single mutator chain ending in one BatchCreate. When
// BatchSize > 0, the builders are sliced into chunks of at
// most N and each chunk runs its own mutator chain + one
// INSERT. A mid-loop error returns the rows persisted so far
// together with the error — wrap in client.Tx(ctx) for
// all-or-nothing semantics.
func (_cb *OrderItemCreateBulk) Save(ctx context.Context) ([]*entity.OrderItem, error) {
	if _cb.err != nil {
		return nil, _cb.err
	}
	if _cb.batchSize <= 0 || _cb.batchSize >= len(_cb.builders) {
		return _cb.saveChunk(ctx, _cb.builders)
	}
	nodes := make([]*entity.OrderItem, 0, len(_cb.builders))
	for start := 0; start < len(_cb.builders); start += _cb.batchSize {
		end := start + _cb.batchSize
		if end > len(_cb.builders) {
			end = len(_cb.builders)
		}
		chunk, err := _cb.saveChunk(ctx, _cb.builders[start:end])
		nodes = append(nodes, chunk...)
		if err != nil {
			return nodes, err
		}
	}
	return nodes, nil
}

// saveChunk runs one mutator chain over a sub-slice of the builders.
func (_cb *OrderItemCreateBulk) saveChunk(ctx context.Context, builders []*OrderItemCreate) ([]*entity.OrderItem, error) {
	if len(builders) == 0 {
		return []*entity.OrderItem{}, nil
	}
	specs := make([]*sqlgraph.CreateSpec, len(builders))
	nodes := make([]*entity.OrderItem, len(builders))
	mutators := make([]runtime.Mutator, len(builders))
	for i := range builders {
		func(i int, root context.Context) {
			builder := builders[i]
			allHooks := builder.hooks
			var mut runtime.Mutator = runtime.MutateFunc(func(ctx context.Context, m runtime.Mutation) (runtime.Value, error) {
				mutation, ok := m.(*OrderItemMutation)
				if !ok {
					return nil, fmt.Errorf("velox: unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				nodes[i].SetConfig(_cb.config)
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					if err = sqlgraph.BatchCreate(ctx, _cb.config.Driver, spec); err != nil {
						err = runtime.MayWrapConstraintError(err)
					}
				}
				if err != nil {
					return nil, err
				}
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
					mutation.SetID(int(id))
				}
				return nodes[i], nil
			})
			for j := len(allHooks) - 1; j >= 0; j-- {
				mut = allHooks[j](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_cb *OrderItemCreateBulk) SaveX(ctx context.Context) []*entity.OrderItem {
	v, err := _cb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_cb *OrderItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _cb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_cb *OrderItemCreateBulk) ExecX(ctx context.Context) {
	if err := _cb.Exec(ctx); err != nil {
		panic(err)
	}
}
