// Code generated by gqlc. DO NOT EDIT.

// Package customer holds the generated GraphQL bindings for the customer group.
package customer

import (
	"context"

	"github.com/syssam/graphql-go"
	customer "github.com/syssam/graphql-go/examples/veloxfx/velox/client/customer"
	entity "github.com/syssam/graphql-go/examples/veloxfx/velox/entity"
)

type CreateCustomerArgs struct {
	Input customer.CreateCustomerInput `graphql:"input"`
}

// Resolver holds methods for fields that are not struct data.
type Resolver interface {
	CustomerID(ctx context.Context, obj *entity.Customer) (graphql.ID, error)
	CreateCustomer(ctx context.Context, args CreateCustomerArgs) (*entity.Customer, error)
	Customers(ctx context.Context) ([]*entity.Customer, error)
}

func Bindings(r Resolver) graphql.SchemaOption {
	return graphql.Options(
		graphql.Input[customer.CreateCustomerInput]("CreateCustomerInput", graphql.ZeroForNull()),
		graphql.Object[entity.Customer]("Customer",
			graphql.Resolve("id", func(ctx context.Context, v *entity.Customer) (graphql.ID, error) { return r.CustomerID(ctx, v) }),
			graphql.Field("name", func(v *entity.Customer) string { return v.Name }),
			graphql.Field("email", func(v *entity.Customer) string { return v.Email }),
			graphql.Resolve("orders", func(ctx context.Context, v *entity.Customer) ([]*entity.Order, error) { return v.Orders(ctx) }),
		),
		graphql.Query(
			graphql.Resolve("customers", func(ctx context.Context, _ graphql.Root) ([]*entity.Customer, error) { return r.Customers(ctx) }),
		),
		graphql.Mutation(
			graphql.ResolveArgs("createCustomer", func(ctx context.Context, _ graphql.Root, a CreateCustomerArgs) (*entity.Customer, error) {
				return r.CreateCustomer(ctx, a)
			}),
		),
		graphql.Args[CreateCustomerArgs](),
	)
}
