// Code generated by gqlc. DO NOT EDIT.

// Package category holds the generated GraphQL bindings for the category group.
package category

import (
	"context"

	"github.com/syssam/graphql-go"
	category "github.com/syssam/graphql-go/examples/veloxfx/velox/client/category"
	entity "github.com/syssam/graphql-go/examples/veloxfx/velox/entity"
)

type CreateCategoryArgs struct {
	Input category.CreateCategoryInput `graphql:"input"`
}

// Resolver holds methods for fields that are not struct data.
type Resolver interface {
	CategoryID(ctx context.Context, obj *entity.Category) (graphql.ID, error)
	CreateCategory(ctx context.Context, args CreateCategoryArgs) (*entity.Category, error)
	Categories(ctx context.Context) ([]*entity.Category, error)
}

func Bindings(r Resolver) graphql.SchemaOption {
	return graphql.Options(
		graphql.Input[category.CreateCategoryInput]("CreateCategoryInput", graphql.ZeroForNull()),
		graphql.Object[entity.Category]("Category",
			graphql.Resolve("id", func(ctx context.Context, v *entity.Category) (graphql.ID, error) { return r.CategoryID(ctx, v) }),
			graphql.Field("name", func(v *entity.Category) string { return v.Name }),
			graphql.Resolve("products", func(ctx context.Context, v *entity.Category) ([]*entity.Product, error) { return v.Products(ctx) }),
		),
		graphql.Query(
			graphql.Resolve("categories", func(ctx context.Context, _ graphql.Root) ([]*entity.Category, error) { return r.Categories(ctx) }),
		),
		graphql.Mutation(
			graphql.ResolveArgs("createCategory", func(ctx context.Context, _ graphql.Root, a CreateCategoryArgs) (*entity.Category, error) {
				return r.CreateCategory(ctx, a)
			}),
		),
		graphql.Args[CreateCategoryArgs](),
	)
}
