// Code generated by gqlc. DO NOT EDIT.

// Package category holds the generated GraphQL bindings for the category group.
package category

import (
	"context"

	"github.com/syssam/graphql-go"
	category "github.com/syssam/graphql-go/examples/veloxfx/velox/client/category"
	entity "github.com/syssam/graphql-go/examples/veloxfx/velox/entity"
	filter "github.com/syssam/graphql-go/examples/veloxfx/velox/filter"
	gqlrelay "github.com/syssam/velox/contrib/graphql/gqlrelay"
)

type CategoryProductsArgs struct {
	After   *gqlrelay.Cursor          `graphql:"after"`
	First   *int                      `graphql:"first"`
	Before  *gqlrelay.Cursor          `graphql:"before"`
	Last    *int                      `graphql:"last"`
	OrderBy *entity.ProductOrder      `graphql:"orderBy"`
	Where   *filter.ProductWhereInput `graphql:"where"`
}

type CreateCategoryArgs struct {
	Input category.CreateCategoryInput `graphql:"input"`
}

type UpdateCategoryArgs struct {
	ID    int                          `graphql:"id"`
	Input category.UpdateCategoryInput `graphql:"input"`
}

type DeleteCategoryArgs struct {
	ID int `graphql:"id"`
}

type CategoryArgs struct {
	ID int `graphql:"id"`
}

// Resolver has a method for each field no Go value answers by itself: every
// root field, and each field not bound to a struct field or method.
type Resolver interface {
	// CreateCategory resolves Mutation.createCategory.
	CreateCategory(ctx context.Context, args CreateCategoryArgs) (*entity.Category, error)
	// UpdateCategory resolves Mutation.updateCategory.
	UpdateCategory(ctx context.Context, args UpdateCategoryArgs) (*entity.Category, error)
	// DeleteCategory resolves Mutation.deleteCategory.
	//
	// Deletes the Category and returns its id. Refused while other rows refer to it.
	DeleteCategory(ctx context.Context, args DeleteCategoryArgs) (int, error)
	// Categories resolves Query.categories.
	Categories(ctx context.Context) ([]*entity.Category, error)
	// Category resolves Query.category.
	//
	// The Category with this id, or null if there is none.
	Category(ctx context.Context, args CategoryArgs) (*entity.Category, error)
}

// Bindings registers the category group's types and fields, calling r for each
// Resolver method. Building a schema never calls r, which is why
// ValidateSchema can pass nil.
func Bindings(r Resolver) graphql.SchemaOption {
	return graphql.Options(
		graphql.Input[filter.CategoryWhereInput]("CategoryWhereInput", graphql.ZeroForNull()),
		graphql.Input[category.CreateCategoryInput]("CreateCategoryInput", graphql.ZeroForNull()),
		graphql.Input[category.UpdateCategoryInput]("UpdateCategoryInput", graphql.ZeroForNull()),
		graphql.Object[entity.Category]("Category",
			graphql.Field("id", func(v *entity.Category) int { return v.ID }),
			graphql.Field("name", func(v *entity.Category) string { return v.Name }),
			graphql.ResolveArgs("products", func(ctx context.Context, v *entity.Category, a CategoryProductsArgs) (*entity.ProductConnection, error) {
				return v.Products(ctx, a.After, a.First, a.Before, a.Last, a.OrderBy, a.Where)
			}),
		),
		graphql.Query(
			graphql.Resolve("categories", func(ctx context.Context, _ graphql.Root) ([]*entity.Category, error) { return r.Categories(ctx) }),
			graphql.ResolveArgs("category", func(ctx context.Context, _ graphql.Root, a CategoryArgs) (*entity.Category, error) {
				return r.Category(ctx, a)
			}),
		),
		graphql.Mutation(
			graphql.ResolveArgs("createCategory", func(ctx context.Context, _ graphql.Root, a CreateCategoryArgs) (*entity.Category, error) {
				return r.CreateCategory(ctx, a)
			}),
			graphql.ResolveArgs("updateCategory", func(ctx context.Context, _ graphql.Root, a UpdateCategoryArgs) (*entity.Category, error) {
				return r.UpdateCategory(ctx, a)
			}),
			graphql.ResolveArgs("deleteCategory", func(ctx context.Context, _ graphql.Root, a DeleteCategoryArgs) (int, error) {
				return r.DeleteCategory(ctx, a)
			}),
		),
		graphql.Args[CategoryProductsArgs](),
		graphql.Args[CreateCategoryArgs](),
		graphql.Args[UpdateCategoryArgs](),
		graphql.Args[DeleteCategoryArgs](),
		graphql.Args[CategoryArgs](),
	)
}
