// Code generated by velox. DO NOT EDIT.

package entity

import (
	"context"
	"fmt"
	"strings"

	predicate "github.com/syssam/graphql-go/examples/veloxfx/velox/predicate"
	velox "github.com/syssam/velox"
	sql "github.com/syssam/velox/dialect/sql"
	sqlgraph "github.com/syssam/velox/dialect/sql/sqlgraph"
	runtime "github.com/syssam/velox/runtime"
)

// Category is the model entity for the Category schema.
type Category struct {
	ID           int    `json:"id,omitempty"`
	Name         string `json:"name,omitempty"`
	config       runtime.Config
	selectValues sql.SelectValues
	Edges        CategoryEdges `json:"edges"`
}

// CategoryEdges holds the relations/edges for the Category entity.
type CategoryEdges struct {
	Products      []*Product `json:"products,omitempty"`
	namedProducts map[string][]*Product
	loadedTypes   [1]bool
	totalCount    map[string]int
}

// ProductsOrErr returns the products value or an error if the edge was not loaded.
func (e CategoryEdges) ProductsOrErr() ([]*Product, error) {
	if e.loadedTypes[0] {
		return e.Products, nil
	}
	return nil, runtime.NewNotLoadedError("products")
}

// SetProducts stores the products edge value and marks it as loaded.
func (e *CategoryEdges) SetProducts(v []*Product) {
	e.Products = v
	e.loadedTypes[0] = true
}

// ProductsLoaded reports whether the products edge was loaded.
func (e CategoryEdges) ProductsLoaded() bool {
	return e.loadedTypes[0]
}

// MarkProductsLoaded marks the products edge as loaded, even if empty.
func (e *CategoryEdges) MarkProductsLoaded() {
	e.loadedTypes[0] = true
}

// SetProductsAny sets the products edge from an any value (used by runtime edge loading).
func (e *CategoryEdges) SetProductsAny(v any) {
	children := v.([]any)
	typed := make([]*Product, len(children))
	for i, c := range children {
		typed[i] = c.(*Product)
	}
	e.Products = typed
	e.loadedTypes[0] = true
}

// GetProducts returns the products edge value as any (for runtime edge loading).
func (e CategoryEdges) GetProducts() any {
	return e.Products
}

// NamedProducts returns the products edge with the given name or an error if it was not loaded.
func (e *Category) NamedProducts(name string) ([]*Product, error) {
	if e.Edges.namedProducts == nil {
		return nil, runtime.NewNotLoadedError("products")
	}
	edges, ok := e.Edges.namedProducts[name]
	if !ok {
		return nil, runtime.NewNotLoadedError("products")
	}
	return edges, nil
}

// AppendNamedProducts adds the given edges to the named edge with the given name.
func (e *Category) AppendNamedProducts(name string, edges ...*Product) {
	if e.Edges.namedProducts == nil {
		e.Edges.namedProducts = make(map[string][]*Product)
	}
	e.Edges.namedProducts[name] = append(e.Edges.namedProducts[name], edges...)
}

// ScanValues returns the types for scanning values from sql.Rows.
func (*Category) ScanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case "id":
			values[i] = new(sql.NullInt64)
		case "name":
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// AssignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Category fields.
func (e *Category) AssignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case "id":
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else {
				if value.Valid {
					e.ID = int(value.Int64)
				}
			}
		case "name":
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else {
				if value.Valid {
					e.Name = value.String
				}
			}
		default:
			e.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Category.
// This includes values selected through modifiers, order, etc.
func (e *Category) Value(name string) (velox.Value, error) {
	return e.selectValues.Get(name)
}

// IsNode implements the Noder interface.
func (*Category) IsNode() {}

// String implements the fmt.Stringer interface.
func (e *Category) String() string {
	var b strings.Builder
	b.WriteString("Category(")
	if e.ID != int(0) {
		fmt.Fprintf(&b, "id=%v", e.ID)
	}
	if b.Len() > 9 {
		b.WriteString(", ")
	}
	b.WriteString("name=")
	b.WriteString(e.Name)
	b.WriteString(")")
	return b.String()
}

// Unwrap detaches the Category from its transaction so it can be used after
// Tx.Commit or Tx.Rollback. Without Unwrap, edge queries and reads performed
// via this entity after the transaction ends fail with
// "sql: transaction has already been committed".
//
// Call this on any entity returned from inside a WithTx closure before
// returning it to code that may read through it (e.g., GraphQL resolvers).
//
// Panics if the entity is not attached to a transaction.
func (e *Category) Unwrap() *Category {
	u, ok := e.config.Driver.(runtime.TxDriverUnwrapper)
	if !ok {
		panic("velox: Category.Unwrap() called on non-transactional entity")
	}
	e.config.Driver = u.BaseDriver()
	return e
}

// Config returns the runtime config (injected after query scan).
func (e *Category) Config() runtime.Config {
	return e.config
}

// SetConfig injects the runtime config (called by the query package after scan).
func (e *Category) SetConfig(c runtime.Config) {
	e.config = c
}

// QueryProducts queries the "products" edge of the Category.
func (_e *Category) QueryProducts() ProductQuerier {
	tq := runtime.NewEntityQuery("Product", _e.config)
	_is, _ := _e.config.InterStore.(*InterceptorStore)
	if _is == nil {
		_is = &InterceptorStore{}
	}
	tq.(interface {
		SetInterStore(*InterceptorStore)
	}).SetInterStore(_is)
	_tp := runtime.EntityPolicy("Product")
	if _tp != nil {
		if _sp, _ok := tq.(interface {
			SetPolicy(velox.Policy)
		}); _ok {
			_sp.SetPolicy(_tp)
		}
	}
	tq.(interface {
		SetPath(func(context.Context) (*sql.Selector, error))
	}).SetPath(func(ctx context.Context) (*sql.Selector, error) {
		id := _e.ID
		step := sqlgraph.NewStep(sqlgraph.From("categories", "id", id), sqlgraph.To("products", "id"), sqlgraph.Edge(sqlgraph.O2M, false, "products", "category_products"))
		return sqlgraph.Neighbors(_e.config.Driver.Dialect(), step), nil
	})
	return tq.(ProductQuerier)
}

// CategoryQuerier defines the query interface for Category entities.
type CategoryQuerier interface {
	All(ctx context.Context) ([]*Category, error)
	First(ctx context.Context) (*Category, error)
	Only(ctx context.Context) (*Category, error)
	Count(ctx context.Context) (int, error)
	Exist(ctx context.Context) (bool, error)
	ExistX(context.Context) bool
	SQL(ctx context.Context) (string, []any, error)
	IDs(ctx context.Context) ([]int, error)
	FirstID(ctx context.Context) (int, error)
	OnlyID(ctx context.Context) (int, error)
	Where(ps ...predicate.Category) CategoryQuerier
	Limit(n int) CategoryQuerier
	Offset(n int) CategoryQuerier
	Order(o ...func(*sql.Selector)) CategoryQuerier
	Unique(unique bool) CategoryQuerier
	WithProducts(opts ...func(ProductQuerier)) CategoryQuerier
	Select(fields ...string) CategorySelector
	Modify(modifiers ...func(*sql.Selector)) CategoryQuerier
	GroupBy(field string, fields ...string) CategoryGroupByer
	Aggregate(fns ...runtime.AggregateFunc) CategorySelector
	Scan(context.Context, any) error
	ScanX(context.Context, any)
	Clone() CategoryQuerier
	ForUpdate(opts ...sql.LockOption) CategoryQuerier
	ForShare(opts ...sql.LockOption) CategoryQuerier
	CollectFields(ctx context.Context, satisfies ...string) (CategoryQuerier, error)
}

// CategorySelector defines the select interface for Category entities.
type CategorySelector interface {
	Aggregate(fns ...runtime.AggregateFunc) CategorySelector
	All(ctx context.Context) ([]*Category, error)
	AllX(ctx context.Context) []*Category
	First(ctx context.Context) (*Category, error)
	FirstX(ctx context.Context) *Category
	Only(ctx context.Context) (*Category, error)
	OnlyX(ctx context.Context) *Category
	Count(ctx context.Context) (int, error)
	CountX(ctx context.Context) int
	Exist(ctx context.Context) (bool, error)
	ExistX(ctx context.Context) bool
	IDs(ctx context.Context) ([]int, error)
	FirstID(ctx context.Context) (int, error)
	OnlyID(ctx context.Context) (int, error)
	Scan(ctx context.Context, v any) error
	ScanX(ctx context.Context, v any)
	Strings(ctx context.Context) ([]string, error)
	StringsX(ctx context.Context) []string
	String(ctx context.Context) (string, error)
	StringX(ctx context.Context) string
	Ints(ctx context.Context) ([]int, error)
	IntsX(ctx context.Context) []int
	Int(ctx context.Context) (int, error)
	IntX(ctx context.Context) int
	Float64s(ctx context.Context) ([]float64, error)
	Float64sX(ctx context.Context) []float64
	Float64(ctx context.Context) (float64, error)
	Float64X(ctx context.Context) float64
	Bools(ctx context.Context) ([]bool, error)
	BoolsX(ctx context.Context) []bool
	Bool(ctx context.Context) (bool, error)
	BoolX(ctx context.Context) bool
}

// CategoryGroupByer defines the group-by interface for Category entities.
type CategoryGroupByer interface {
	Aggregate(fns ...runtime.AggregateFunc) CategoryGroupByer
	Scan(ctx context.Context, v any) error
	ScanX(ctx context.Context, v any)
	Strings(ctx context.Context) ([]string, error)
	StringsX(ctx context.Context) []string
	String(ctx context.Context) (string, error)
	StringX(ctx context.Context) string
	Ints(ctx context.Context) ([]int, error)
	IntsX(ctx context.Context) []int
	Int(ctx context.Context) (int, error)
	IntX(ctx context.Context) int
	Float64s(ctx context.Context) ([]float64, error)
	Float64sX(ctx context.Context) []float64
	Float64(ctx context.Context) (float64, error)
	Float64X(ctx context.Context) float64
	Bools(ctx context.Context) ([]bool, error)
	BoolsX(ctx context.Context) []bool
	Bool(ctx context.Context) (bool, error)
	BoolX(ctx context.Context) bool
}
