// Code generated by velox. DO NOT EDIT.

package entity

import (
	"context"

	"github.com/syssam/velox/runtime"
)

func (m *OrderItem) Order(ctx context.Context) (*Order, error) {
	result, err := m.Edges.OrderOrErr()
	if runtime.IsNotLoaded(err) {
		val, err2 := m.QueryOrder().Only(ctx)
		if err2 != nil {
			return nil, runtime.MaskNotFound(err2)
		}
		return val, nil
	}
	return result, runtime.MaskNotFound(err)
}
func (m *OrderItem) Product(ctx context.Context) (*Product, error) {
	result, err := m.Edges.ProductOrErr()
	if runtime.IsNotLoaded(err) {
		val, err2 := m.QueryProduct().Only(ctx)
		if err2 != nil {
			return nil, runtime.MaskNotFound(err2)
		}
		return val, nil
	}
	return result, runtime.MaskNotFound(err)
}
