// Code generated by velox. DO NOT EDIT.

package entity

import (
	"context"

	"github.com/syssam/velox/runtime"
)

func (m *Category) Products(ctx context.Context) ([]*Product, error) {
	result, err := m.Edges.ProductsOrErr()
	if runtime.IsNotLoaded(err) {
		return m.QueryProducts().All(ctx)
	}
	return result, err
}
