// Code generated by velox. DO NOT EDIT.

package entity

import (
	"context"

	"github.com/syssam/velox/runtime"
)

func (m *Order) Customer(ctx context.Context) (*Customer, error) {
	result, err := m.Edges.CustomerOrErr()
	if runtime.IsNotLoaded(err) {
		val, err2 := m.QueryCustomer().Only(ctx)
		if err2 != nil {
			return nil, runtime.MaskNotFound(err2)
		}
		return val, nil
	}
	return result, runtime.MaskNotFound(err)
}
func (m *Order) Warehouse(ctx context.Context) (*Warehouse, error) {
	result, err := m.Edges.WarehouseOrErr()
	if runtime.IsNotLoaded(err) {
		val, err2 := m.QueryWarehouse().Only(ctx)
		if err2 != nil {
			return nil, runtime.MaskNotFound(err2)
		}
		return val, nil
	}
	return result, runtime.MaskNotFound(err)
}
func (m *Order) Items(ctx context.Context) ([]*OrderItem, error) {
	result, err := m.Edges.ItemsOrErr()
	if runtime.IsNotLoaded(err) {
		return m.QueryItems().All(ctx)
	}
	return result, err
}
