// Code generated by velox. DO NOT EDIT.

package entity

import (
	"context"

	"github.com/syssam/velox/runtime"
)

func (m *Customer) Orders(ctx context.Context) ([]*Order, error) {
	result, err := m.Edges.OrdersOrErr()
	if runtime.IsNotLoaded(err) {
		return m.QueryOrders().All(ctx)
	}
	return result, err
}
