// Code generated by velox. DO NOT EDIT.

package entity

import velox "github.com/syssam/velox"

// HookStore holds mutation hooks for all entities.
// Shared via pointer between root client and all entity clients.
//
// Concurrency contract: all Use() calls must complete before
// concurrent query/mutation execution begins. HookStore is
// intended for application startup (e.g., in main or init),
// not for runtime registration. No synchronization is provided
// on the hook slices — this matches Ent's design.
type HookStore struct {
	Todo []velox.Hook
	User []velox.Hook
}

// AppendAll appends the given hooks to every entity's hook slice.
func (s *HookStore) AppendAll(hooks ...velox.Hook) {
	s.Todo = append(s.Todo, hooks...)
	s.User = append(s.User, hooks...)
}

// InterceptorStore holds query interceptors for all entities.
// Shared via pointer between root client and all entity clients.
//
// Concurrency contract: all Intercept() calls must complete before
// concurrent query execution begins. InterceptorStore is intended
// for application startup (e.g., in main or init), not for
// runtime registration. No synchronization is provided on the
// interceptor slices — this matches Ent's design.
type InterceptorStore struct {
	Todo []velox.Interceptor
	User []velox.Interceptor
}

// AppendAll appends the given interceptors to every entity's interceptor slice.
func (s *InterceptorStore) AppendAll(interceptors ...velox.Interceptor) {
	s.Todo = append(s.Todo, interceptors...)
	s.User = append(s.User, interceptors...)
}
