// Code generated by velox. DO NOT EDIT.

package entity

import (
	"context"
	"fmt"
	"strings"

	predicate "github.com/syssam/graphql-go/examples/veloxfx/velox/predicate"
	velox "github.com/syssam/velox"
	sql "github.com/syssam/velox/dialect/sql"
	sqlgraph "github.com/syssam/velox/dialect/sql/sqlgraph"
	runtime "github.com/syssam/velox/runtime"
)

// OrderItem is the model entity for the OrderItem schema.
type OrderItem struct {
	ID                  int `json:"id,omitempty"`
	Quantity            int `json:"quantity,omitempty"`
	UnitPriceCents      int `json:"unit_price_cents,omitempty"`
	order_items         *int
	product_order_items *int
	config              runtime.Config
	selectValues        sql.SelectValues
	Edges               OrderItemEdges `json:"edges"`
}

// OrderItemEdges holds the relations/edges for the OrderItem entity.
type OrderItemEdges struct {
	Order       *Order   `json:"order,omitempty"`
	Product     *Product `json:"product,omitempty"`
	loadedTypes [2]bool
	totalCount  map[string]int
}

// OrderOrErr returns the order value or an error if the edge was not loaded.
func (e OrderItemEdges) OrderOrErr() (*Order, error) {
	if e.loadedTypes[0] {
		return e.Order, nil
	}
	return nil, runtime.NewNotLoadedError("order")
}

// SetOrder stores the order edge value and marks it as loaded.
func (e *OrderItemEdges) SetOrder(v *Order) {
	e.Order = v
	e.loadedTypes[0] = true
}

// OrderLoaded reports whether the order edge was loaded.
func (e OrderItemEdges) OrderLoaded() bool {
	return e.loadedTypes[0]
}

// MarkOrderLoaded marks the order edge as loaded, even if empty.
func (e *OrderItemEdges) MarkOrderLoaded() {
	e.loadedTypes[0] = true
}

// SetOrderAny sets the order edge from an any value (used by runtime edge loading).
func (e *OrderItemEdges) SetOrderAny(v any) {
	if v != nil {
		e.Order = v.(*Order)
	}
	e.loadedTypes[0] = true
}

// GetOrder returns the order edge value as any (for runtime edge loading).
func (e OrderItemEdges) GetOrder() any {
	return e.Order
}

// ProductOrErr returns the product value or an error if the edge was not loaded.
func (e OrderItemEdges) ProductOrErr() (*Product, error) {
	if e.loadedTypes[1] {
		return e.Product, nil
	}
	return nil, runtime.NewNotLoadedError("product")
}

// SetProduct stores the product edge value and marks it as loaded.
func (e *OrderItemEdges) SetProduct(v *Product) {
	e.Product = v
	e.loadedTypes[1] = true
}

// ProductLoaded reports whether the product edge was loaded.
func (e OrderItemEdges) ProductLoaded() bool {
	return e.loadedTypes[1]
}

// MarkProductLoaded marks the product edge as loaded, even if empty.
func (e *OrderItemEdges) MarkProductLoaded() {
	e.loadedTypes[1] = true
}

// SetProductAny sets the product edge from an any value (used by runtime edge loading).
func (e *OrderItemEdges) SetProductAny(v any) {
	if v != nil {
		e.Product = v.(*Product)
	}
	e.loadedTypes[1] = true
}

// GetProduct returns the product edge value as any (for runtime edge loading).
func (e OrderItemEdges) GetProduct() any {
	return e.Product
}

// ScanValues returns the types for scanning values from sql.Rows.
func (*OrderItem) ScanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case "id", "quantity", "unit_price_cents":
			values[i] = new(sql.NullInt64)
		case "order_items":
			values[i] = new(sql.NullInt64)
		case "product_order_items":
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// AssignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OrderItem fields.
func (e *OrderItem) AssignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case "id":
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else {
				if value.Valid {
					e.ID = int(value.Int64)
				}
			}
		case "quantity":
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else {
				if value.Valid {
					e.Quantity = int(value.Int64)
				}
			}
		case "unit_price_cents":
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field unit_price_cents", values[i])
			} else {
				if value.Valid {
					e.UnitPriceCents = int(value.Int64)
				}
			}
		case "order_items":
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order_items", values[i])
			} else {
				if value.Valid {
					e.order_items = new(int)
					*e.order_items = int(value.Int64)
				}
			}
		case "product_order_items":
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field product_order_items", values[i])
			} else {
				if value.Valid {
					e.product_order_items = new(int)
					*e.product_order_items = int(value.Int64)
				}
			}
		default:
			e.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OrderItem.
// This includes values selected through modifiers, order, etc.
func (e *OrderItem) Value(name string) (velox.Value, error) {
	return e.selectValues.Get(name)
}

// FKValue returns the value of a foreign key field by column name.
func (e *OrderItem) FKValue(column string) any {
	switch column {
	case "order_items":
		return e.order_items
	case "product_order_items":
		return e.product_order_items
	default:
		return nil
	}
}

// IsNode implements the Noder interface.
func (*OrderItem) IsNode() {}

// String implements the fmt.Stringer interface.
func (e *OrderItem) String() string {
	var b strings.Builder
	b.WriteString("OrderItem(")
	if e.ID != int(0) {
		fmt.Fprintf(&b, "id=%v", e.ID)
	}
	if b.Len() > 10 {
		b.WriteString(", ")
	}
	fmt.Fprintf(&b, "quantity=%v", e.Quantity)
	if b.Len() > 10 {
		b.WriteString(", ")
	}
	fmt.Fprintf(&b, "unit_price_cents=%v", e.UnitPriceCents)
	b.WriteString(")")
	return b.String()
}

// Unwrap detaches the OrderItem from its transaction so it can be used after
// Tx.Commit or Tx.Rollback. Without Unwrap, edge queries and reads performed
// via this entity after the transaction ends fail with
// "sql: transaction has already been committed".
//
// Call this on any entity returned from inside a WithTx closure before
// returning it to code that may read through it (e.g., GraphQL resolvers).
//
// Panics if the entity is not attached to a transaction.
func (e *OrderItem) Unwrap() *OrderItem {
	u, ok := e.config.Driver.(runtime.TxDriverUnwrapper)
	if !ok {
		panic("velox: OrderItem.Unwrap() called on non-transactional entity")
	}
	e.config.Driver = u.BaseDriver()
	return e
}

// Config returns the runtime config (injected after query scan).
func (e *OrderItem) Config() runtime.Config {
	return e.config
}

// SetConfig injects the runtime config (called by the query package after scan).
func (e *OrderItem) SetConfig(c runtime.Config) {
	e.config = c
}

// QueryOrder queries the "order" edge of the OrderItem.
func (_e *OrderItem) QueryOrder() OrderQuerier {
	tq := runtime.NewEntityQuery("Order", _e.config)
	_is, _ := _e.config.InterStore.(*InterceptorStore)
	if _is == nil {
		_is = &InterceptorStore{}
	}
	tq.(interface {
		SetInterStore(*InterceptorStore)
	}).SetInterStore(_is)
	_tp := runtime.EntityPolicy("Order")
	if _tp != nil {
		if _sp, _ok := tq.(interface {
			SetPolicy(velox.Policy)
		}); _ok {
			_sp.SetPolicy(_tp)
		}
	}
	tq.(interface {
		SetPath(func(context.Context) (*sql.Selector, error))
	}).SetPath(func(ctx context.Context) (*sql.Selector, error) {
		id := _e.ID
		step := sqlgraph.NewStep(sqlgraph.From("order_items", "id", id), sqlgraph.To("orders", "id"), sqlgraph.Edge(sqlgraph.M2O, true, "order_items", "order_items"))
		return sqlgraph.Neighbors(_e.config.Driver.Dialect(), step), nil
	})
	return tq.(OrderQuerier)
}

// QueryProduct queries the "product" edge of the OrderItem.
func (_e *OrderItem) QueryProduct() ProductQuerier {
	tq := runtime.NewEntityQuery("Product", _e.config)
	_is, _ := _e.config.InterStore.(*InterceptorStore)
	if _is == nil {
		_is = &InterceptorStore{}
	}
	tq.(interface {
		SetInterStore(*InterceptorStore)
	}).SetInterStore(_is)
	_tp := runtime.EntityPolicy("Product")
	if _tp != nil {
		if _sp, _ok := tq.(interface {
			SetPolicy(velox.Policy)
		}); _ok {
			_sp.SetPolicy(_tp)
		}
	}
	tq.(interface {
		SetPath(func(context.Context) (*sql.Selector, error))
	}).SetPath(func(ctx context.Context) (*sql.Selector, error) {
		id := _e.ID
		step := sqlgraph.NewStep(sqlgraph.From("order_items", "id", id), sqlgraph.To("products", "id"), sqlgraph.Edge(sqlgraph.M2O, true, "order_items", "product_order_items"))
		return sqlgraph.Neighbors(_e.config.Driver.Dialect(), step), nil
	})
	return tq.(ProductQuerier)
}

// OrderItemQuerier defines the query interface for OrderItem entities.
type OrderItemQuerier interface {
	All(ctx context.Context) ([]*OrderItem, error)
	First(ctx context.Context) (*OrderItem, error)
	Only(ctx context.Context) (*OrderItem, error)
	Count(ctx context.Context) (int, error)
	Exist(ctx context.Context) (bool, error)
	ExistX(context.Context) bool
	SQL(ctx context.Context) (string, []any, error)
	IDs(ctx context.Context) ([]int, error)
	FirstID(ctx context.Context) (int, error)
	OnlyID(ctx context.Context) (int, error)
	Where(ps ...predicate.OrderItem) OrderItemQuerier
	Limit(n int) OrderItemQuerier
	Offset(n int) OrderItemQuerier
	Order(o ...func(*sql.Selector)) OrderItemQuerier
	Unique(unique bool) OrderItemQuerier
	WithOrder(opts ...func(OrderQuerier)) OrderItemQuerier
	WithProduct(opts ...func(ProductQuerier)) OrderItemQuerier
	Select(fields ...string) OrderItemSelector
	Modify(modifiers ...func(*sql.Selector)) OrderItemQuerier
	GroupBy(field string, fields ...string) OrderItemGroupByer
	Aggregate(fns ...runtime.AggregateFunc) OrderItemSelector
	Scan(context.Context, any) error
	ScanX(context.Context, any)
	Clone() OrderItemQuerier
	ForUpdate(opts ...sql.LockOption) OrderItemQuerier
	ForShare(opts ...sql.LockOption) OrderItemQuerier
	CollectFields(ctx context.Context, satisfies ...string) (OrderItemQuerier, error)
}

// OrderItemSelector defines the select interface for OrderItem entities.
type OrderItemSelector interface {
	Aggregate(fns ...runtime.AggregateFunc) OrderItemSelector
	All(ctx context.Context) ([]*OrderItem, error)
	AllX(ctx context.Context) []*OrderItem
	First(ctx context.Context) (*OrderItem, error)
	FirstX(ctx context.Context) *OrderItem
	Only(ctx context.Context) (*OrderItem, error)
	OnlyX(ctx context.Context) *OrderItem
	Count(ctx context.Context) (int, error)
	CountX(ctx context.Context) int
	Exist(ctx context.Context) (bool, error)
	ExistX(ctx context.Context) bool
	IDs(ctx context.Context) ([]int, error)
	FirstID(ctx context.Context) (int, error)
	OnlyID(ctx context.Context) (int, error)
	Scan(ctx context.Context, v any) error
	ScanX(ctx context.Context, v any)
	Strings(ctx context.Context) ([]string, error)
	StringsX(ctx context.Context) []string
	String(ctx context.Context) (string, error)
	StringX(ctx context.Context) string
	Ints(ctx context.Context) ([]int, error)
	IntsX(ctx context.Context) []int
	Int(ctx context.Context) (int, error)
	IntX(ctx context.Context) int
	Float64s(ctx context.Context) ([]float64, error)
	Float64sX(ctx context.Context) []float64
	Float64(ctx context.Context) (float64, error)
	Float64X(ctx context.Context) float64
	Bools(ctx context.Context) ([]bool, error)
	BoolsX(ctx context.Context) []bool
	Bool(ctx context.Context) (bool, error)
	BoolX(ctx context.Context) bool
}

// OrderItemGroupByer defines the group-by interface for OrderItem entities.
type OrderItemGroupByer interface {
	Aggregate(fns ...runtime.AggregateFunc) OrderItemGroupByer
	Scan(ctx context.Context, v any) error
	ScanX(ctx context.Context, v any)
	Strings(ctx context.Context) ([]string, error)
	StringsX(ctx context.Context) []string
	String(ctx context.Context) (string, error)
	StringX(ctx context.Context) string
	Ints(ctx context.Context) ([]int, error)
	IntsX(ctx context.Context) []int
	Int(ctx context.Context) (int, error)
	IntX(ctx context.Context) int
	Float64s(ctx context.Context) ([]float64, error)
	Float64sX(ctx context.Context) []float64
	Float64(ctx context.Context) (float64, error)
	Float64X(ctx context.Context) float64
	Bools(ctx context.Context) ([]bool, error)
	BoolsX(ctx context.Context) []bool
	Bool(ctx context.Context) (bool, error)
	BoolX(ctx context.Context) bool
}
