// Code generated by velox. DO NOT EDIT.

package entity

import (
	"context"
	"fmt"
	"strings"
	"time"

	predicate "github.com/syssam/graphql-go/examples/veloxfx/velox/predicate"
	todo "github.com/syssam/graphql-go/examples/veloxfx/velox/todo"
	velox "github.com/syssam/velox"
	sql "github.com/syssam/velox/dialect/sql"
	sqlgraph "github.com/syssam/velox/dialect/sql/sqlgraph"
	runtime "github.com/syssam/velox/runtime"
)

// Todo is the model entity for the Todo schema.
type Todo struct {
	ID           int         `json:"id,omitempty"`
	CreatedAt    time.Time   `json:"created_at,omitempty"`
	UpdatedAt    time.Time   `json:"updated_at,omitempty"`
	Title        string      `json:"title,omitempty"`
	Status       todo.Status `json:"status,omitempty"`
	user_todos   *int
	config       runtime.Config
	selectValues sql.SelectValues
	Edges        TodoEdges `json:"edges"`
}

// TodoEdges holds the relations/edges for the Todo entity.
type TodoEdges struct {
	Owner       *User `json:"owner,omitempty"`
	loadedTypes [1]bool
	totalCount  map[string]int
}

// OwnerOrErr returns the owner value or an error if the edge was not loaded.
func (e TodoEdges) OwnerOrErr() (*User, error) {
	if e.loadedTypes[0] {
		return e.Owner, nil
	}
	return nil, runtime.NewNotLoadedError("owner")
}

// SetOwner stores the owner edge value and marks it as loaded.
func (e *TodoEdges) SetOwner(v *User) {
	e.Owner = v
	e.loadedTypes[0] = true
}

// OwnerLoaded reports whether the owner edge was loaded.
func (e TodoEdges) OwnerLoaded() bool {
	return e.loadedTypes[0]
}

// MarkOwnerLoaded marks the owner edge as loaded, even if empty.
func (e *TodoEdges) MarkOwnerLoaded() {
	e.loadedTypes[0] = true
}

// SetOwnerAny sets the owner edge from an any value (used by runtime edge loading).
func (e *TodoEdges) SetOwnerAny(v any) {
	if v != nil {
		e.Owner = v.(*User)
	}
	e.loadedTypes[0] = true
}

// GetOwner returns the owner edge value as any (for runtime edge loading).
func (e TodoEdges) GetOwner() any {
	return e.Owner
}

// ScanValues returns the types for scanning values from sql.Rows.
func (*Todo) ScanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case "id":
			values[i] = new(sql.NullInt64)
		case "title", "status":
			values[i] = new(sql.NullString)
		case "created_at", "updated_at":
			values[i] = new(sql.NullTime)
		case "user_todos":
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// AssignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Todo fields.
func (e *Todo) AssignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case "id":
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else {
				if value.Valid {
					e.ID = int(value.Int64)
				}
			}
		case "created_at":
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else {
				if value.Valid {
					e.CreatedAt = value.Time
				}
			}
		case "updated_at":
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else {
				if value.Valid {
					e.UpdatedAt = value.Time
				}
			}
		case "title":
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else {
				if value.Valid {
					e.Title = value.String
				}
			}
		case "status":
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else {
				if value.Valid {
					e.Status = todo.Status(value.String)
				}
			}
		case "user_todos":
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_todos", values[i])
			} else {
				if value.Valid {
					e.user_todos = new(int)
					*e.user_todos = int(value.Int64)
				}
			}
		default:
			e.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Todo.
// This includes values selected through modifiers, order, etc.
func (e *Todo) Value(name string) (velox.Value, error) {
	return e.selectValues.Get(name)
}

// FKValue returns the value of a foreign key field by column name.
func (e *Todo) FKValue(column string) any {
	switch column {
	case "user_todos":
		return e.user_todos
	default:
		return nil
	}
}

// IsNode implements the Noder interface.
func (*Todo) IsNode() {}

// String implements the fmt.Stringer interface.
func (e *Todo) String() string {
	var b strings.Builder
	b.WriteString("Todo(")
	if e.ID != int(0) {
		fmt.Fprintf(&b, "id=%v", e.ID)
	}
	if b.Len() > 5 {
		b.WriteString(", ")
	}
	fmt.Fprintf(&b, "created_at=%v", e.CreatedAt)
	if b.Len() > 5 {
		b.WriteString(", ")
	}
	fmt.Fprintf(&b, "updated_at=%v", e.UpdatedAt)
	if b.Len() > 5 {
		b.WriteString(", ")
	}
	b.WriteString("title=")
	b.WriteString(e.Title)
	if b.Len() > 5 {
		b.WriteString(", ")
	}
	fmt.Fprintf(&b, "status=%v", e.Status)
	b.WriteString(")")
	return b.String()
}

// Unwrap detaches the Todo from its transaction so it can be used after
// Tx.Commit or Tx.Rollback. Without Unwrap, edge queries and reads performed
// via this entity after the transaction ends fail with
// "sql: transaction has already been committed".
//
// Call this on any entity returned from inside a WithTx closure before
// returning it to code that may read through it (e.g., GraphQL resolvers).
//
// Panics if the entity is not attached to a transaction.
func (e *Todo) Unwrap() *Todo {
	u, ok := e.config.Driver.(runtime.TxDriverUnwrapper)
	if !ok {
		panic("velox: Todo.Unwrap() called on non-transactional entity")
	}
	e.config.Driver = u.BaseDriver()
	return e
}

// Config returns the runtime config (injected after query scan).
func (e *Todo) Config() runtime.Config {
	return e.config
}

// SetConfig injects the runtime config (called by the query package after scan).
func (e *Todo) SetConfig(c runtime.Config) {
	e.config = c
}

// QueryOwner queries the "owner" edge of the Todo.
func (_e *Todo) QueryOwner() UserQuerier {
	tq := runtime.NewEntityQuery("User", _e.config)
	_is, _ := _e.config.InterStore.(*InterceptorStore)
	if _is == nil {
		_is = &InterceptorStore{}
	}
	tq.(interface {
		SetInterStore(*InterceptorStore)
	}).SetInterStore(_is)
	_tp := runtime.EntityPolicy("User")
	if _tp != nil {
		if _sp, _ok := tq.(interface {
			SetPolicy(velox.Policy)
		}); _ok {
			_sp.SetPolicy(_tp)
		}
	}
	tq.(interface {
		SetPath(func(context.Context) (*sql.Selector, error))
	}).SetPath(func(ctx context.Context) (*sql.Selector, error) {
		id := _e.ID
		step := sqlgraph.NewStep(sqlgraph.From("todos", "id", id), sqlgraph.To("users", "id"), sqlgraph.Edge(sqlgraph.M2O, true, "todos", "user_todos"))
		return sqlgraph.Neighbors(_e.config.Driver.Dialect(), step), nil
	})
	return tq.(UserQuerier)
}

// TodoQuerier defines the query interface for Todo entities.
type TodoQuerier interface {
	All(ctx context.Context) ([]*Todo, error)
	First(ctx context.Context) (*Todo, error)
	Only(ctx context.Context) (*Todo, error)
	Count(ctx context.Context) (int, error)
	Exist(ctx context.Context) (bool, error)
	ExistX(context.Context) bool
	SQL(ctx context.Context) (string, []any, error)
	IDs(ctx context.Context) ([]int, error)
	FirstID(ctx context.Context) (int, error)
	OnlyID(ctx context.Context) (int, error)
	Where(ps ...predicate.Todo) TodoQuerier
	Limit(n int) TodoQuerier
	Offset(n int) TodoQuerier
	Order(o ...func(*sql.Selector)) TodoQuerier
	Unique(unique bool) TodoQuerier
	WithOwner(opts ...func(UserQuerier)) TodoQuerier
	Select(fields ...string) TodoSelector
	Modify(modifiers ...func(*sql.Selector)) TodoQuerier
	GroupBy(field string, fields ...string) TodoGroupByer
	Aggregate(fns ...runtime.AggregateFunc) TodoSelector
	Scan(context.Context, any) error
	ScanX(context.Context, any)
	Clone() TodoQuerier
	ForUpdate(opts ...sql.LockOption) TodoQuerier
	ForShare(opts ...sql.LockOption) TodoQuerier
	CollectFields(ctx context.Context, satisfies ...string) (TodoQuerier, error)
}

// TodoSelector defines the select interface for Todo entities.
type TodoSelector interface {
	Aggregate(fns ...runtime.AggregateFunc) TodoSelector
	All(ctx context.Context) ([]*Todo, error)
	AllX(ctx context.Context) []*Todo
	First(ctx context.Context) (*Todo, error)
	FirstX(ctx context.Context) *Todo
	Only(ctx context.Context) (*Todo, error)
	OnlyX(ctx context.Context) *Todo
	Count(ctx context.Context) (int, error)
	CountX(ctx context.Context) int
	Exist(ctx context.Context) (bool, error)
	ExistX(ctx context.Context) bool
	IDs(ctx context.Context) ([]int, error)
	FirstID(ctx context.Context) (int, error)
	OnlyID(ctx context.Context) (int, error)
	Scan(ctx context.Context, v any) error
	ScanX(ctx context.Context, v any)
	Strings(ctx context.Context) ([]string, error)
	StringsX(ctx context.Context) []string
	String(ctx context.Context) (string, error)
	StringX(ctx context.Context) string
	Ints(ctx context.Context) ([]int, error)
	IntsX(ctx context.Context) []int
	Int(ctx context.Context) (int, error)
	IntX(ctx context.Context) int
	Float64s(ctx context.Context) ([]float64, error)
	Float64sX(ctx context.Context) []float64
	Float64(ctx context.Context) (float64, error)
	Float64X(ctx context.Context) float64
	Bools(ctx context.Context) ([]bool, error)
	BoolsX(ctx context.Context) []bool
	Bool(ctx context.Context) (bool, error)
	BoolX(ctx context.Context) bool
}

// TodoGroupByer defines the group-by interface for Todo entities.
type TodoGroupByer interface {
	Aggregate(fns ...runtime.AggregateFunc) TodoGroupByer
	Scan(ctx context.Context, v any) error
	ScanX(ctx context.Context, v any)
	Strings(ctx context.Context) ([]string, error)
	StringsX(ctx context.Context) []string
	String(ctx context.Context) (string, error)
	StringX(ctx context.Context) string
	Ints(ctx context.Context) ([]int, error)
	IntsX(ctx context.Context) []int
	Int(ctx context.Context) (int, error)
	IntX(ctx context.Context) int
	Float64s(ctx context.Context) ([]float64, error)
	Float64sX(ctx context.Context) []float64
	Float64(ctx context.Context) (float64, error)
	Float64X(ctx context.Context) float64
	Bools(ctx context.Context) ([]bool, error)
	BoolsX(ctx context.Context) []bool
	Bool(ctx context.Context) (bool, error)
	BoolX(ctx context.Context) bool
}
