// Code generated by velox. DO NOT EDIT.

package customerclient

import (
	"context"
	"errors"
	"fmt"

	customer "github.com/syssam/graphql-go/examples/veloxfx/velox/customer"
	entity "github.com/syssam/graphql-go/examples/veloxfx/velox/entity"
	velox "github.com/syssam/velox"
	sqlgraph "github.com/syssam/velox/dialect/sql/sqlgraph"
	runtime "github.com/syssam/velox/runtime"
	field "github.com/syssam/velox/schema/field"
)

// customerIDFieldType is the field.Type for Customer's primary key column.
var customerIDFieldType = field.TypeInt

// customerFieldTypes maps column names to field.Type for Customer.
var customerFieldTypes = map[string]field.Type{"id": field.TypeInt, "name": field.TypeString, "email": field.TypeString}

// CustomerCreate is the builder for creating a Customer entity.
type CustomerCreate struct {
	config   runtime.Config
	mutation *CustomerMutation
	hooks    []runtime.Hook
}

// NewCustomerCreate creates a new CustomerCreate builder.
func NewCustomerCreate(c runtime.Config, mutation *CustomerMutation, hooks []runtime.Hook) *CustomerCreate {
	return &CustomerCreate{
		config:   c,
		hooks:    hooks,
		mutation: mutation,
	}
}

// SetName sets the "name" field.
func (c *CustomerCreate) SetName(v string) *CustomerCreate {
	c.mutation.SetName(v)
	return c
}

// SetEmail sets the "email" field.
func (c *CustomerCreate) SetEmail(v string) *CustomerCreate {
	c.mutation.SetEmail(v)
	return c
}

// AddOrderIDs adds the "orders" edge by ids.
func (c *CustomerCreate) AddOrderIDs(ids ...int) *CustomerCreate {
	c.mutation.AddOrderIDs(ids...)
	return c
}

// AddOrders adds the "orders" edge to the given entities.
func (c *CustomerCreate) AddOrders(v ...*entity.Order) *CustomerCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	c.AddOrderIDs(ids...)
	return c
}

// Mutation returns the CustomerMutation.
func (c *CustomerCreate) Mutation() *CustomerMutation {
	return c.mutation
}

// check runs all checks and user-defined validators on the builder.
func (c *CustomerCreate) check() error {
	if _, ok := c.mutation.Name(); !ok {
		return &runtime.ValidationError{
			Entity: "Customer",
			Err:    errors.New("missing required field \"Customer.name\""),
			Field:  "name",
			Name:   "name",
		}
	}
	if v, ok := c.mutation.Name(); ok {
		if err := customer.NameValidator(v); err != nil {
			return &runtime.ValidationError{
				Entity: "Customer",
				Err:    fmt.Errorf("validator failed for field \"Customer.name\": %w", err),
				Field:  "name",
				Name:   "name",
			}
		}
	}
	if _, ok := c.mutation.Email(); !ok {
		return &runtime.ValidationError{
			Entity: "Customer",
			Err:    errors.New("missing required field \"Customer.email\""),
			Field:  "email",
			Name:   "email",
		}
	}
	if v, ok := c.mutation.Email(); ok {
		if err := customer.EmailValidator(v); err != nil {
			return &runtime.ValidationError{
				Entity: "Customer",
				Err:    fmt.Errorf("validator failed for field \"Customer.email\": %w", err),
				Field:  "email",
				Name:   "email",
			}
		}
	}
	return nil
}

// sqlSave executes the SQL create for Customer after hooks have run.
func (c *CustomerCreate) sqlSave(ctx context.Context) (*entity.Customer, error) {
	if err := c.check(); err != nil {
		return nil, err
	}
	_node, _spec := c.createSpec()
	if err := sqlgraph.CreateNode(ctx, c.config.Driver, _spec); err != nil {
		return nil, runtime.MayWrapConstraintError(err)
	}
	_node.SetConfig(c.config)
	if _spec.ID.Value != nil {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	c.mutation.SetID(_node.ID)
	return _node, nil
}

// createSpec builds the Customer node and sqlgraph.CreateSpec from mutation fields.
func (c *CustomerCreate) createSpec() (*entity.Customer, *sqlgraph.CreateSpec) {
	var (
		_node = &entity.Customer{}
		_spec = sqlgraph.NewCreateSpec(customer.Table, &sqlgraph.FieldSpec{
			Column: customer.FieldID,
			Type:   customerIDFieldType,
		})
	)
	if c.mutation._name != nil {
		v := *c.mutation._name
		_spec.SetField("name", field.TypeString, v)
		_node.Name = v
	}
	if c.mutation._email != nil {
		v := *c.mutation._email
		_spec.SetField("email", field.TypeString, v)
		_node.Email = v
	}
	if nodes := c.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"customer_orders"},
			Inverse: false,
			Rel:     sqlgraph.O2M,
			Table:   "orders",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// Save creates the Customer in the database.
func (c *CustomerCreate) Save(ctx context.Context) (*entity.Customer, error) {
	hooks := c.hooks
	return velox.WithHooks[*entity.Customer, CustomerMutation, *CustomerMutation](ctx, c.sqlSave, c.mutation, hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (c *CustomerCreate) SaveX(ctx context.Context) *entity.Customer {
	v, err := c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (c *CustomerCreate) Exec(ctx context.Context) error {
	_, err := c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (c *CustomerCreate) ExecX(ctx context.Context) {
	if err := c.Exec(ctx); err != nil {
		panic(err)
	}
}

// CustomerCreateBulk is the builder for creating many Customer entities in bulk.
type CustomerCreateBulk struct {
	config    runtime.Config
	err       error
	builders  []*CustomerCreate
	batchSize int
}

// NewCustomerCreateBulk creates a new CustomerCreateBulk builder.
func NewCustomerCreateBulk(c runtime.Config, builders []*CustomerCreate) *CustomerCreateBulk {
	return &CustomerCreateBulk{
		builders: builders,
		config:   c,
	}
}

// BatchSize sets the chunk size for the bulk insert.
// A value of 0 (default) means no chunking — all builders
// go through a single BatchCreate. When set, Save splits the
// builders into chunks of at most n and runs one INSERT per
// chunk. Use this to stay under SQLite's SQL-variable cap.
//
// Atomicity across chunks is NOT automatic. Wrap the call
// in client.Tx(ctx) if you need all-or-nothing semantics.
func (_cb *CustomerCreateBulk) BatchSize(n int) *CustomerCreateBulk {
	_cb.batchSize = n
	return _cb
}

// Save creates the Customer entities in the database.
//
// When BatchSize is 0 (default), all builders go through a
// single mutator chain ending in one BatchCreate. When
// BatchSize > 0, the builders are sliced into chunks of at
// most N and each chunk runs its own mutator chain + one
// INSERT. A mid-loop error returns the rows persisted so far
// together with the error — wrap in client.Tx(ctx) for
// all-or-nothing semantics.
func (_cb *CustomerCreateBulk) Save(ctx context.Context) ([]*entity.Customer, error) {
	if _cb.err != nil {
		return nil, _cb.err
	}
	if _cb.batchSize <= 0 || _cb.batchSize >= len(_cb.builders) {
		return _cb.saveChunk(ctx, _cb.builders)
	}
	nodes := make([]*entity.Customer, 0, len(_cb.builders))
	for start := 0; start < len(_cb.builders); start += _cb.batchSize {
		end := start + _cb.batchSize
		if end > len(_cb.builders) {
			end = len(_cb.builders)
		}
		chunk, err := _cb.saveChunk(ctx, _cb.builders[start:end])
		nodes = append(nodes, chunk...)
		if err != nil {
			return nodes, err
		}
	}
	return nodes, nil
}

// saveChunk runs one mutator chain over a sub-slice of the builders.
func (_cb *CustomerCreateBulk) saveChunk(ctx context.Context, builders []*CustomerCreate) ([]*entity.Customer, error) {
	if len(builders) == 0 {
		return []*entity.Customer{}, nil
	}
	specs := make([]*sqlgraph.CreateSpec, len(builders))
	nodes := make([]*entity.Customer, len(builders))
	mutators := make([]runtime.Mutator, len(builders))
	for i := range builders {
		func(i int, root context.Context) {
			builder := builders[i]
			var mut runtime.Mutator = runtime.MutateFunc(func(ctx context.Context, m runtime.Mutation) (runtime.Value, error) {
				mutation, ok := m.(*CustomerMutation)
				if !ok {
					return nil, fmt.Errorf("velox: unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				nodes[i].SetConfig(_cb.config)
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					if err = sqlgraph.BatchCreate(ctx, _cb.config.Driver, spec); err != nil {
						err = runtime.MayWrapConstraintError(err)
					}
				}
				if err != nil {
					return nil, err
				}
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
					mutation.SetID(int(id))
				}
				return nodes[i], nil
			})
			allHooks := builder.hooks
			for j := len(allHooks) - 1; j >= 0; j-- {
				mut = allHooks[j](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_cb *CustomerCreateBulk) SaveX(ctx context.Context) []*entity.Customer {
	v, err := _cb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_cb *CustomerCreateBulk) Exec(ctx context.Context) error {
	_, err := _cb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_cb *CustomerCreateBulk) ExecX(ctx context.Context) {
	if err := _cb.Exec(ctx); err != nil {
		panic(err)
	}
}
