// Code generated by velox. DO NOT EDIT.

package customerclient

// CreateCustomerInput represents a mutation input for creating customers.
type CreateCustomerInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	OrderIDs []int  `json:"orderIDs,omitempty"`
}

// Mutate applies the CreateCustomerInput on the CustomerMutation builder.
func (i *CreateCustomerInput) Mutate(m *CustomerMutation) {
	m.SetName(i.Name)
	m.SetEmail(i.Email)
	if len(i.OrderIDs) > 0 {
		m.AddOrderIDs(i.OrderIDs...)
	}
}

// SetInput applies the change-set in the CreateCustomerInput on the CustomerCreate builder.
func (c *CustomerCreate) SetInput(i CreateCustomerInput) *CustomerCreate {
	i.Mutate(c.Mutation())
	return c
}
