// Code generated by velox. DO NOT EDIT.

package customerclient

import (
	"context"
	"fmt"

	entity "github.com/syssam/graphql-go/examples/veloxfx/velox/entity"
	predicate "github.com/syssam/graphql-go/examples/veloxfx/velox/predicate"
	velox "github.com/syssam/velox"
	sql "github.com/syssam/velox/dialect/sql"
	runtime "github.com/syssam/velox/runtime"
)

// CustomerMutation represents an operation that mutates the Customer nodes in the graph.
type CustomerMutation struct {
	config        runtime.Config
	op            runtime.Op
	id            *int
	_name         *string
	_email        *string
	clearedFields map[string]struct{}
	oldValue      func(context.Context) (*entity.Customer, error)
	oldLoaded     bool
	oldCache      *entity.Customer
	orders        map[int]struct{}
	removedOrders map[int]struct{}
	clearedOrders bool
	predicates    []predicate.Customer
}

var _ velox.Mutation = (*CustomerMutation)(nil)

// customerOption allows management of the mutation configuration using functional options.
type customerOption func(*CustomerMutation)

// NewCustomerMutation creates new mutation for the Customer entity.
func NewCustomerMutation(c runtime.Config, op runtime.Op, opts ...customerOption) *CustomerMutation {
	m := &CustomerMutation{
		config: c,
		op:     runtime.Op(op),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// Op returns the operation name.
func (m *CustomerMutation) Op() runtime.Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *CustomerMutation) SetOp(op runtime.Op) {
	m.op = op
}

// Type returns the schema type name of this mutation ("Customer").
func (m *CustomerMutation) Type() string {
	return "Customer"
}

// ID returns the ID value in the mutation, if it was provided by the caller.
// The second bool return indicates whether the ID field was set.
func (m *CustomerMutation) ID() (id any, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetID sets the entity ID value on the mutation.
func (m *CustomerMutation) SetID(id int) {
	m.id = &id
}

// loadOld lazily loads the pre-mutation entity state for OldXxx methods.
func (m *CustomerMutation) loadOld(ctx context.Context) (*entity.Customer, error) {
	if m.op != runtime.OpUpdateOne {
		return nil, fmt.Errorf("OldField is only allowed on UpdateOne operations")
	}
	if m.oldValue == nil {
		return nil, fmt.Errorf("OldField is not supported: no old value loader configured")
	}
	if m.oldLoaded {
		return m.oldCache, nil
	}
	old, err := m.oldValue(ctx)
	if err != nil {
		return nil, fmt.Errorf("querying old values: %w", err)
	}
	m.oldCache = old
	m.oldLoaded = true
	return old, nil
}

// Where appends a list predicates to the CustomerMutation builder.
func (m *CustomerMutation) Where(ps ...predicate.Customer) {
	m.predicates = append(m.predicates, ps...)
}

// PredicatesFuncs returns the predicates as untyped selector functions.
func (m *CustomerMutation) PredicatesFuncs() []func(*sql.Selector) {
	ps := make([]func(*sql.Selector), len(m.predicates))
	for i, p := range m.predicates {
		ps[i] = p
	}
	return ps
}

// SetName sets the "name" field.
func (m *CustomerMutation) SetName(v string) {
	m._name = &v
}

// Name returns the value of the "name" field in the mutation.
func (m *CustomerMutation) Name() (r string, exists bool) {
	if m._name == nil {
		return
	}
	return *m._name, true
}

// ResetName resets all changes to the "name" field.
func (m *CustomerMutation) ResetName() {
	m._name = nil
	delete(m.clearedFields, "name")
}

// SetEmail sets the "email" field.
func (m *CustomerMutation) SetEmail(v string) {
	m._email = &v
}

// Email returns the value of the "email" field in the mutation.
func (m *CustomerMutation) Email() (r string, exists bool) {
	if m._email == nil {
		return
	}
	return *m._email, true
}

// ResetEmail resets all changes to the "email" field.
func (m *CustomerMutation) ResetEmail() {
	m._email = nil
	delete(m.clearedFields, "email")
}

// AddOrderIDs adds the "orders" edge to the Order entity by ids.
func (m *CustomerMutation) AddOrderIDs(ids ...int) {
	if m.orders == nil {
		m.orders = make(map[int]struct{})
	}
	for _, id := range ids {
		m.orders[id] = struct{}{}
	}
}

// RemoveOrderIDs removes the "orders" edge to the Order entity by ids.
func (m *CustomerMutation) RemoveOrderIDs(ids ...int) {
	if m.removedOrders == nil {
		m.removedOrders = make(map[int]struct{})
	}
	for _, id := range ids {
		delete(m.orders, id)
		m.removedOrders[id] = struct{}{}
	}
}

// ClearOrders clears the "orders" edge.
func (m *CustomerMutation) ClearOrders() {
	m.clearedOrders = true
}

// OrdersCleared reports if the "orders" edge was cleared.
func (m *CustomerMutation) OrdersCleared() bool {
	return m.clearedOrders
}

// RemovedOrdersIDs returns the removed IDs of the "orders" edge.
func (m *CustomerMutation) RemovedOrdersIDs() (ids []int) {
	for id := range m.removedOrders {
		ids = append(ids, id)
	}
	return
}

// ResetOrders resets all changes to the "orders" edge.
func (m *CustomerMutation) ResetOrders() {
	m.orders = nil
	m.clearedOrders = false
	m.removedOrders = nil
}

// OrdersIDs returns the "orders" edge IDs in the mutation.
func (m *CustomerMutation) OrdersIDs() (ids []int) {
	for id := range m.orders {
		ids = append(ids, id)
	}
	return
}

// Fields returns all fields that were changed during this mutation.
func (m *CustomerMutation) Fields() []string {
	var fields []string
	if m._name != nil {
		fields = append(fields, "name")
	}
	if m._email != nil {
		fields = append(fields, "email")
	}
	return fields
}

// Field returns the value of a field with the given name.
func (m *CustomerMutation) Field(name string) (runtime.Value, bool) {
	switch name {
	case "name":
		if m._name != nil {
			return *m._name, true
		}
	case "email":
		if m._email != nil {
			return *m._email, true
		}
	}
	return nil, false
}

// SetField sets the value of a field with the given name. It returns an error if the field is not defined in the schema, or if the value type does not match.
func (m *CustomerMutation) SetField(name string, value runtime.Value) error {
	switch name {
	case "name":
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field name", value)
		}
		m.SetName(v)
		return nil
	case "email":
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field email", value)
		}
		m.SetEmail(v)
		return nil
	default:
		return fmt.Errorf("unknown Customer field %s", name)
	}
}

// AddedFields returns all numeric fields that were incremented or decremented during this mutation.
func (m *CustomerMutation) AddedFields() []string {
	var fields []string
	return fields
}

// AddedField returns the numeric value that was incremented or decremented for a field.
func (m *CustomerMutation) AddedField(name string) (runtime.Value, bool) {
	switch name {
	}
	return nil, false
}

// AddField adds the value for the given name. It returns an error if the field is not defined in the schema, or if the value type does not match.
func (m *CustomerMutation) AddField(name string, value runtime.Value) error {
	switch name {
	default:
		return fmt.Errorf("unknown Customer addable field %s", name)
	}
}

// ClearedFields returns all fields that were cleared during this mutation.
func (m *CustomerMutation) ClearedFields() []string {
	var fields []string
	for f := range m.clearedFields {
		fields = append(fields, f)
	}
	return fields
}

// FieldCleared reports if a field with the given name was cleared in this mutation.
func (m *CustomerMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an error if the field is not defined in the schema or is not nullable.
func (m *CustomerMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Customer nullable field %s", name)
}

// ResetField resets all changes for the field with the given name. It returns an error if the field is not defined in the schema.
func (m *CustomerMutation) ResetField(name string) error {
	switch name {
	case "name":
		m._name = nil
		delete(m.clearedFields, "name")
	case "email":
		m._email = nil
		delete(m.clearedFields, "email")
	default:
		return fmt.Errorf("unknown Customer field %s", name)
	}
	return nil
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *CustomerMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.orders != nil {
		edges = append(edges, "orders")
	}
	return edges
}

// AddedIDs returns all IDs that were added for the given edge name.
func (m *CustomerMutation) AddedIDs(name string) []velox.Value {
	switch name {
	case "orders":
		ids := make([]velox.Value, 0, len(m.orders))
		for id := range m.orders {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *CustomerMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedOrders != nil {
		edges = append(edges, "orders")
	}
	return edges
}

// RemovedIDs returns all IDs that were removed for the given edge name.
func (m *CustomerMutation) RemovedIDs(name string) []velox.Value {
	switch name {
	case "orders":
		ids := make([]velox.Value, 0, len(m.removedOrders))
		for id := range m.removedOrders {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *CustomerMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedOrders {
		edges = append(edges, "orders")
	}
	return edges
}

// EdgeCleared reports if the given edge was cleared in this mutation.
func (m *CustomerMutation) EdgeCleared(name string) bool {
	switch name {
	case "orders":
		return m.clearedOrders
	}
	return false
}

// ClearEdge clears the value of the edge with the given name.
func (m *CustomerMutation) ClearEdge(name string) error {
	switch name {
	case "orders":
		m.ClearOrders()
		return nil
	}
	return fmt.Errorf("unknown Customer unique edge %s", name)
}

// ResetEdge resets all changes for the edge with the given name.
func (m *CustomerMutation) ResetEdge(name string) error {
	switch name {
	case "orders":
		m.ResetOrders()
		return nil
	}
	return fmt.Errorf("unknown Customer edge %s", name)
}

// OldField returns the old value of a field from the database.
// An error is returned if the mutation operation is not UpdateOne,
// or the query to the database fails.
func (m *CustomerMutation) OldField(ctx context.Context, name string) (velox.Value, error) {
	switch name {
	case "name":
		return m.OldName(ctx)
	case "email":
		return m.OldEmail(ctx)
	}
	return nil, fmt.Errorf("unknown Customer field %s", name)
}

// OldName returns the old "name" field value, if exists.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CustomerMutation) OldName(ctx context.Context) (v string, err error) {
	old, loadErr := m.loadOld(ctx)
	if loadErr != nil {
		err = loadErr
		return
	}
	v = old.Name
	return
}

// OldEmail returns the old "email" field value, if exists.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CustomerMutation) OldEmail(ctx context.Context) (v string, err error) {
	old, loadErr := m.loadOld(ctx)
	if loadErr != nil {
		err = loadErr
		return
	}
	v = old.Email
	return
}
