// Code generated by velox. DO NOT EDIT.

package customerclient

import (
	"context"
	"errors"
	"fmt"

	customer "github.com/syssam/graphql-go/examples/veloxfx/velox/customer"
	entity "github.com/syssam/graphql-go/examples/veloxfx/velox/entity"
	predicate "github.com/syssam/graphql-go/examples/veloxfx/velox/predicate"
	velox "github.com/syssam/velox"
	sql "github.com/syssam/velox/dialect/sql"
	sqlgraph "github.com/syssam/velox/dialect/sql/sqlgraph"
	runtime "github.com/syssam/velox/runtime"
	field "github.com/syssam/velox/schema/field"
)

// CustomerUpdate is the update builder for Customer entities.
//
// Query interceptors do NOT run on mutations. A row filter registered
// with Intercept() leaves this builder unscoped, so express row-level
// authorization as a schema Policy() — it covers reads and writes.
type CustomerUpdate struct {
	config    runtime.Config
	mutation  *CustomerMutation
	hooks     []runtime.Hook
	modifiers []func(*sql.UpdateBuilder)
}

// NewCustomerUpdate creates a new CustomerUpdate builder.
func NewCustomerUpdate(c runtime.Config, mutation *CustomerMutation, hooks []runtime.Hook) *CustomerUpdate {
	return &CustomerUpdate{
		config:   c,
		hooks:    hooks,
		mutation: mutation,
	}
}

// Where appends a list predicates to the CustomerUpdate builder.
func (_u *CustomerUpdate) Where(ps ...predicate.Customer) *CustomerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *CustomerUpdate) SetName(v string) *CustomerUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CustomerUpdate) SetNillableName(v *string) *CustomerUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *CustomerUpdate) SetEmail(v string) *CustomerUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *CustomerUpdate) SetNillableEmail(v *string) *CustomerUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// AddOrderIDs adds the "orders" edge by ids.
func (_u *CustomerUpdate) AddOrderIDs(ids ...int) *CustomerUpdate {
	_u.mutation.AddOrderIDs(ids...)
	return _u
}

// RemoveOrderIDs removes the "orders" edge by ids.
func (_u *CustomerUpdate) RemoveOrderIDs(ids ...int) *CustomerUpdate {
	_u.mutation.RemoveOrderIDs(ids...)
	return _u
}

// ClearOrders clears the "orders" edge.
func (_u *CustomerUpdate) ClearOrders() *CustomerUpdate {
	_u.mutation.ClearOrders()
	return _u
}

// AddOrders adds the "orders" edge to the given entities.
func (_u *CustomerUpdate) AddOrders(v ...*entity.Order) *CustomerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	_u.AddOrderIDs(ids...)
	return _u
}

// RemoveOrders removes the "orders" edge to the given entities.
func (_u *CustomerUpdate) RemoveOrders(v ...*entity.Order) *CustomerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	_u.RemoveOrderIDs(ids...)
	return _u
}

// Mutation returns the CustomerMutation.
func (_u *CustomerUpdate) Mutation() *CustomerMutation {
	return _u.mutation
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CustomerUpdate) Modify(modifiers ...func(*sql.UpdateBuilder)) *CustomerUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

// check runs the user-defined validators on the fields this mutation sets
// and guards required unique edges against being cleared.
func (_u *CustomerUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := customer.NameValidator(v); err != nil {
			return &runtime.ValidationError{
				Entity: "Customer",
				Err:    fmt.Errorf("validator failed for field \"Customer.name\": %w", err),
				Field:  "name",
				Name:   "name",
			}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := customer.EmailValidator(v); err != nil {
			return &runtime.ValidationError{
				Entity: "Customer",
				Err:    fmt.Errorf("validator failed for field \"Customer.email\": %w", err),
				Field:  "email",
				Name:   "email",
			}
		}
	}
	return nil
}

// sqlSave executes the SQL update for Customer after hooks have run.
func (_u *CustomerUpdate) sqlSave(ctx context.Context) (int, error) {
	if err := _u.check(); err != nil {
		return 0, err
	}
	spec := sqlgraph.NewUpdateSpec(customer.Table, customer.Columns, &sqlgraph.FieldSpec{
		Column: customer.FieldID,
		Type:   customerIDFieldType,
	})
	if _u.mutation._name != nil {
		spec.SetField("name", field.TypeString, *_u.mutation._name)
	}
	if _u.mutation._email != nil {
		spec.SetField("email", field.TypeString, *_u.mutation._email)
	}
	ps := _u.mutation.PredicatesFuncs()
	if len(ps) > 0 {
		spec.Predicate = func(s *sql.Selector) {
			for i := range ps {
				ps[i](s)
			}
		}
	}
	if _u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"customer_orders"},
			Inverse: false,
			Rel:     sqlgraph.O2M,
			Table:   "orders",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		spec.Edges.Clear = append(spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOrdersIDs(); len(nodes) > 0 && !_u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"customer_orders"},
			Inverse: false,
			Rel:     sqlgraph.O2M,
			Table:   "orders",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		spec.Edges.Clear = append(spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"customer_orders"},
			Inverse: false,
			Rel:     sqlgraph.O2M,
			Table:   "orders",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		spec.Edges.Add = append(spec.Edges.Add, edge)
	}
	if len(_u.modifiers) > 0 {
		spec.AddModifiers(_u.modifiers...)
	}
	affected, err := sqlgraph.UpdateNodes(ctx, _u.config.Driver, spec)
	if err != nil {
		return 0, runtime.MayWrapConstraintError(err)
	}
	return affected, nil
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CustomerUpdate) Save(ctx context.Context) (int, error) {
	hooks := _u.hooks
	return velox.WithHooks[int, CustomerMutation, *CustomerMutation](ctx, _u.sqlSave, _u.mutation, hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CustomerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CustomerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CustomerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// CustomerUpdateOne is the update builder for a single Customer entity.
type CustomerUpdateOne struct {
	config       runtime.Config
	mutation     *CustomerMutation
	hooks        []runtime.Hook
	modifiers    []func(*sql.UpdateBuilder)
	selectFields []string
}

// NewCustomerUpdateOne creates a new CustomerUpdateOne builder.
func NewCustomerUpdateOne(c runtime.Config, mutation *CustomerMutation, hooks []runtime.Hook) *CustomerUpdateOne {
	return &CustomerUpdateOne{
		config:   c,
		hooks:    hooks,
		mutation: mutation,
	}
}

// Where appends a list predicates to the CustomerUpdateOne builder.
func (_u *CustomerUpdateOne) Where(ps ...predicate.Customer) *CustomerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema. It narrows
// only what is read back — every field set on this builder is still written.
func (_u *CustomerUpdateOne) Select(field string, fields ...string) *CustomerUpdateOne {
	_u.selectFields = append([]string{field}, fields...)
	return _u
}

// SetName sets the "name" field.
func (_u *CustomerUpdateOne) SetName(v string) *CustomerUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CustomerUpdateOne) SetNillableName(v *string) *CustomerUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *CustomerUpdateOne) SetEmail(v string) *CustomerUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *CustomerUpdateOne) SetNillableEmail(v *string) *CustomerUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// AddOrderIDs adds the "orders" edge by ids.
func (_u *CustomerUpdateOne) AddOrderIDs(ids ...int) *CustomerUpdateOne {
	_u.mutation.AddOrderIDs(ids...)
	return _u
}

// RemoveOrderIDs removes the "orders" edge by ids.
func (_u *CustomerUpdateOne) RemoveOrderIDs(ids ...int) *CustomerUpdateOne {
	_u.mutation.RemoveOrderIDs(ids...)
	return _u
}

// ClearOrders clears the "orders" edge.
func (_u *CustomerUpdateOne) ClearOrders() *CustomerUpdateOne {
	_u.mutation.ClearOrders()
	return _u
}

// AddOrders adds the "orders" edge to the given entities.
func (_u *CustomerUpdateOne) AddOrders(v ...*entity.Order) *CustomerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	_u.AddOrderIDs(ids...)
	return _u
}

// RemoveOrders removes the "orders" edge to the given entities.
func (_u *CustomerUpdateOne) RemoveOrders(v ...*entity.Order) *CustomerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	_u.RemoveOrderIDs(ids...)
	return _u
}

// Mutation returns the CustomerMutation.
func (_u *CustomerUpdateOne) Mutation() *CustomerMutation {
	return _u.mutation
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CustomerUpdateOne) Modify(modifiers ...func(*sql.UpdateBuilder)) *CustomerUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

// check runs the user-defined validators on the fields this mutation sets
// and guards required unique edges against being cleared.
func (_u *CustomerUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := customer.NameValidator(v); err != nil {
			return &runtime.ValidationError{
				Entity: "Customer",
				Err:    fmt.Errorf("validator failed for field \"Customer.name\": %w", err),
				Field:  "name",
				Name:   "name",
			}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := customer.EmailValidator(v); err != nil {
			return &runtime.ValidationError{
				Entity: "Customer",
				Err:    fmt.Errorf("validator failed for field \"Customer.email\": %w", err),
				Field:  "email",
				Name:   "email",
			}
		}
	}
	return nil
}

// sqlSave executes the SQL update for a single Customer after hooks have run.
func (_u *CustomerUpdateOne) sqlSave(ctx context.Context) (*entity.Customer, error) {
	if err := _u.check(); err != nil {
		return nil, err
	}
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, errors.New("velox: missing ID for UpdateOne")
	}
	spec := sqlgraph.NewUpdateSpec(customer.Table, customer.Columns, &sqlgraph.FieldSpec{
		Column: customer.FieldID,
		Type:   customerIDFieldType,
	})
	if _u.mutation._name != nil {
		spec.SetField("name", field.TypeString, *_u.mutation._name)
	}
	if _u.mutation._email != nil {
		spec.SetField("email", field.TypeString, *_u.mutation._email)
	}
	spec.Node.ID.Value = id
	ps := _u.mutation.PredicatesFuncs()
	spec.Predicate = func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(customer.FieldID), id))
		for i := range ps {
			ps[i](s)
		}
	}
	if _u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"customer_orders"},
			Inverse: false,
			Rel:     sqlgraph.O2M,
			Table:   "orders",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		spec.Edges.Clear = append(spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOrdersIDs(); len(nodes) > 0 && !_u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"customer_orders"},
			Inverse: false,
			Rel:     sqlgraph.O2M,
			Table:   "orders",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		spec.Edges.Clear = append(spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Bidi:    false,
			Columns: []string{"customer_orders"},
			Inverse: false,
			Rel:     sqlgraph.O2M,
			Table:   "orders",
			Target: &sqlgraph.EdgeTarget{IDSpec: &sqlgraph.FieldSpec{
				Column: "id",
				Type:   field.TypeInt,
			}},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		spec.Edges.Add = append(spec.Edges.Add, edge)
	}
	if len(_u.modifiers) > 0 {
		spec.AddModifiers(_u.modifiers...)
	}
	if err := sqlgraph.UpdateNode(ctx, _u.config.Driver, spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			return nil, velox.NewNotFoundError("Customer")
		}
		return nil, runtime.MayWrapConstraintError(err)
	}
	columns := customer.Columns
	if len(_u.selectFields) > 0 {
		columns = make([]string, 0, len(_u.selectFields)+1)
		columns = append(columns, customer.FieldID)
		for _, f := range _u.selectFields {
			if !customer.ValidColumn(f) {
				return nil, &runtime.ValidationError{
					Entity: "Customer",
					Err:    errors.New("invalid field for query"),
					Field:  f,
					Name:   f,
				}
			}
			if f != customer.FieldID {
				columns = append(columns, f)
			}
		}
	}
	build := func(_ context.Context) (*sql.Selector, error) {
		s := sql.Select(columns...).From(sql.Table(customer.Table))
		s.SetDialect(_u.config.Driver.Dialect())
		s.Where(sql.EQ(s.C(customer.FieldID), id))
		s.Limit(1)
		return s, nil
	}
	_node, err2 := runtime.ScanFirst[entity.Customer, *entity.Customer](ctx, _u.config.Driver, build, "Customer")
	if err2 != nil {
		return nil, err2
	}
	_node.SetConfig(_u.config)
	return _node, nil
}

// Save executes the query and returns the updated Customer entity.
func (_u *CustomerUpdateOne) Save(ctx context.Context) (*entity.Customer, error) {
	_u.mutation.oldValue = func(ctx context.Context) (*entity.Customer, error) {
		id, ok := _u.mutation.ID()
		if !ok {
			return nil, errors.New("velox: missing ID for OldField")
		}
		build := func(_ context.Context) (*sql.Selector, error) {
			s := sql.Select(customer.Columns...).From(sql.Table(customer.Table))
			s.SetDialect(_u.config.Driver.Dialect())
			s.Where(sql.EQ(s.C(customer.FieldID), id))
			s.Limit(1)
			return s, nil
		}
		_old, err := runtime.ScanFirst[entity.Customer, *entity.Customer](ctx, _u.config.Driver, build, "Customer")
		if err != nil {
			return nil, err
		}
		_old.SetConfig(_u.config)
		return _old, nil
	}
	hooks := _u.hooks
	return velox.WithHooks[*entity.Customer, CustomerMutation, *CustomerMutation](ctx, _u.sqlSave, _u.mutation, hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CustomerUpdateOne) SaveX(ctx context.Context) *entity.Customer {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CustomerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CustomerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}
