// Code generated by velox. DO NOT EDIT.

package warehouse

import (
	predicate "github.com/syssam/graphql-go/examples/veloxfx/velox/predicate"
	sql "github.com/syssam/velox/dialect/sql"
	sqlgraph "github.com/syssam/velox/dialect/sql/sqlgraph"
	runtime "github.com/syssam/velox/runtime"
)

const (
	// Label holds the string label denoting the Warehouse type in the database.
	Label = "warehouse"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeStocks holds the string denoting the stocks edge name in mutations.
	EdgeStocks = "stocks"
	// Table holds the table name of the Warehouse in the database.
	Table = "warehouses"
	// StocksTable is the table that holds the stocks relation/edge.
	StocksTable = "stocks"
	// StocksInverseTable is the table name for the Stock entity.
	// It exists in this package in order to avoid circular dependency with the "stock" package.
	StocksInverseTable = "stocks"
	// StocksColumn is the table column denoting the stocks relation/edge.
	StocksColumn = "warehouse_stocks"
)

// Columns holds all SQL columns for Warehouse fields.
var Columns = []string{FieldID, FieldName}

// ForeignKeys holds the SQL foreign-keys that are owned by the "warehouses"
// table and are not defined as standalone fields in the schema.
var ForeignKeys []string

// columnSet holds the set of valid column names for O(1) lookups.
var columnSet = func() map[string]struct{} {
	s := make(map[string]struct{}, 2)
	for _, c := range Columns {
		s[c] = struct{}{}
	}
	return s
}()

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	_, ok := columnSet[column]
	return ok
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
)

// OrderOption defines the ordering options for the Warehouse queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByStocksCount orders the results by stocks count.
func ByStocksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newStocksStep(), opts...)
	}
}

// ByStocks orders the results by stocks terms.
func ByStocks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStocksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newStocksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(sqlgraph.From(Table, FieldID), sqlgraph.To(StocksInverseTable, FieldID), sqlgraph.Edge(sqlgraph.O2M, false, StocksTable, StocksColumn))
}

// =============================================================================
// LoadOption helpers (functional options for edge loading)
// =============================================================================

// Where returns a LoadOption that adds predicates to the edge query.
func Where(ps ...predicate.Warehouse) runtime.LoadOption {
	return func(c *runtime.LoadConfig) {
		for _, p := range ps {
			c.Predicates = append(c.Predicates, (func(*sql.Selector))(p))
		}
	}
}

// Select returns a LoadOption that selects specific fields.
func Select(fields ...string) runtime.LoadOption {
	return runtime.Select(fields...)
}

// Limit returns a LoadOption that limits the number of results.
func Limit(n int) runtime.LoadOption {
	return runtime.Limit(n)
}

// OrderBy returns a LoadOption that orders the results.
func OrderBy(o ...func(*sql.Selector)) runtime.LoadOption {
	return runtime.OrderBy(o...)
}

// WithStocks returns a LoadOption that eager-loads the "stocks" edge.
func WithStocks(opts ...runtime.LoadOption) runtime.LoadOption {
	return runtime.WithEdge("stocks", opts...)
}
