// Code generated by gqlc. DO NOT EDIT.

// Package order holds the types generated from the GraphQL schema.
package order

type PlaceOrderInput struct {
	CustomerID  int                   `graphql:"customerID"`
	WarehouseID int                   `graphql:"warehouseID"`
	Items       []PlaceOrderItemInput `graphql:"items"`
}

type PlaceOrderItemInput struct {
	ProductID int `graphql:"productID"`
	Quantity  int `graphql:"quantity"`
}
