// Code generated by gqlc. DO NOT EDIT.

// Package product holds the generated GraphQL bindings for the product group.
package product

import (
	"context"

	"github.com/syssam/graphql-go"
	product "github.com/syssam/graphql-go/examples/veloxfx/velox/client/product"
	entity "github.com/syssam/graphql-go/examples/veloxfx/velox/entity"
)

type CreateProductArgs struct {
	Input product.CreateProductInput `graphql:"input"`
}

type UpdateProductArgs struct {
	ID    graphql.ID                 `graphql:"id"`
	Input product.UpdateProductInput `graphql:"input"`
}

type DeleteProductArgs struct {
	ID graphql.ID `graphql:"id"`
}

// Resolver holds methods for fields that are not struct data.
type Resolver interface {
	CreateProduct(ctx context.Context, args CreateProductArgs) (*entity.Product, error)
	UpdateProduct(ctx context.Context, args UpdateProductArgs) (*entity.Product, error)
	DeleteProduct(ctx context.Context, args DeleteProductArgs) (graphql.ID, error)
	ProductID(ctx context.Context, obj *entity.Product) (graphql.ID, error)
	Products(ctx context.Context) ([]*entity.Product, error)
}

func Bindings(r Resolver) graphql.SchemaOption {
	return graphql.Options(
		graphql.Input[product.CreateProductInput]("CreateProductInput", graphql.ZeroForNull()),
		graphql.Input[product.UpdateProductInput]("UpdateProductInput", graphql.ZeroForNull()),
		graphql.Object[entity.Product]("Product",
			graphql.Resolve("id", func(ctx context.Context, v *entity.Product) (graphql.ID, error) { return r.ProductID(ctx, v) }),
			graphql.Field("sku", func(v *entity.Product) string { return v.Sku }),
			graphql.Field("name", func(v *entity.Product) string { return v.Name }),
			graphql.Field("priceCents", func(v *entity.Product) int { return v.PriceCents }),
			graphql.Resolve("category", func(ctx context.Context, v *entity.Product) (*entity.Category, error) { return v.Category(ctx) }),
			graphql.Resolve("stocks", func(ctx context.Context, v *entity.Product) ([]*entity.Stock, error) { return v.Stocks(ctx) }),
			graphql.Resolve("orderItems", func(ctx context.Context, v *entity.Product) ([]*entity.OrderItem, error) { return v.OrderItems(ctx) }),
		),
		graphql.Query(
			graphql.Resolve("products", func(ctx context.Context, _ graphql.Root) ([]*entity.Product, error) { return r.Products(ctx) }),
		),
		graphql.Mutation(
			graphql.ResolveArgs("createProduct", func(ctx context.Context, _ graphql.Root, a CreateProductArgs) (*entity.Product, error) {
				return r.CreateProduct(ctx, a)
			}),
			graphql.ResolveArgs("updateProduct", func(ctx context.Context, _ graphql.Root, a UpdateProductArgs) (*entity.Product, error) {
				return r.UpdateProduct(ctx, a)
			}),
			graphql.ResolveArgs("deleteProduct", func(ctx context.Context, _ graphql.Root, a DeleteProductArgs) (graphql.ID, error) {
				return r.DeleteProduct(ctx, a)
			}),
		),
		graphql.Args[CreateProductArgs](),
		graphql.Args[UpdateProductArgs](),
		graphql.Args[DeleteProductArgs](),
	)
}
